### ISSUE TITLE
Trying to run any build after 12.3.5 migration results in registry.useXDeprecatedProvider is not a function

### ISSUE THREAD

**Issue by Splaktar** [nrwl/nx#5829]
## Current Behavior

`ng build` fails

## Expected Behavior

`ng build` still works after migration

## Steps to Reproduce

1. `nx migrate 12.3.5`
2. `npm i`
3. `nx migrate --run-migrations`
4. `ng build --configuration=staging`

If I downgrade to `12.3.4`, this works fine. It also worked fine on the previous version we were on (`12.3.1`).

### Failure Logs

```
> nx run xlts-dev:build:staging
registry.useXDeprecatedProvider is not a function
```

### Environment

```
  Node : 14.16.1
  OS   : darwin x64
  npm  : 6.14.13
  
  nx : Not Found
  @nrwl/angular : 12.3.5
  @nrwl/cli : 12.3.5
  @nrwl/cypress : 12.3.5
  @nrwl/devkit : 12.3.5
  @nrwl/eslint-plugin-nx : 12.3.5
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.5
  @nrwl/linter : 12.3.5
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.5
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.5
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

```

**Comment by jredl-va** [comment]
Would be related too: https://github.com/nrwl/nx/pull/5807/files

It sounds like your workspace is missing the nx angular decorator: https://github.com/nrwl/nx-examples/blob/master/decorate-angular-cli.js

Which in turn is wired up with a post install script: https://github.com/nrwl/nx-examples/blob/master/package.json#L26


Will leave it too the nx team to comment on the actual fix, but the above will allow you to use ng commands within a nx workspace (simply passing them thru to nx).

**Comment by Splaktar** [comment]
I have 
```json
  "postinstall": "node ./decorate-angular-cli.js && ngcc --properties es2015 browser module main"
```
I also have `decorate-angular-cli.js` in my workspace root.

**Comment by Splaktar** [comment]
I created a whole new Nx workspace and refactored my app to match it very closely. Unfortunately, it didn't help with this issue in `12.3.5`, but it works fine in `12.3.4`.

**Comment by leosvelperez** [comment]
@Splaktar thanks for reporting this!

I tried to reproduce this issue in 2 ways:

- Creating a 12.3.1 workspace and migrating it to 12.3.5.
- Creating a 12.3.5 workspace.

In both scenarios the build worked well, I was not able to reproduce the problem. This seems weird, this is the line which could cause it https://github.com/nrwl/nx/blob/master/packages/tao/src/commands/ngcli-adapter.ts#L53, but the `useXDeprecatedProvider` is a function defined in the `CoreSchemaRegistry` as it can be seen here https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/core/src/json/schema/registry.ts#L627.

Could you share a reproduction of the issue so we can have a look?

Please note 12.3.4 has issues with CI which were solved in 12.3.5.

**Comment by Splaktar** [comment]
Oh, I'm so glad that https://github.com/nrwl/nx/issues/5729 is fixed! I've been trying to figure out that insane behavior all night long.

Unfortunately, I can still reproduce this issue when I put the `node ./decorate-angular-cli.js` back in the `postinstall` script. If I take it out, then `ng build` works fine.

When I get this `registry.useXDeprecatedProvider is not a function` issue, it happens right at the start of the build, almost instantly (`Executed in: < 1s`). The error code is `1`.

**Comment by Splaktar** [comment]
It looks like this is probably caused by https://github.com/nrwl/nx/pull/5807/files#diff-5efae550d183a15e666d390e483c77c408a3759bce9480a29fd89e330d9ef0caR51.

I'm trying to test that in my `node_modules/@nrwl/tao/src/commands/ngcli-adapter.js` but I'm not quite sure how the old generated code looked. I'll try to install the previous version as a reference.

**Comment by Splaktar** [comment]
I can verify that with everything else on `12.3.5` and `"@nrwl/tao": "12.3.4",`, my builds work using Nx.

**Comment by Splaktar** [comment]
Indeed, if I comment out this line, it works fine:
```js
registry.useXDeprecatedProvider((msg) => logger.warn(msg));
```

**Comment by Splaktar** [comment]
```
Angular CLI: 12.0.2
Node: 14.16.1
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            9.1.15
@angular-devkit/schematics      9.1.15
@angular/fire                   6.1.5
@schematics/angular             9.1.15
ng-packagr                      12.0.2
rxjs                            6.6.7
typescript                      4.2.4
```
```js
$ npm ls @angular-devkit/core
xlts.dev@1.0.1 /Users/splaktar/Git/xlts/xlts.dev
├─┬ @angular-devkit/build-angular@12.0.2
│ ├─┬ @angular-devkit/architect@0.1200.2
│ │ └── @angular-devkit/core@12.0.2 
│ └── @angular-devkit/core@12.0.2 
├─┬ @angular/cli@12.0.2
│ ├── @angular-devkit/core@12.0.2 
│ ├─┬ @angular-devkit/schematics@12.0.2
│ │ └── @angular-devkit/core@12.0.2  deduped
│ └─┬ @schematics/angular@12.0.2
│   └── @angular-devkit/core@12.0.2  deduped
├─┬ @nrwl/angular@12.3.5
│ ├─┬ @angular-devkit/schematics@12.0.2
│ │ └── @angular-devkit/core@12.0.2 
│ └─┬ @schematics/angular@12.0.2
│   └── @angular-devkit/core@12.0.2  deduped
├─┬ @schuchard/prettier@5.0.0
│ ├── @angular-devkit/core@11.0.5 
│ └─┬ @angular-devkit/schematics@11.0.5
│   └── @angular-devkit/core@11.0.5  deduped
└─┬ @scullyio/init@1.1.4
  ├── @angular-devkit/core@9.1.15 
  ├─┬ @angular-devkit/schematics@9.1.15
  │ └── @angular-devkit/core@9.1.15  deduped
  ├─┬ @schematics/angular@9.1.15
  │ └── @angular-devkit/core@9.1.15  deduped
  └─┬ schematics-utilities@2.0.3
    ├── @angular-devkit/core@8.3.29 
    ├─┬ @angular-devkit/schematics@8.3.29
    │ └── @angular-devkit/core@8.3.29  deduped
    ├─┬ @schematics/angular@8.3.29
    │ └── @angular-devkit/core@8.3.29  deduped
    └─┬ @schematics/update@0.803.29
      ├── @angular-devkit/core@8.3.29 
      └─┬ @angular-devkit/schematics@8.3.29
        └── @angular-devkit/core@8.3.29  deduped
```
If your not careful, you might import a version of `@angular-devkit/core` that isn't the latest.

For a reproduction, you might try taking a normal Nx project and doing [`ng add @scullyio/init`](https://scully.io/docs/learn/getting-started/installation/).

**Comment by Splaktar** [comment]
We've seen the same kind of issues with getting the wrong version of `@angular/dev-kit/schematics` in Angular Material.

**Comment by leosvelperez** [comment]
> @angular-devkit/architect       0.1200.2
> @angular-devkit/build-angular   12.0.2
> @angular-devkit/core            9.1.15
> @angular-devkit/schematics      9.1.15
> @angular/fire                   6.1.5
> @schematics/angular             9.1.15
> ng-packagr                      12.0.2

Yep, the Angular packages are not in sync here and this particular issue would be caused by the `@angular-devkit/core` package being in v9.1.15. The `useXDeprecatedProvider` was introduced in v10.1.0.

The Angular versions are expected to be in sync. I did try to reproduce it on an Nx 12.3.5 workspace by doing `ng add @scullyio/init` but it works well, the `@angular-devkit/core` package is correctly resolved to 12.0.2. I guess this was probably a result of a bad migration, probably that v9.x.x has been in the project for quite some time 🙂

By upgrading those to v12.0.2 the issue should be resolved.

**Comment by Splaktar** [comment]
It's not as simple as you seem to be interpreting it. I don't think that it has anything to do with a bad migration. All of the Angular packages in my `package.json` are `12.0.2`.

I can try to regenerate my `package-lock.json`.

**Comment by leosvelperez** [comment]
Yep, that can also be the case. It's a problem with npm sometimes, where depending on when dependencies are installed, the resolution is not always the same. We've faced this issue with other deps in the past and sadly the solution has been to remove the lock file and node_modules and reinstall.

**Comment by Splaktar** [comment]
OK, I deleted `package-lock.json`, removed `node_modules/` and did `npm i` again. This is what I have now:
```js
r$ npm ls @angular-devkit/core
xlts.dev@1.0.1 /Users/splaktar/Git/xlts/xlts.dev
├─┬ @angular-devkit/build-angular@12.0.2
│ ├─┬ @angular-devkit/architect@0.1200.2
│ │ └── @angular-devkit/core@12.0.2  deduped
│ └── @angular-devkit/core@12.0.2 
├─┬ @angular/cli@12.0.2
│ ├── @angular-devkit/core@12.0.2  deduped
│ ├─┬ @angular-devkit/schematics@12.0.2
│ │ └── @angular-devkit/core@12.0.2  deduped
│ └─┬ @schematics/angular@12.0.2
│   └── @angular-devkit/core@12.0.2  deduped
├─┬ @schuchard/prettier@5.0.0
│ ├── @angular-devkit/core@11.2.13 
│ └─┬ @angular-devkit/schematics@11.2.13
│   └── @angular-devkit/core@11.2.13  deduped
└─┬ @scullyio/init@1.1.4
  ├── @angular-devkit/core@9.1.15 
  ├─┬ @angular-devkit/schematics@9.1.15
  │ └── @angular-devkit/core@9.1.15  deduped
  ├─┬ @schematics/angular@9.1.15
  │ └── @angular-devkit/core@9.1.15  deduped
  └─┬ schematics-utilities@2.0.3
    ├── @angular-devkit/core@8.3.29 
    ├─┬ @angular-devkit/schematics@8.3.29
    │ └── @angular-devkit/core@8.3.29  deduped
    ├─┬ @schematics/angular@8.3.29
    │ └── @angular-devkit/core@8.3.29  deduped
    └─┬ @schematics/update@0.803.29
      ├── @angular-devkit/core@8.3.29 
      └─┬ @angular-devkit/schematics@8.3.29
        └── @angular-devkit/core@8.3.29  deduped
```

**Comment by Splaktar** [comment]
It does seem like the Angular CLI is at least defaulting to the newer versions now though, even though many old versions are still required by other libs:
```js
Angular CLI: 12.0.2
Node: 14.16.1
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@angular/fire                   6.1.5
@schematics/angular             12.0.2
ng-packagr                      12.0.2
rxjs                            6.6.7
typescript                      4.2.4
```

**Comment by leosvelperez** [comment]
Is it working now or is the build still broken? With those versions it should be fine, `@nrwl/tao` should use the right version of the `@angular-devkit/core` now.

**Comment by Splaktar** [comment]
Yeah, it seems to be working now. Since `@nrwl/tao` doesn't have a dependency on `@angular-devkit/core`, this kind of thing can happen pretty easily when there are a lot of different versions of it due to different libraries and tools. It usually results in very hard to understand errors. The Angular CLI team is aware that this kind of problem exists and it keeps coming back up again and again. I think that they have a design for a solution and are working towards getting there at some point in the future.

**Comment by Splaktar** [comment]
I'm not sure why I'm getting these warnings now when building:
```ts
Option "extractCss" is deprecated: Deprecated since version 11.0. No longer required to disable CSS extraction for HMR.
Option "showCircularDependencies" is deprecated: The recommended method to detect circular dependencies in project code is to use either a lint rule or other external tooling.
```
I don't have either of these things set in my `angular.json`. Perhaps that's something from the Nx packages?

**Comment by leosvelperez** [comment]
You can disregard it for now, it's just a warning which is appearing now precisely because we added the `useXDeprecatedProvider` to warn about deprecations, but it seems we might be passing the default values to the scheduled target as if they were specified by the dev in the config. I'll have a look to correct that tomorrow.

**Comment by Splaktar** [comment]
OK, thank you for helping investigate and solve this!

**Comment by Splaktar** [comment]
Was there a fix for the warnings?

**Comment by leosvelperez** [comment]
There is this PR open https://github.com/nrwl/nx/pull/5845 that'll fix it. I closed this one since the original issue was solved.

**Comment by mackelito** [comment]
Just tried a migrate to angular 12 and for me the builds fail `Could not execute web-client:build because it has a circular dependency`
