### ISSUE TITLE
Migrating from 14.3.5 to 15.1.0 can fail; and even without failing, the project is in an incomplete state.

### ISSUE THREAD

**Issue by fbartho** [nrwl/nx#13205]
## Current Behavior
Our monorepo uses NX 14.3.5 with on-the-order of 20-30 applications. We’re trying to `nx migrate` from 14.3.5 to the latest version.

The tools successfully generate a migrations.json, and when we try to apply them, 2 of the migrations die.
The migrations that die are related to jest config, and maybe should be a separate ticket?
<details>
<summary>The failed migrations (here).</summary>

```json
{
	"version": "14.5.5-beta.0",
	"cli": "nx",
	"description": "Exclude jest.config.ts from tsconfig where missing.",
	"factory": "./src/migrations/update-14-0-0/update-jest-config-ext",
	"package": "@nrwl/jest",
	"name": "exclude-jest-config-from-ts-config"
},
{
	"version": "14.6.0-beta.0",
	"cli": "nx",
	"description": "Update jest configs to support jest 28 changes (https://jestjs.io/docs/upgrading-to-jest28#configuration-options)",
	"factory": "./src/migrations/update-14-6-0/update-configs-jest-28",
	"package": "@nrwl/jest",
	"name": "update-configs-jest-28"
}
```
</details>

Even if I manually patch the migrations.json to skip the problem migrations, it looks like there’s a missing feature in the migrations.

The migrations appear to take the `architect` node out of each project in our workspace.json, and shove it under an `nx` node in each of the project’s package.json, but they don’t clean up the workspace.json.

It’s unclear what was supposed to happen, but I suspect the workspace.json is supposed to be pruned down to a minimum set of fields if the architect node is moved into the package.json files.

## Expected Behavior

The failing the migrations is definitely a big problem, since I don’t know exactly where the migrations live to review their code. I’d expect the migrations to succeed, and log diagnostics on any issues the migrations cannot correct. If it fails fatally, it needs to log how I’m supposed to proceed.

At the next level is that deprecating workspace.json is a breaking change in NX 15, and I suspect we need a migration to help merge our project the right way. Or if there is already a partial migration, the work needs to be finished so it fully deletes workspace.json if that’s no longer valid. I’ve also requested a documentation update related to this In #13191

## Steps to Reproduce

1. Create a project that has all of its nx config in workspace.json (no project.json)
2. Migrate from 14.3.5 to 15.1.0

I have not attempted to reproduce this with nx-examples yet, but I can try if a maintainer thinks it would be valuable and worth the time.

### Failure Logs

The original failure logs are no longer a problem with 15.1.1, unfortunately the remaining behavior is still inconsistent, even though there are no failure logs.

### Environment

<details>
<summary>NX Report Output</summary>

```
   Node : 17.9.1
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.1.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.1.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.1.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.1.0
   @nrwl/expo : Not Found
   @nrwl/express : 15.1.0
   @nrwl/jest : 15.1.0
   @nrwl/js : 15.1.0
   @nrwl/linter : 15.1.0
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.1.0
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : 15.1.0
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.1.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.1.0
   @nrwl/webpack : 15.1.0
   @nrwl/workspace : 15.1.0
   typescript : 4.9.3
   ---------------------------------------
   Local workspace plugins:
         @hca/package-generator
   ---------------------------------------
   Community plugins:
```

</details>

**Comment by fbartho** [comment]
Okay, replicating the migration today, it selects `nx 15.1.1` instead of `15.1.0` -- and the migrations succeed without fatal errors.

Unfortunately, they still leave my workspace.json in an inconsistent state where I have target-commands in both workspace.json and in each application/library's package.json.

Please advise?

**Comment by jewe11er** [comment]
I got a error with module-federation after updating from 14 to 15.1.1 with `nx migrate latest`

`import('@nrwl/react/module-federation').ModuleFederationConfig` doesn't work in version 15

I tried to change it to `import('@nrwl/devkit').ModuleFederationConfig` and got a error
`Cannot find module '@nrwl/devkit' or its corresponding type declarations`
