### ISSUE TITLE
Automatically shared package includes sample projects from npm package

### ISSUE THREAD

**Issue by pschnoop** [nrwl/nx#10094]
We have a microfrontend setup where one of our apps is using gojs.
The gojs package itself contains sample projects. 
These are found by the mechanism to automatically share dependencies between microfrontends which leads to errors.

## Current Behavior
It is not possible to build microfrontends if used npm package contains samples.

## Expected Behavior
We can build microfrontends if npm packages contains sample projects.
Worked in 13.10.1, failed with 14.0.5.

## Steps to Reproduce
[See this sample. ](https://github.com/pschnoop/nx-bug-gojs)
```
yarn install
yarn build my-microfrontend
```

### Failure Logs
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/62992625/166240936-42cf996a-656b-4908-a05e-ba594357fcb9.png">
`maximalsource` is a sample project in `node_modules/gojs/projects`

### Environment
<img width="304" alt="image" src="https://user-images.githubusercontent.com/62992625/166241135-f1e4213d-67c7-4eb0-ade9-068a9358df60.png">

**Comment by ak274** [comment]
I also faced this issue while using Ag-Grid in my project..

**Comment by ak274** [comment]
@leosvelperez I have updated my project to latest release and now compilation failed with different error

![image](https://user-images.githubusercontent.com/16129430/167073741-a2a46b9c-f966-4495-9dcc-78aee2e4743c.png)
