### ISSUE TITLE
Visual Studio Code detects Jasmine instead of Jest in Jest test specification

### ISSUE THREAD

**Issue by stijnvn** [nrwl/nx#816]
Visual Studio Code detects Jasmine instead of Jest. 

When I try to use the ```toBeObservable``` matcher, I get the following error message:

```
[ts] Property 'toBeObservable' does not exist on type 'Matchers<...>'
```

The problem seems to be related with how Visual Studio Code resolves type definitions. It does not uses the `tsconfig.spec.json` but still seems to use the imports defined in `test-setup.ts`. As a workaround I have added an import for Jest on top of `test-setup.ts`:

```typescript
import 'jest';
import 'jest-preset-angular';
```

Can this be fixed in nx? Or should this be fixed in Visual Studio Code?

**Comment by skydever** [comment]
hi @stijnvn 

samehow the same on my side. I did not use jest specific matchers like said [here](https://github.com/nrwl/nx/issues/752) (and you are using [jest-marbles](https://www.npmjs.com/package/jest-marbles)?) that is why I did not run into issues concerning that - expect for the intellisense in vscode. I get `jasmine.matchers` methods, but when I add the jest import in the `test-setup.ts` like you did I get `jest.Matchers` correctly.

I think it is a vscode issue, shouldn't it respect the `compilerOptions.types` from `tsconfig.spec.json`? ... from the *nearest* matching `tsconfig` that includes the file? that should enable the jest matchers, or do I miss something?

do you have a matcher *at hand* from pure `jest` that does not exist in `jasmine` to play around with?

**Comment by skydever** [comment]
... and are you using a vscode extension for jest? just wondering, I use [vscode-jest](https://github.com/jest-community/vscode-jest), but not very actively at the moment ...

**Comment by skydever** [comment]
thx for the info about the extension.

I can confirm that vscode seems to only check a `tsconfig.json` - I created a `tsconfig.json` next to my spec file and the jest matchers came up, when I rename to `tsconfig.spec.json` I get the jasmine matchers.

**Comment by skydever** [comment]
... found [this](https://github.com/Microsoft/TypeScript/issues/21473#issuecomment-361836082) typescript issue, and [this](https://github.com/Microsoft/vscode/issues/12463) vscode issue...

**Comment by skydever** [comment]
tried to explicitly `import { expect } from 'jest';` in the spec file, but I get 
`[ts] File '.../node_modules/@types/jest/index.d.ts' is not a module`
When I open the file I see the following errors:
```
[ts] Definitions of the following identifiers conflict with those in another file: describe, fdescribe, xdescribe, it, fit, xit, beforeEach, afterEach, beforeAll, afterAll, expect, clock, CustomEqualityTester, CustomMatcherFactory, DEFAULT_TIMEOUT_INTERVAL
index.d.ts(14, 1): Conflicts are in this file.
```
and at the named identifiers
```
[ts] Duplicate identifier 'beforeAll'.
index.d.ts(14, 18): 'beforeAll' was also declared here.
```

The link points to `@types/jasminewd2/index.d.ts` and `@types/jasmine/index.d.ts`, that also have errors because of duplications.

I thought if I stick to use imports like above this name clashing could not happen. Any thoughts on that?

**Comment by golfadas** [comment]
Webstorm has this issue as well

**Comment by sandangel** [comment]
you need to uninstall jasmine and @types/jasmine to have correct type in your IDE. or specify the types config in tsconfig.json to include jest

**Comment by skydever** [comment]
hi @sandangel 

you will need `@types/jasmine` for your e2e tests if you use the jasmine+protractor combination, so uninstalling it may be no solution.

adding `"jasmine", "jasminewd2", "jest", "jest-marbles"` to the types at `tsconfig.json` at the root results to listing the jasmine matchers in vscode (there is this conflict), removing `"jasmine", "jasminewd2"` but keeping `"jest", "jest-marbles"` results to the jest matchers, but at the e2e test you also get the jest matchers then, but you don't want that because jasmine is used ... vscode is looking at `tsconfig.json` only, the execution is using the correct `tsconfig.spec.json` - different behavior here 🤔

**Comment by sandangel** [comment]
of course, you should not use protractor either. use cypress for that ^^

**Comment by skydever** [comment]
I am not sure if that would help - you may add the cypress typings at the `tsconfig.e2e.json` that vscode is ignoring too - not sure about conflicts, did not use cypress before - but yes, I am very interested in doing so and can't wait for #819 from @bcabanes 👍

**Comment by skydever** [comment]
... but renaming `tsconfig.e2e.json` to `tsconfig.json` would help, it is a separate project with one tsconfig only, no explicit need for different names like at the app level for `tsconfig.spec.json` and `tsconfig.app.json` ...

**Comment by skorunka** [comment]
Hi, is really the only solution to rename `tsconfig.spec.json` to `tsconfig.json`? It works, but one needs to update angular.json and keep it in mind when generating libs/apps.

**Comment by stijnvn** [comment]
@FrozenPandaz What about the workaround of adding `import 'jest';` to `test-setup.ts`? I seems to do the job and I haven't seen any side effects.

**Comment by golfadas** [comment]
@FrozenPandaz appending `/// <reference types="..."` to test files makes webstorm detect the typings correctly, but it still gets confused on how to run the tests (this might be a webstorm issue though...)

**Comment by FrozenPandaz** [comment]
> @FrozenPandaz What about the workaround of adding `import 'jest';` to `test-setup.ts`? I seems to do the job and I haven't seen any side effects.

This is interesting. Do you know how this works?

**Comment by goelinsights** [comment]
@FrozenPandaz any insights from how you've set up new apps with cypress in nx 7.0?

Encountered the issue when updating nx of an existing workspace to 7.0.0, so I'd imagine you've made it compatible for new 7.0.0 applications.

**Comment by Jdruwe** [comment]
Where can I find the documentation?

**Comment by pkamdem** [comment]
@Jdruwe [Here](https://github.com/FrozenPandaz/nx/wiki/Workspace-Organization#tsconfigs). Still in draft stage though.

**Comment by micksatana** [comment]
> > @FrozenPandaz What about the workaround of adding `import 'jest';` to `test-setup.ts`? I seems to do the job and I haven't seen any side effects.
> 
> This is interesting. Do you know how this works?
> 
> There are projects which will not have the test-setup.ts because it does not require it.

Adding `test-setup.ts` to the projects which required jest and adding `import 'jest';` to `test-setup.ts` fixed the problem for me. My guess when we `import 'jest'`, typescript use functions in jest module in all the test files, the vscode then see those types correctly.

**Comment by Stronhold** [comment]
Still same error using Jasmine + Cypress in VS Code. Any workaround?

**Comment by danielgeri** [comment]
@Stronhold did you include a tsconfig.json file inside your cypress folder? https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json

**Comment by Stronhold** [comment]
Yes, I do have. In fact it is created by the schematic

**Comment by soupman99** [comment]
@danielgeri @Stronhold  I'm having the same issue.  I included the tsconfig in the cypress folder but still get `
Property 'toBeTruthy' does not exist on type 'Assertion'`

**Comment by sanidz** [comment]
> @danielgeri @Stronhold I'm having the same issue. I included the tsconfig in the cypress folder but still get ` Property 'toBeTruthy' does not exist on type 'Assertion'` Any solution?

I might be wrong, but I am trinking about creating separate "child" project for cypress only, because cypress typings messes jasmine typings in karma tests.
Only con is slightly different scripts for cypress open and run...

**Comment by AltarBeastiful** [comment]
Could you show us how you did separate cypress and your main project ? 
Thinking about this too as there seems to be no other solution to have code completion in both cypress and unit tests.

**Comment by sanidz** [comment]
> Could you show us how you did separate cypress and your main project ?
> Thinking about this too as there seems to be no other solution to have code completion in both cypress and unit tests.

There is also one more "workaround", just add empty import statement inside .spec.ts file like this:

import { } from 'jasmine';

and methods such as .toHaveBeenCalled, .toBeTruthy and all jasmine.Matchers should be recognised.

🔨

**Comment by AltarBeastiful** [comment]
Still get errors using the empty import.

The only time vscode picks up correctly jasmine is when I uninstall cypress package.
I'm considering splitting the projects, but the added complexity is pretty annoying for us.

**Comment by krokofant** [comment]
@AltarBeastiful I excluded the cypress folder from the root tsconfig.json file and that fixed it for me

**Comment by AltarBeastiful** [comment]
Adding an exclude works, in my root tsconfig.json I have: 
```
,
  "exclude": [
    "e2e"
  ]
```

Thanks ! I'll open a PR to cypress doc to document this.

**Comment by isthatcentered** [comment]
Adding ``ìmport "cypress"```in ```app/myapp-e2e/src/support/index.ts``` did the trick for me with phpstorm :).

**Comment by mfechner** [comment]
I created a file in `apps/backend/src/test-setup.ts` with:
```
import 'jest';
```
but it does not help, has there maybe something changed with nx 8.4.3?

**Comment by danielsmeyer** [comment]
> but it does not help, has there maybe something changed with nx 8.4.3?

Fix is working for me in 8.4.3

**Comment by martijnsenden** [comment]
> Adding ` import "cypress"` in `app/myapp-e2e/src/support/index.ts` did the trick for me with phpstorm 🥳
> 
> Does it work for anyone else ?

It does for me. Thanks!

**Comment by maximedupre** [comment]
> Adding an exclude works, in my root tsconfig.json I have:
> 
> ```
> ,
>   "exclude": [
>     "e2e"
>   ]
> ```
> 
> Thanks ! I'll open a PR to cypress doc to document this.

For those of you trying out this solution, I also had to add `exclude: []` to my `/e2e/tsconfig.json`, or Visual Studio Code could not resolve the `Cypress` namespace.

**Comment by hamzahsn** [comment]
@maximedupre could you give more context? could you post your `tsconfig` files for cypress and root project? also I think the solution of @danielgeri should work normally without any issues.

**Comment by sentient06** [comment]
This is a nightmare.
