### PR TITLE
fix(testing): use @swc/jest if being used as transformer

### LINKED ISSUE #11836: v14.6.2 - jest 28 - React fails with 3rd party js
## Current Behavior
When running a test on a component that imports `@headlessui/react`, the transformer fails.
While debugging, I saw that [babel-jest transformer](https://github.com/nrwl/nx/blob/9b26bc1585f6bf70f135e15304a3d2975c47a187/packages/react/plugins/jest.ts#L47-L55) return an object with `createTransform` instead of a transformer.

Additionally - in our tests, we are using `@swc/jest` so I expected it to grab its transformer, not babel's.
Changing those lines to use `@swc/jest` makes it work.

## Expected Behavior
Tests should not break.

## Steps to Reproduce
* Create a repo with React app
* Install `@headlessui/react`
* Import and use it in your component
* Run jest 

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
```sh
 Test suite failed to run

    TypeError: transformer.process is not a function

      at Object.process (../../packages/react/plugins/jest.ts:37:43)
      at ScriptTransformer.transformSource (../../node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
      at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:822:19)

```

### Environment
```sh
 Node : 16.16.0
   OS   : darwin arm64
   yarn : 3.2.3
   
   nx : 14.6.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.6.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.6.2
   @nrwl/eslint-plugin-nx : 14.6.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.6.2
   @nrwl/js : 14.6.2
   @nrwl/linter : 14.6.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.6.2
   @nrwl/nx-cloud : 14.6.0
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.6.2
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.6.2
   @nrwl/web : 14.6.2
   @nrwl/workspace : 14.6.2
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         rxjs: 6.6.7
         nx-stylelint: 13.5.3

```

### LINKED ISSUE #12723: Jest option "transformIgnorePatterns" don't work with Nx 14.8/15 and React
We have a generator for React Ionic templates but trying with a default react app adding Ionic dependencies, the result is the same.

## Expected Behavior
Jest is able to run the test.
I'm not sure what version it broke. With 14.5 it was working; with 14.8 not. At some point in between it broke.

## Steps to Reproduce
- Create a React app using @nrwl/react package.
- Import a component from Ionic:
e.g.
```
import {IonApp, setupIonicReact} from '@ionic/react';

setupIonicReact();

export function App() {
  return (
    <IonApp>
      <h1>Hello World</h1>
    </IonApp>
  );
}

export default App;
```
- add transformIgnorePatterns to the jest config
```
  transformIgnorePatterns: [
    'node_modules/(?!(@ionic/react|@ionic/react-router|@ionic/core|@stencil/core|ionicons)/)',
  ],
```
- run 'nx test <appname>'

### Failure Logs
nx run reactapp:test

 FAIL   reactapp  apps/reactapp/src/app/app.spec.tsx
  ● Test suite failed to run

    TypeError: transformer.process is not a function

      at Object.process (../../packages/react/plugins/jest.ts:37:43)
      at ScriptTransformer.transformSource (../../node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
      at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:822:19)
      at Object.<anonymous> (../../node_modules/@stencil/core/internal/client/index.js:24:1)
      at Object.<anonymous> (../../node_modules/@ionic/core/components/index.js:4:1)
      at Object.<anonymous> (../../node_modules/@ionic/react/dist/index.js:7:20)
      at Object.<anonymous> (src/app/app.tsx:2:1)
      at Object.<anonymous> (src/app/app.spec.tsx:3:1)

### Environment
Node : 16.13.1
   OS   : darwin x64
   yarn : 1.22.15

   nx : 14.8.5
   @nrwl/angular : 14.8.5
   @nrwl/cypress : 14.8.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.5
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.5
   @nrwl/js : 14.8.5
   @nrwl/linter : 14.8.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.8.5
   @nrwl/nx-cloud : 15.0.0
   @nrwl/nx-plugin : 14.8.5
   @nrwl/react : 14.8.5
   @nrwl/react-native : Not Found
   @nrwl/rollup : 14.8.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.5
   @nrwl/web : 14.8.5
   @nrwl/webpack : 14.8.5
   @nrwl/workspace : 14.8.5
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @nxext/ionic-react: 999.9.9

### PR DESCRIPTION
**Pull request by barbados-clemens**
## Current Behavior

always using babel-jest then swc/jest even if tests where using babel-jest.
babel-jest not calling `createTransformer()`

## Expected Behavior

use swc/jest when the tests are configured for swc/jest
when using babel-jest correctly call the transformer

## Related Issue(s)

Fixes #11836 
Fixes #12723

### CODE REVIEW

**Comment by neil-hughes** [comment]
Hi! I'm not sure of the etiquette here but is there anything I can do to help get this fix merged? Our CI is currently blocked as all tests are failing due to the change in transformer API. Ping me if I can be of any service.

**Comment by danr-za** [comment]
Same as the above ❤️

**Review by jaysoo — APPROVED** [review]
LGTM!
