### ISSUE TITLE
autogenerated type import path fails during build on nextjs 13 app directory, not finding layout file

### ISSUE THREAD

**Issue by marianzburlea** [nrwl/nx#14558]
### Current Behavior

![image](https://user-images.githubusercontent.com/1318985/214098925-de44e378-0150-450f-b73a-9d09612f038c.png)

### Expected Behavior

Build successfully without errors.

### Steps to Reproduce

All I need to do to reproduces it is to enable app dir:

![image](https://user-images.githubusercontent.com/1318985/214099736-c0e3b5be-fd76-416b-9ae5-4c0c547f4775.png)

in a NextJS project.

While running `nx serve my-next`, the **appDir** works fine,
when running `nx build my-next`, the error above happens.

I can see the file generated during the build process that is dealing with types has a wrong path:

![image](https://user-images.githubusercontent.com/1318985/214099294-5b1d2606-80dd-43f2-a1ae-32421a91e174.png)

### Nx Report

```shell
$ nx build my-next

> nx run my-next:build:production

warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback

info  - Creating an optimized production build  
info  - Compiled successfully
info  - Skipping linting
info  - Checking validity of types ..Failed to compile.

Type error: Cannot find module '../../../../app/layout' or its corresponding type declarations.


 ——————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project my-next (2s)
 
    ✖    1/1 failed
    ✔    0/1 succeeded [0 read from cache]
 
   View structured, searchable error logs at https://nx.app/runs/lWgLCc4scB
```

### Additional Information

Just a very basic **@nrwl/next** project, with `appDir` enabled, fails on build.

**Comment by Shooshte** [comment]
Bump, having the same issue, with a nested `page.tsx`. So the full path is `app/battle/[id]/page.ts` and the error I am getting is:
> Type error: Cannot find module '../../../../../../app/battle/[id]/page' or its corresponding type declarations.

**Comment by AndriiTsok** [comment]
Hello, we experiencing the same issue. Currently, the dev/prod builds are affected. 

```info  - Loaded env from apps/vto-legal/.env
warn  - You have enabled experimental feature (appDir) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.
info  - Thank you for testing `appDir` please leave your feedback at https://nextjs.link/app-feedback
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Skipping linting
info  - Checking validity of types ...Failed to compile.

Type error: Cannot find module '../../../../app/layout' or its corresponding type declarations.```

Workarounds with tsconfig and exclude do not work.

**Comment by Fetten** [comment]
I came across this behavior as well. The issue seems to be related to Next.js adding the `types` directory, that is created during build, to the tsconfig, which then cannot be resolved.

**Workaround**
The type error does not occur when the build directory is inside the Next.js app directory itself. This can be changed in the project.json config by modifying the `outputPath` of the build target:

```diff
"targets": {
  "build": {
    "executor": "@nrwl/next:build",
    "outputs": ["{options.outputPath}"],
    "defaultConfiguration": "production",
    "options": {
      "root": "apps/next-app",
-      "outputPath": "dist/apps/next-app"
+      "outputPath": "apps/next-app/dist"
    },
  },
```

**Comment by AndriiTsok** [comment]
@Fetten thank you for the workaround! Have you tried it for standalone outputs?

**Comment by Fetten** [comment]
> @Fetten thank you for the workaround! Have you tried it for standalone outputs?

@AndriiTsok, No, haven't tried it yet in standalone mode.

**Comment by marianzburlea** [comment]
It looks like NX is not supporting NextJS 13, since no one in the entire world can use
`nx build my-app`.

Does anyone know if NX is planning to support Next 13 any time soon or is it back to Next 12 for production?

**Comment by ianldgs** [comment]
It seems to build in next@13.2.1. However, it's putting the build output on `apps/my-app/.next` instead of in `dist/apps/my-app/.next`.

**Comment by ianldgs** [comment]
Ok, it seems like next@13.2.1 breaks nx:

https://github.com/vercel/next.js/pull/45455
https://github.com/vercel/next.js/issues/46374#issuecomment-1446065787

https://github.com/nrwl/nx/issues/15214

**Comment by ianldgs** [comment]
I've made a temporary fix for next@13.1.6, which is still compatible with NX in case anyone wants to try out.

```json
  "pnpm": {
    "overrides": {
      "next": "npm:@ian-patches/next@13.1.6-patch-1"
    }
  }
```

**Comment by ianldgs** [comment]
Opened a PR in next to fix it. Also release a patch for 13.2.4:

```json
  "pnpm": {
    "overrides": {
      "next": "npm:@ian-patches/next@13.2.4-patch-2"
    }
  }
```

**Comment by hakobpogh** [comment]
> I came across this behavior as well. The issue seems to be related to Next.js adding the `types` directory, that is created during build, to the tsconfig, which then cannot be resolved.
> 
> **Workaround** The type error does not occur when the build directory is inside the Next.js app directory itself. This can be changed in the `project.json` config by modifying the `outputPath` of the build target:
> 
> ```diff
> "targets": {
>   "build": {
>     "executor": "@nrwl/next:build",
>     "outputs": ["{options.outputPath}"],
>     "defaultConfiguration": "production",
>     "options": {
>       "root": "apps/next-app",
> -      "outputPath": "dist/apps/next-app"
> +      "outputPath": "apps/next-app/dist"
>     },
>   },
> ```

This one worked for me as a hotfix. I hope nx + next will resolve this soon.

**Comment by Jordaneisenburger** [comment]
Also encountering this issue, should have checked GH earlier instead of waisting hours of headaches :)

**Comment by giva9712** [comment]
we need a permanent solution instead of playing with project.json

**Comment by ianldgs** [comment]
Hi all! Can you try with `next@13.2.5-canary.29` / `next@13.2.5-canary.30`?

**Comment by dev360** [comment]
The next@13.3.0 release fixed it for me as well.

**Comment by leosvelperez** [comment]
This has been fixed in the latest versions of Nx and Next.js. Please note the `appDir` setting is no longer needed as of Next.js 13.4.0 (https://nextjs.org/docs/app/api-reference/next-config-js/appDir).

I'm closing this. If you still face issues related to this using the latest versions, feel free to leave a comment or open a new issue with updated details.
