### ISSUE TITLE
Cannot find module '@phenomnomnominal/tsquery' + update-babel-jest-transform-option from @nrwl/react

### ISSUE THREAD

**Issue by webpro** [nrwl/nx#12570]
Posting this here just in case others may face the same issue.

When migrating from v14.5.10 to 14.8.4 I had the error as shown below. The workaround is to install the package before the migration:

```
npm install @phenomnomnominal/tsquery
```

This should get things going again. I guess it's safe to remove it again afterwards.

## Current Behavior

```
❯ npx nx migrate --run-migrations

 >  NX   Running 'npm install' to make sure necessary packages are installed


[...]
 >  NX   Running migrations from 'migrations.json'


 >  NX   Failed to run update-babel-jest-transform-option from @nrwl/react. This workspace is NOT up to date!


 >  NX   Cannot find module '@phenomnomnominal/tsquery'

   Require stack:
   - .../node_modules/@nrwl/react/src/migrations/update-14-6-0/add-preset-jest-config.js
   - /private/var/folders/n4/0pyh5xbd6kv_ksrk0nz6xsp00000gn/T/tmp-46289-fPIbirm3Pzq8/node_modules/nx/src/command-line/migrate.js
   - /private/var/folders/n4/0pyh5xbd6kv_ksrk0nz6xsp00000gn/T/tmp-46289-fPIbirm3Pzq8/node_modules/nx/src/command-line/nx-commands.js
   - /private/var/folders/n4/0pyh5xbd6kv_ksrk0nz6xsp00000gn/T/tmp-46289-fPIbirm3Pzq8/node_modules/nx/bin/init-local.js
   - /private/var/folders/n4/0pyh5xbd6kv_ksrk0nz6xsp00000gn/T/tmp-46289-fPIbirm3Pzq8/node_modules/nx/bin/nx.js
   Pass --verbose to see the stacktrace.
```

## Expected Behavior

That the package is part of the dependency tree where it belongs so we don't get this error.

## Steps to Reproduce

Coming from v14.15.10 (not sure if there other variants from/to with the same issue):

```
npx nx migrate latest
npx nx migrate latest
```

### Environment

```
❯ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.17.1
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx : 14.8.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.8.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.4
   @nrwl/js : 14.8.4
   @nrwl/linter : 14.8.4
   @nrwl/nest : Not Found
   @nrwl/next : 14.8.4
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.8.4
   @nrwl/react-native : Not Found
   @nrwl/rollup : 14.8.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.4
   @nrwl/web : 14.8.4
   @nrwl/webpack : 14.8.4
   @nrwl/workspace : 14.8.4
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @nxext/capacitor: 14.0.0
```
