### ISSUE TITLE
Auto import from shared lib doesn't work in "@nx/next": "16.5.1"

### ISSUE THREAD

**Issue by RowinVanAmsterdam** [nrwl/nx#18107]
### Current Behavior

When using a component which is defined in a shared lib, the auto import doesn't recognise it. 

I've a clean NX project with a NextJS project and a shared react lib. As soon as I want to use a component that is in the shared lib, I have to type the import manually. Like so: `import { Typography } from '@frontend/jsx-core';`

If I add a second component, the auto-import does recognise it and can update it automatically! But only if the import is already there. I also have an older NX project with @nrwl and that one does work like expected. 

### Expected Behavior

I would expect that if I use a component that is in a shared lib, I'll see the error: 
`Cannot find name 'YourComponent'.`

And after hovering over the error, I would expect the 'quick fix': Import X from '@frontend/jsx-core'

### GitHub Repo
https://github.com/RowinVanAmsterdam/gamesource

Make sure to be on feature/shared-lib branch

### Steps to Reproduce

1. cd frontend/
2. npm install
3. go to ./app/platform/app/page.tsx
4. try to import  <Typography /> via auto import from '@frontend/jsx-core'

### Nx Report

```shell
Node   : 19.1.0
   OS     : darwin-arm64
   npm    : 9.1.2
   
   nx                 : 16.5.1
   @nx/js             : 16.5.1
   @nx/jest           : 16.5.1
   @nx/linter         : 16.5.1
   @nx/workspace      : 16.5.1
   @nx/cypress        : 16.5.1
   @nx/devkit         : 16.5.1
   @nx/eslint-plugin  : 16.5.1
   @nx/next           : 16.5.1
   @nx/react          : 16.5.1
   @nrwl/tao          : 16.5.1
   @nx/web            : 16.5.1
   typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Old project with nrwl, where it does work: https://github.com/koiosonline/koios.world--leg

**Comment by RowinVanAmsterdam** [comment]
Fixed itself
