### ISSUE TITLE
Error after updating to 15.1.1

### ISSUE THREAD

**Issue by jewe11er** [nrwl/nx#13211]
## Current Behavior

I got a error with module-federation after updating from 15.0.4 to 15.1.1

Error: `import('@nrwl/react/module-federation').ModuleFederationConfig` doesn't exist

I tried to change it to `import('@nrwl/devkit').ModuleFederationConfig` and got a error
`Cannot find module '@nrwl/devkit' or its corresponding type declarations`
Also I can't install `@nrwl/devkit`

## Expected Behavior

Project start successful

## Steps to Reproduce

1. Create project as written in this article:
`https://nx.dev/recipes/module-federation/faster-builds`
2. Update it with `nx migrate latest`
3. Run `nx migrate --run-migrations`
4. Run `nx serve host --open --devRemotes=APP_NAME`

**Comment by GraxMonzo** [comment]
Hi @jewe11er, I just ran into the same problem.
Problem is that this type is now in a different package.
```diff
/**
- * @type {import('@nrwl/react/module-federation').ModuleFederationConfig}
+ * @type {import('@nrwl/devkit').ModuleFederationConfig}
**/
```

**Comment by GraxMonzo** [comment]
My bad, I didn't notice that you already tried that.

**Comment by AgentEnder** [comment]
@jewe11er It sounds like you may need to first install @nrwl/devkit from the error message.

**Comment by Coly010** [comment]
What is the reason you can't install `@nrwl/devkit`?

This error shouldn't get thrown, but the solution will be to have the generator install the devkit package as a dev dependency.

**Comment by Coly010** [comment]
I don't get this error on a new workspace with Nx 15.2.0, can you try again with latest?

**Comment by nvonbenken** [comment]
I just spun up a brand new workspace and a MFE solution with `npx nx g @nrwl/react:host shell` and encountered the problem. This was on Nx 15.0.12.

Running `npx nx migrate latest` brought me up to Nx 15.2.1 and I'm still seeing the error.
