### ISSUE TITLE
Daemon received a message from different workspace and refuses to process ( windows )

### ISSUE THREAD

**Issue by JelleBruisten** [nrwl/nx#36722]
### Current Behavior

NX   The Nx Daemon for 'd:\path....' received a message from a different workspace ('D:\path...') and refused to process it. This usually means multiple workspaces are sharing a socket directory; ensure NX_SOCKET_DIR (or NX_DAEMON_SOCKET_DIR) is not set to a shared location.

This happens when an AI in this case claude executes some nx commands ( like linting ), and you yourself with a powershell window try to run the same command yourself.

Currently to fix, is to stop claude, vscode, stop the deamon. And then try it yourself again. Digging through it it seems that claude in its shell lowercases the drive number while powershell passes it as uppercase.

### Expected Behavior

Should work ( and did work before nx [23.2.0-beta.6](https://github.com/nrwl/nx/releases/tag/23.2.0-beta.6)

### Steps to Reproduce

1.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 24.18.0
OS             : win32-x64
Native Target  : x86_64-windows
pnpm           : 11.9.0
daemon         : Available

nx (global)        : 23.0.1
nx                 : 23.2.0-beta.7
@nx/js             : 23.2.0-beta.7
@nx/eslint         : 23.2.0-beta.7
@nx/workspace      : 23.2.0-beta.7
@nx/angular        : 23.2.0-beta.7
@nx/cypress        : 23.2.0-beta.7
@nx/devkit         : 23.2.0-beta.7
@nx/eslint-plugin  : 23.2.0-beta.7
@nx/node           : 23.2.0-beta.7
@nx/oxlint         : 23.2.0-beta.7
@nx/playwright     : 23.2.0-beta.7
@nx/plugin         : 23.2.0-beta.7
@nx/vite           : 23.2.0-beta.7
@nx/vitest         : 23.2.0-beta.7
@nx/web            : 23.2.0-beta.7
typescript         : 6.0.3

Nx key
---------------------------------------
(getPowerpackLicenseInformationAsync ?? getPowerpackLicenseInformation) is not a function

---------------------------------------
Community plugins:
@analogjs/vite-plugin-angular : 2.6.4
@analogjs/vitest-angular      : 2.6.4
@jsverse/transloco            : 8.4.0
@ngrx/component-store         : 21.1.1
@ngrx/operators               : 21.1.1
@ngrx/schematics              : 21.1.1
@ngrx/signals                 : 21.1.1
@nx/azure-cache               : 5.0.7
angular-eslint                : 22.1.0
```

### Failure Logs

```shell

```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by atsjo** [comment]
this bug is now released with 23.1.2, AI is not needed to reproduce...

after upgrading from 23.1.1 -> 23.1.2, it happens when running any command via nx console:

NX   The Nx Daemon for 'd:\repos\...' received a message from a different workspace ('D:\repos\...') and refused to process it. This usually means multiple workspaces are sharing a socket directory; ensure NX_SOCKET_DIR (or NX_DAEMON_SOCKET_DIR) is not set to a shared location.

**Comment by JelleBruisten** [comment]
@atsjo I only encountered when running a command by cli and another process or shell does the same or different commands. Even both are in the same directory etc.

Anyway this seems to be cause:
https://github.com/nrwl/nx/pull/36370/changes#diff-fd796367dff7448827ef735597fc0bcd5e52dbc7ab4b4eedca406aca51c232a0

**Comment by atsjo** [comment]
Nx 23.1.2 on windows (with pnpm) is broken, can't run any commands, notifying @AgentEnder as the author of the PR mentioned above...

```
D:\repos\test>pnpm nx build client --verbose

 NX   The Nx Daemon for 'd:\repos\test' received a message from a different workspace ('D:\repos\test') and refused to process it. This usually means multiple workspaces are sharing a socket directory; ensure NX_SOCKET_DIR (or NX_DAEMON_SOCKET_DIR) is not set to a shared location.

Error: The Nx Daemon for 'd:\repos\test' received a message from a different workspace ('D:\repos\test') and refused to process it. This usually means multiple workspaces are sharing a socket directory; ensure NX_SOCKET_DIR (or NX_DAEMON_SOCKET_DIR) is not set to a shared location.
    at assertNotForeignWorkspaceMessage (D:\repos\test\node_modules\.pnpm\nx@23.1.2_@swc-node+registe_1ccd5f9cf54afa4ef544ce0e33801e9f\node_modules\nx\dist\src\daemon\message-types\daemon-message.js:29:15)
    at handleMessage (D:\repos\test\node_modules\.pnpm\nx@23.1.2_@swc-node+registe_1ccd5f9cf54afa4ef544ce0e33801e9f\node_modules\nx\dist\src\daemon\server\server.js:126:67)
    at D:\repos\test\node_modules\.pnpm\nx@23.1.2_@swc-node+registe_1ccd5f9cf54afa4ef544ce0e33801e9f\node_modules\nx\dist\src\daemon\server\server.js:82:15
    at Socket.<anonymous> (D:\repos\test\node_modules\.pnpm\nx@23.1.2_@swc-node+registe_1ccd5f9cf54afa4ef544ce0e33801e9f\node_modules\nx\dist\src\utils\consume-messages-from-socket.js:27:21)
    at Socket.emit (node:events:514:20)
    at addChunk (node:internal/streams/readable:568:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:519:3)
    at Readable.push (node:internal/streams/readable:399:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)
```

**Comment by JelleBruisten** [comment]
Note were also using pnpm here, might be related?

**Comment by JelleBruisten** [comment]
@atsjo I made a potentional fix, could you check the linked PR https://github.com/nrwl/nx/pull/36835 if this would fix your problem?

Also tagging @AgentEnder

**Comment by atsjo** [comment]
the PR should definitely fix it, I tested 23.1.2 using a workaround described in https://github.com/nrwl/nx-console/issues/3115, and if I manually set NX_WORKSPACE_ROOT_PATH to my workspace path with small drive letter it works fine

**Comment by AgentEnder** [comment]
> @atsjo I made a potentional fix, could you check the linked PR https://github.com/nrwl/nx/pull/36835 if this would fix your problem?
> 
> Also tagging @AgentEnder 

Thanks for the tag, really didnt think the drive letter casing would vary so much... and in my windows testing it wasnt something I had ran into.

Does anyone know why it would vary? Seems odd but definitely what you are seeing in the error.messages.

**Comment by JelleBruisten** [comment]
@AgentEnder I'm not 100% sure why it happens, however it seems VS code lowercases the drive letters?

It normalizes something File://D:/ to lowercase drive letter, so any extensions etc inherit the lowercase?
And a normal shell/terminal, keeps the uppercase by default.

Its my best guess, and I have no idea why it would do this.

**Comment by atsjo** [comment]
@AgentEnder I would look into nx-console vs-code extension, and how it interacts with the daemon vs running nx from command line...

If I disable nx-console everything works fine... When nx-console is enabled, the startup initialization performed by the extension seems to "lock" the daemon into using the wrong path, and daemon requests from running nx from command line doesn't work after that...

**Comment by AgentEnder** [comment]
Yeah, at the end of the day knowing exactly why doesn't matter a ton here in that we have a working fix and its merged, pending backport + release. If the vscode extension path normalization handles drive casing differently that makes sense, and in either case the paths are equivalent so the new check is more correct.

**Comment by fasergeyte** [comment]
I had this issue in VS Code on Windows and I investigated it locally. There are several reasons that cause such behavior:

1. This happened because I use the bash terminal, and by default it opens the workspace with a lowercase drive letter (`/c/my-workspace/`), but PowerShell opens with uppercase (`C:/my-workspace/`). The workaround was to do cd `/C/my-workspace` and nx reset (maybe it can be configured in VS Code settings).

2. The second reason is trickier: when we use a package manager that uses symlinks. Symlinks use the case of the drive letter that was in the terminal when you run `npm i`. And when Node executes `fs.realpath`, it may change the letter on inconsistent paths (including `require('some-module')` and `require.resolve('some-module')`, as it uses realpath under the hood). Screnshot shows how node resolves symlinks that was created in terminals with different cases

<img width="583" height="393" alt="Image" src="https://github.com/user-attachments/assets/65634cec-59e9-49b6-aed5-ee6e4fac2473" />

ps: hope my investigation will help, and removes your curiosity how that happen 😊
