### ISSUE TITLE
Angular-cli v6 support schedule

### ISSUE THREAD

**Issue by noelmace** [nrwl/nx#412]
Angular-cli v6 RC2 [has already been released](https://github.com/angular/angular-cli/releases/tag/v6.0.0-rc.2), introducing some changes which could have an important impact on Nrwl/Nx, and a stable version [should be released soon along with Angular 6](https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md#tentative-schedule-until-april-2018).

Given that the [dependencies doesn't play well together](https://github.com/nrwl/nx/issues/362#issuecomment-376719677) for now, I started to investigate the subject (see the [associated branch](https://github.com/noelmace/nx/tree/angular-cli-6)).

I propose to list here all the required actions we could identify, and to handle as many of them as I can by myself, following your guidance (@vsavkin, @jeffbcross).

This is not a "feature request", just a discussion / scheduling proposition.

#### Fix build errors - DONE

* [x] TypeScript 2.7 in schematics/angular (https://github.com/angular/devkit/issues/651) (https://github.com/angular/devkit/pull/655) - example : ``packages/schematics/src/utils/ast-utils.ts(387,38): error TS2345: Argument of type 'ts.SourceFile' is not assignable to parameter of type 'ts.SourceFile'.`` 
* [x] [RxJS 6 breacking changes](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md) impact - example, in packages/nx/spec/data-persistence.spec.ts `import { Observable } from 'rxjs/Observable';
* [x] ng-packagr build error "no such file or directory", open '/home/osboxes/git/nx/packages/nx/.ng_pkg_build/nrwl-nx/out/src/data-persistence.ts'
`  - just have to wait for the next release (see this merged PR https://github.com/dherges/ng-packagr/pull/754)
* [x] ``@angular-devkit/schematics``  : breaking change on EngineHost (introduced by https://github.com/angular/devkit/commit/5b06cc7dd1f3a07e7c6f075383e91d0f1d3f8786 - probably released in 0.4.6)
* [x] ng-packagr update impacts (see https://github.com/dherges/ng-packagr/compare/v2.2.0...v2.4.2)

#### Angular Schematics

* [ ] lib : use [schematics/angular:library](https://github.com/angular/devkit/tree/master/packages/schematics/angular/library) instead
* [ ] app : use [schematics/angular:application](https://github.com/angular/devkit/tree/master/packages/schematics/angular/application) instead

#### Handle NgRx 6 impacts on ``@nrwl/nx``

* [ ] ... I didn't start to investigate this yet, but I'm sure @ThomasBurleson have some ideas :slightly_smiling_face:

#### Last things ...

* [ ] migration (update)
* [ ] set dependencies version numbers and test

### Phase 2 : Architects

* [ ] support the new angular-cli configuration file
* [ ] refactor the commands following https://github.com/angular/angular-cli/blob/d1b22d0e680f254b8395ad48ed1c8f29c9b4d46f/packages/%40angular/cli/models/architect-command.ts in order to be hable to use the architects
* [ ] run the right architect for each project, following the configuration file

**Comment by choucry13** [comment]
Thank you 👍

**Comment by noelmace** [comment]
@choucry13 you're welcome, but it's a slow process, given that this is, for me, more of a global thinking on how we could have a great build process for a multi-libraries angular monorepository, using angular-devkit/build-ng-packagr, schematics/build-ng-packagr, schematics/angular:library and nrwl/nx.

Given this, my main priorities are : 
1. "patch" nrwl/nx with packagr-for-nx, so without schematics nor architect, in order to simply validate the concepts (on a middle sized enterprise project)
2. see if the "build / publish all the libraries in my project at once" feature should be covered by angular-cli, angular-devkit/build-ng-packagr, or nrwl/nx only, and do the required PRs
3. integrate this in nrwl/nx

Any help would be welcome if you want this last part (ie this issue) to be done more quickly.

**Comment by noelmace** [comment]
For now, I froze my work on this since @vsavkin should post a more detailed migrate plan next week (see https://github.com/nrwl/nx/pull/419#issuecomment-382004783).

**Comment by choucry13** [comment]
@noelmace , i will this weekend

**Comment by noelmace** [comment]
Closing has Nrwl is working on this internally. See https://github.com/nrwl/nx/pull/419#issuecomment-387433968.

**Comment by noelmace** [comment]
I don't see any issue with that. You could also use the alpha version of nrwl/nx if you also want to move to Angular-cli 6. @vsavkin ?

**Comment by Springrbua** [comment]
@noelmace Thanks for your replay. So basicly the new release should only build on top of new CLI-features, but the current release should already be Angular-CLI v6 compatible?

**Comment by noelmace** [comment]
@Springrbua No. You asked about Angular, not Angular-CLI. Angular-cli 1.7 should be compatible with Angular 6 as far as I know, so I think NrwL/Nx v1.0.1 should be too. But current latest Nrwl/nx (v1.0.1) is not compatible with Angular-CLI v6. Only next is (v6.0.0-rc.1).

**Comment by Springrbua** [comment]
Thanks for your reply. In order to benefit from update schenatics to fully work, I probably need to wait for it to be CLI v6 compatible. Is a release of that version already near?
