### ISSUE TITLE
Module Federation still not working properly due to multiple  Can't resolve 'core-js/modules...' errors

### ISSUE THREAD

**Issue by jonesy212** [nrwl/nx#14681]
### Current Behavior

 The apps do initially do open and load up as if they are working.  You can click on them and change back and forth between the menu links in the left corner.  There is an issue with the remotes not loading properly for routing.  The remote creates an error where it is acting as if the port is already being used even though it isn't.  Libraries are not properly being imported and used. 

### Expected Behavior

After serving the host and remotes, when clicking on the bookstore, it should show the custom book app with a books list ui and links to navigate within the app.

### GitHub Repo

https://github.com/jonesy212/appository-review

### Steps to Reproduce

1. npx create-nx-workspace@latest
2. install pnpm
3. pnpm nx g @nrwl/react:host host --remotes dashboard,bookstore
4. install @nrwl/web
5. create libraries for books-ui: ui, feature,data-access using @nrwl/web, and a general ui
  a. pnpm nx g @nrwl/react:lib feature --directory books --tags type:feature,scope:books - no bundler
  b.  pnpm nx g @nrwl/react:lib ui --directory books --tags type:ui,scope:books
  c. pnpm nx g @nrwl/web:lib data-access --directory books --tags type:data-access,scope:books - no bundler
6.  Created component
  a. pnpm nx g component Books --project books-ui --export      
  b.  pnpm nx g component Book --project books-ui --export

### Nx Report

```shell
Node : 18.11.0
   OS   : darwin x64
   pnpm : 7.25.0
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.6.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.6.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.6.3
   @nrwl/webpack : 15.6.3
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
```

### Failure Logs

```shell
ERROR in ../../lib/books-data-access.ts 1:0-39
Module not found: Error: Can't resolve 'core-js/modules/es.promise.js' in '/../libs/books/data-access/src/lib'

ERROR in ../../libs/books/feature/src/lib/books-feature.tsx 2:0-46
Module not found: Error: Can't resolve 'core-js/modules/es.array.iterator.js' in '/../libs/books/feature/src/lib'

ERROR in ../../libs/books/feature/src/lib/books-feature.tsx 3:0-57
Module not found: Error: Can't resolve 'core-js/modules/web.dom-collections.iterator.js' in '/../../libs/books/feature/src/lib'

ERROR in ../../libs/ui/src/lib/button/button.tsx 4:0-45
Module not found: Error: Can't resolve 'core-js/modules/es.object.assign.js' in '/../libs/ui/src/lib/button'

webpack compiled with 4 errors (815c8d0edfc9f79a)
[ ready ] http://localhost:4202
assets by path *.js 1.3 MiB
  assets by chunk 1.19 MiB (id hint: vendors)
    asset vendors-node_modules_pnpm_react-dom_18_2_0_react_18_2_0_node_modules_react-dom_index_js.js 1020 KiB [emitted] [javascript module] [big] (id hint: vendors) 1 related asset
    asset vendors-node_modules_pnpm_react_18_2_0_node_modules_react_index_js.js 86.2 KiB [emitted] [javascript module] (id hint: vendors) 1 related asset
    asset vendors-node_modules_pnpm_styled-components_5_3_6_7i5myeigehqah43i5u7wbekgba_node_modules_sty-923ccb.js 70.8 KiB [emitted] [javascript module] (id hint: vendors) 1 related asset
    asset vendors-node_modules_pnpm_react_18_2_0_node_modules_react_jsx-dev-runtime_js.js 41 KiB [emitted] [javascript module] (id hint: vendors) 1 related asset
  asset src_app_app_tsx.js 53.1 KiB [emitted] [javascript module] 1 related asset
  asset remoteEntry.js 27.5 KiB [emitted] [javascript module] (name: dashboard) 1 related asset
  asset main.js 26.9 KiB [emitted] [javascript module] (name: main) 1 related asset
  asset src_bootstrap_tsx.js 2.42 KiB [emitted] [javascript module] 1 related asset
  asset src_remote-entry_ts.js 583 bytes [emitted] [javascript module]
asset favicon.ico 14.7 KiB [emitted] [from: src/favicon.ico] [copied]
asset assets/.gitkeep 0 bytes [emitted] [from: src/assets/.gitkeep] [copied]
runtime modules 38.6 KiB 30 modules
built modules 1.23 MiB (javascript) 126 bytes (share-init) 126 bytes (consume-shared) [built]
  cacheable modules 1.23 MiB
    modules by path ../../node_modules/.pnpm/ 1.18 MiB 20 modules
    modules by path ./src/ 46.4 KiB 5 modules
  provide-module modules 126 bytes
    provide shared module (default) react-dom@18.2.0 = ../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/index.js 42 bytes [built] [code generated]
    provide shared module (default) react@18.2.0 = ../../node_modules/.pnpm/react@18.2.0/node_modules/react/index.js 42 bytes [built] [code generated]
    provide shared module (default) styled-components@5.3.6 = ../../node_modules/.pnpm/styled-components@5.3.6_7i5myeigehqah43i5u7wbekgba/node_modules/styled-components/dist/styled-components.browser.cjs.js 42 bytes [built] [code generated]
  consume-shared-module modules 126 bytes
    consume shared module (default) react@=18.2.0 (strict) (singleton) (fallback: ../../node_modules/.pnpm/react@18.2.0/node_modules/react/index.js) 42 bytes [built] [code generated]
    consume shared module (default) react-dom@=18.2.0 (strict) (singleton) (fallback: ../../node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/index.js) 42 bytes [built] [code generated]
    consume shared module (default) styled-components@=5.3.6 (strict) (singleton) (fallback: ../../node_modules/.pnpm/styled-components@5.3.6_7i5myeigehqah43i5u7wbekgba/node_modules/styled-components/dist/styled-components.browser.cjs.js) 42 bytes [built] [code generated]
  container entry 42 bytes [built] [code generated]
webpack 5.75.0 compiled successfully in 23690 ms

 —————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for project dashboard



 >  NX   Running target build for project bookstore and 1 task it depends on:

 —————————————————————————————————————————————————————————————

> nx run books-feature:build

Bundling books-feature...
Error during bundle: Error: libs/books/feature/src/lib/books-feature.tsx:4:26 - error TS6059: File '/../libs/books/data-access/src/index.ts' is not under 'rootDir' '/../libs/books/feature'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via '@appindex/books/data-access' from file '/../libs/books/feature/src/lib/books-feature.tsx'
    Root file specified for compilation

4 import { getBooks } from '@appindex/books/data-access'
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libs/books/feature/src/lib/books-feature.tsx:5:23 - error TS6059: File '/../libs/books/ui/src/index.ts' is not under 'rootDir' '/../libs/books/feature'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via '@appindex/books/ui' from file '/../libs/books/feature/src/lib/books-feature.tsx'
    Root file specified for compilation

5 import { Books } from '@../books/ui'
                        ~~~~~~~~~~~~~~~~~~~~

Bundle failed: books-feature

 —————————————————————————————————————————————————————————————

 >  NX   Running target build for project bookstore and 1 task it depends on failed
```

### Additional Information

This set up works in an earlier version of nx 15.5.0

**Comment by rlesniak** [comment]
bump

**Comment by karthikeyan-arumugam-1558** [comment]
bump

**Comment by karthikeyan-arumugam-1558** [comment]
I don't need polyfilling, so removing the following from the lib's .babelrc fixed this issue for me
```
"useBuiltIns": "usage"
```

**Comment by rj-wowza** [comment]
https://github.com/nrwl/nx/issues/14681#issuecomment-1491888873

This solved my issue, specifically with using a spread operator on an object
