### ISSUE TITLE
ReferenceError: spyOn is not defined after migration to 12.4.0

### ISSUE THREAD

**Issue by dragonflypl** [nrwl/nx#6063]
## Current Behavior
After migration from 12.3.6 to 12.4.0 (jest is bumped to 27) I get `ReferenceError: spyOn is not defined` on every spyOn occurence in my tests

## Expected Behavior
After migration I would expect that test would work as before (compile & execute successfully). 

## Steps to Reproduce
Migrate from 12.3.6 to 12.4.0 

### Failure Logs

```
    ReferenceError: spyOn is not defined

      38 |
      39 |     const item = mockItems[1];
    > 40 |     spyOn(instance.selected, 'emit');
```

### Environment

It is happening when running test e.g. `nx affected:test`

**Comment by shumih** [comment]
This method and many other jasmine methods were removed in jest 27.
You should replace usage of spyOn with jest.spyOn (https://jestjs.io/docs/jest-object#jestspyonobject-methodname)

**Comment by dragonflypl** [comment]
Are you planning to add a migration for it in next versions?

**Comment by d3473r** [comment]
Any update on this issue?

I am getting the same error and some more after going from jest 26 to 27 with `nx migrate latest`
I am currently collecting all jest related errors (an missing migrations) below:

- ReferenceError: fail is not defined, related issue: https://github.com/facebook/jest/issues/11698
- Property 'and' does not exist on type 'SpyInstance' after changing from spyOn to jest.spyOn
- thrown: "Exceeded timeout of 5000 ms for a hook. Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

**Comment by gabeodessru** [comment]
> Property 'and' does not exist on type 'SpyInstance' after changing from spyOn to jest.spyOn

I'm having the same issue.

**Comment by russcarver** [comment]
Since I'm using Jasmine tests under Jest, I solved this by adding the following to `jest.config.js`:

```
  testRunner: 'jest-jasmine2',
```

See: https://jestjs.io/blog/2021/05/25/jest-27#flipping-defaults

**Comment by mmruesch12** [comment]
> > Property 'and' does not exist on type 'SpyInstance' after changing from spyOn to jest.spyOn
> 
> I'm having the same issue.

I'm having the same issue right now as well. Did anybody find a solution for this? I'm hoping I don't have to manually fix a large amount of tests.

**Comment by gabeodessru** [comment]
> I'm having the same issue right now as well. Did anybody find a solution for this? I'm hoping I don't have to manually fix a large amount of tests.

If you are trying to find a solution to `.and.return()` you could do a find and replace with `.mockResolvedValue()`

**Comment by mmruesch12** [comment]
> > I'm having the same issue right now as well. Did anybody find a solution for this? I'm hoping I don't have to manually fix a large amount of tests.
> 
> If you are trying to find a solution to `.and.return()` you could do a find and replace with `.mockResolvedValue()`

Probably won't be able to get away with a find and replace but that did work for me. Thanks!
