### ISSUE TITLE
Issue with ESLINT cannot find module '@swc/core-darwin-arm64'

### ISSUE THREAD

**Issue by 3JTek** [nrwl/nx#9545]
## Current Behavior

ESLINT fails to load due to missing module `@swc/core-darwin-arm64` (part of `nrwl/nx/angular` lib).

## Expected Behavior 

ESLINT to not fail.

NOTE: problem appeared when upgrading to version 13.8.3, downgrading back to 13.4.4 fixes the problem.

## Steps to Reproduce

- `npm cache clean --force && rm -rf node_modules && npm i`
- Restart ESLINT server

### Failure Logs

ESLINT logs: 

`(node:19717) UnhandledPromiseRejectionWarning: Error: Failed to load plugin '@nrwl/nx' declared in 'libs/gu-storage/.eslintrc.json » ../../.eslintrc.json#overrides[1]': Cannot find module '@swc/core-darwin-arm64'
Require stack:
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@swc/core/binding.js
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@swc/core/index.js
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@swc-node/core/lib/index.js
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@swc-node/register/lib/register.js
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@nrwl/eslint-plugin-nx/src/resolve-workspace-rules.js
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@nrwl/eslint-plugin-nx/src/index.js
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
Referenced from: /Users/jeremygiraudet/development/immutable/gu-cerberus/.eslintrc.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
`

### Environment

- MacBook Pro (16-inch, 2021), Apple M1 Max`
- npm: '6.14.15',
- node:  v14.18.2
- VSCode: 
`Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z (2 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.0.1`

### My first take on this issue

If I look at my node_modules, I can see the `core-darwin-x64` installed but not `core-darwin-arm64`.

Interestingly I've tried to manually install `@swc/core-darwin-arm64` but npm refused it due to my machine architecture:

`npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @swc/core-darwin-arm64@1.2.160: wanted {"os":"darwin","arch":"arm64"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  arm64
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64
`

If I type node -p "process.arch" I get `x64`.

Now when I look at my VSCode version, I can see it using an arm64 architecture:
`OS: Darwin arm64 21.0.1`

Could this be the root of the problem?

Thanks in advance for your help guys !!!

**Comment by GuskiS** [comment]
Most likely, you need to use newer node version for M1. For reference: https://isapplesiliconready.com/app/Node

**Comment by 3JTek** [comment]
Hey @GuskiS thanks for your help here.

I've installed node v16.14.2 and run `npm cache clean --force && rm -rf node_modules && npm i` but I still have the same error thrown by ESLINT after restarting the server:

`[Info  - 10:13:24 AM] ESLint server is starting
[Info  - 10:13:25 AM] ESLint server running in node v14.16.0
[Info  - 10:13:25 AM] ESLint server is running.
[Info  - 10:13:26 AM] ESLint library loaded from: /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/eslint/lib/api.js
(node:62665) UnhandledPromiseRejectionWarning: Error: Failed to load plugin '@nrwl/nx' declared in 'apps/desktop/.eslintrc.json » ../../.eslintrc.json#overrides[1]': Cannot find module '@swc/core-darwin-arm64'
Require stack:
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@swc/core/binding.js
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@swc/core/index.js
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@swc-node/core/lib/index.js
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@swc-node/register/lib/register.js
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@nrwl/eslint-plugin-nx/src/resolve-workspace-rules.js
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@nrwl/eslint-plugin-nx/src/index.js
- /Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
Referenced from: /Users/jeremygiraudet/development/immutable/gu-cerberus/.eslintrc.json
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:934:15)
    at Module._load (internal/modules/cjs/loader.js:779:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:1006:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/jeremygiraudet/development/immutable/gu-cerberus/node_modules/@swc/core/binding.js:129:41)
    at Module._compile (internal/modules/cjs/loader.js:1125:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1155:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Module._load (internal/modules/cjs/loader.js:823:14)
(Use `Electron --trace-warnings ...` to show where the warning was created)`

**Comment by GuskiS** [comment]
It seems you are still running node 14:
`[Info  - 10:13:25 AM] ESLint server running in node v14.16.0`

Node 14 works fine on M1, but is emulated or something like that.
Anyhow, you probably do want to be using node 16 for all the performance improvements that M1 provides.

**Comment by 3JTek** [comment]
@GuskiS This node version is actually the version that VS Code is using:

```
Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z (2 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.0.1
```

The version I've installed is `Now using node v16.14.2 (npm v8.5.0)`.

**Comment by 3JTek** [comment]
Fixed it.

I've updated VSCode to `OS: Darwin x64 21.0.1` and ESLINT is now working fine.

Thanks @GuskiS for your previous help.

**Comment by nevestuan** [comment]
@3JTek could you please share how to update VSCode to that OS version? I have the same issue with M1 Max but couldn't figure out how to fix that. Thanks.

**Comment by christian1koch** [comment]
> @3JTek could you please share how to update VSCode to that OS version? I have the same issue with M1 Max but couldn't figure out how to fix that. Thanks.

Go to the VSCode downloads and choose "Intel Chip", that should install the x64 VSCode

**Comment by Nitsan-Baleli-lmnd** [comment]
@christian1koch perf on the intel kind was sluggish, autocomplete/type-checking was really slow. installing the apple kind fixed that.

I fixed the op's issue with this vscode setting:
`"eslint.runtime": "/Users/nitsan.baleli/.nvm/versions/node/v16.13.2/bin/node",`
