### ISSUE TITLE
Nx Monorepo: `@upero/pipes` Fails to Resolve `@upero/store` Despite Correct Configuration (Minimal Repro Attached)

### ISSUE THREAD

**Issue by sycamoregroupltd** [nrwl/nx#30795]
# Nx Upstream Issue: `@upero/pipes` Fails to Resolve `@upero/store` in Monorepo

## Problem Description

In an Nx monorepo, the library `@upero/pipes` fails to resolve its dependency on `@upero/store` during build, despite all canonical configuration and remediation steps. This issue persists across environments and after all local fixes, blocking downstream builds and SSR.

## Impact

- **Builds for `@upero/pipes` are blocked** due to unresolved dependency on `@upero/store`.
- **SSR and downstream libraries** depending on `@upero/pipes` are also blocked.
- The error persists after all standard Nx/Angular monorepo fixes, affecting CI/CD and local development.

## Minimal Reproduction Steps

1. **Create two Nx libraries:** `@upero/store` and `@upero/pipes`.
2. **Export a symbol from `@upero/store`** and import it in `@upero/pipes`.
3. **Configure `@upero/pipes`** to depend on `@upero/store` in `project.json` and `ng-package.json`.
4. **Build `@upero/store`:**
   ```sh
   npx nx build store --skip-nx-cache
   ```
5. **Build `@upero/pipes`:**
   ```sh
   npx nx build pipes --skip-nx-cache
   ```
6. **Observe error:**
   ```
   Cannot find module '@upero/store' or its corresponding type declarations.
   ```
   See [`prompt/2.5-pipes-fix/pipes-build.log`](../prompt/2.5-pipes-fix/pipes-build.log) for full output.

## Findings & Investigation Summary

- All path mappings, configs, and dependency declarations are correct and aligned.
- No circular dependencies or build order issues detected.
- Both libraries build independently; `@upero/pipes` fails only when resolving `@upero/store`.
- All canonical Nx/Angular monorepo fixes (clean builds, cache reset, lockfile removal, dependency graph tweaks, upgrades) were attempted with no effect.
- The error persists across environments and after all local remediations.

**Most Likely Root Cause:**  
A bug in Nx's dependency/build system, where it does not recognize that `@upero/store` has been built, despite correct configuration and successful manual builds.

## Included Files

- **Investigation & Summaries**
  - [`docs/pipes-store-resolution-error-investigation.md`](pipes-store-resolution-error-investigation.md)
  - [`docs/cycle_6_summary.md`](cycle_6_summary.md)
  - [`docs/cycle_5_summary.md`](cycle_5_summary.md)
- **Nx & Library Configs**
  - [`nx.json`](../nx.json)
  - [`tsconfig.base.json`](../tsconfig.base.json)
  - [`libs/pipes/ng-package.json`](../libs/pipes/ng-package.json)
  - [`libs/pipes/project.json`](../libs/pipes/project.json)
  - [`libs/pipes/package.json`](../libs/pipes/package.json)
  - [`libs/store/ng-package.json`](../libs/store/ng-package.json)
  - [`libs/store/project.json`](../libs/store/project.json)
  - [`libs/store/package.json`](../libs/store/package.json)
- **Build Log**
  - [`prompt/2.5-pipes-fix/pipes-build.log`](../prompt/2.5-pipes-fix/pipes-build.log)

## Prior Context

- **Cycle 5 Summary:** See [`docs/cycle_5_summary.md`](cycle_5_summary.md)
- **Cycle 6 Summary:** See [`docs/cycle_6_summary.md`](cycle_6_summary.md)

## References

- All investigation, reproduction, and findings are documented in the included Markdown files.
- All relevant configuration and log files are attached for direct reproduction and analysis.

---

**For full details, see [`docs/nx-support-submission-summary.md`](nx-support-submission-summary.md).**

> If you need a zip or Gist of the minimal reproduction, configs, or logs, please let me know and I will provide them immediately.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Please update the issue description with working links (all links are broken) and provide more information like the output of `nx report`.
