### ISSUE TITLE
NextJs 10.0.8 Export Error

### ISSUE THREAD

**Issue by nickroberts** [nrwl/nx#4973]
## Current Behavior
When trying to export a NextJs app, an error is thrown saying `Cannot find module '<outputPath>/.next/serverless/pages-manifest.json'`.

## Expected Behavior
This should export a static generated site.

Everything was working with NextJs 10.0.7, but when I upgraded to 10.0.8, this started happening.

I tried updating to the latest Canary version of NextJs, 10.0.9-canary.2, and the same thing happens.

## Steps to Reproduce
1. Create a new NextJs workspace with a default app.
2. Upgrade NextJs to 10.0.8 (the latest stable as of this): `npm i next@latest`
3. Add a script in package.json, `"export": "nx export"` (Optional)
4. Try to export the app: `npm run export`

### Failure Logs
```
➜ npm run export

> nx-test-next-2@0.0.0 export <project-directory>
> nx export


> nx run app:export
info  - Using external babel configuration from <project-directory>/apps/app/.babelrc
info  - Creating an optimized production build
info  - Compiled successfully
info  - Collecting page data
info  - Generating static pages (3/3)
info  - Finalizing page optimization

Page                                                           Size     First Load JS
┌ ○ /                                                          1.23 kB        81.8 kB
├   /_app                                                      0 B            66.5 kB
└ ○ /404                                                       1.23 kB        81.8 kB
+ First Load JS shared by all                                  66.5 kB
  ├ chunks/f6078781a05fe1bcb0902d23dbbb2662c8d200b3.a6ce72.js  13.7 kB
  ├ chunks/framework.ca6c0d.js                                 41.8 kB
  ├ chunks/main.ef305f.js                                      6.34 kB
  ├ chunks/pages/_app.eb2392.js                                3.96 kB
  ├ chunks/webpack.50bee0.js                                   751 B
  └ css/f9743d5d25f6fddabd4d.css                               682 B

λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
   (ISR)     incremental static regeneration (uses revalidate in getStaticProps)

info  - using build directory: <project-directory>/dist/apps/app/.next
Cannot find module '<project-directory>/dist/apps/app/.next/serverless/pages-manifest.json'
Require stack:
- <project-directory>/node_modules/next/dist/export/index.js
- <project-directory>/node_modules/@nrwl/next/src/executors/export/export.impl.js
- <project-directory>/node_modules/@nrwl/tao/src/shared/workspace.js
- <project-directory>/node_modules/@nrwl/tao/src/commands/run.js
- <project-directory>/node_modules/@nrwl/tao/index.js
- <project-directory>/node_modules/@nrwl/cli/lib/run-cli.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nx-test-next-2@0.0.0 export: `nx export`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nx-test-next-2@0.0.0 export script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     <npm-log-directory>/2021-03-09T05_10_56_592Z-debug.log
```

### Environment
```
➜ nx report

>  NX  Report complete - copy this into the issue template

  Node : 14.15.5
  OS   : darwin x64
  npm  : 6.14.11

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.4.0
  @nrwl/cypress : 11.4.0
  @nrwl/devkit : 11.4.0
  @nrwl/eslint-plugin-nx : 11.4.0
  @nrwl/express : Not Found
  @nrwl/jest : 11.4.0
  @nrwl/linter : 11.4.0
  @nrwl/nest : Not Found
  @nrwl/next : 11.4.0
  @nrwl/node : Not Found
  @nrwl/react : 11.4.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.4.0
  @nrwl/web : 11.4.0
  @nrwl/workspace : 11.4.0
  typescript : 4.0.7
```

**Comment by underfisk** [comment]
Its also happening to me, i have indeed contacted Vercel because i though it was related to Nextjs but i think its the latest version (or one of them) of nrwl/next package, the issue also happens with env vars not being passed and the next.config being ignored

**Comment by nickroberts** [comment]
This still happens with 10.0.9, along with 10.0.10-canary.6.

**Comment by kirjai** [comment]
Hey @nickroberts , you will need to try with a new version of Nx, once it comes out - `11.6.0`

**Comment by cyrus-za** [comment]
Just in case anyone sees this before upgrading to 11.6.0 (or not able to) I ran into it myself but fixed it by adding --skip-nx-cache in my build
