### ISSUE TITLE
@nx/jest@22.7.x — getJestProjectsAsync throws "yargs is not a function" on every inferred jest run-commands target

### ISSUE THREAD

**Issue by MaksymPlotnikov** [nrwl/nx#35654]
## Current Behavior

Running `jest` from the workspace root (i.e. using the Nx-recommended root `jest.config.ts` that calls `getJestProjectsAsync`) throws on every inferred run-commands `test` target whose command contains the word "jest":

```
TypeError: yargs is not a function
    at collectJestConfigFromCommand (node_modules/@nx/jest/src/utils/config/get-jest-projects.js:101:24)
    at collectJestConfigFromRunCommandsExecutor (node_modules/@nx/jest/src/utils/config/get-jest-projects.js:72:9)
    at getJestProjectsAsync (node_modules/@nx/jest/src/utils/config/get-jest-projects.js:41:17)
```

In our workspace (98 projects with `@nx/jest/plugin` registered, all inferred with `{ command: "jest" }` shape and no `executor` field, defaulting to `nx:run-commands`), this fires on the very first call and aborts test discovery.

## Root cause

`packages/jest/src/utils/config/get-jest-projects.ts` does:

```ts
import * as yargs from 'yargs-parser';
// ...
const parsed = yargs(match, { ... });   // line 101
```

Compiled to JS by current tsconfig:

```js
const yargs = tslib_1.__importStar(require("yargs-parser"));
```

`yargs-parser` is a CJS module exporting a callable function with no `__esModule` marker. `tslib.__importStar` then wraps it in a **non-callable** namespace object (the callable function lives on `.default`). Calling `yargs(match, ...)` throws.

This was a regression introduced between `@nx/jest@22.5.4` and `@nx/jest@22.7.0`. Diff of the shipped file:

```diff
-const yargs = require("yargs-parser");   // 22.5.4 — works
+const yargs = tslib_1.__importStar(require("yargs-parser"));  // 22.7.x — broken
```

The TS source on `nrwl/nx` HEAD still has `import * as yargs from 'yargs-parser'`, so this is still broken on master.

## Expected Behavior

`getJestProjectsAsync` should discover all configured jest projects without throwing, regardless of whether per-project test targets use `@nx/jest:jest` or `nx:run-commands` executors.

## Trigger / amplification

`@nx/jest/plugin` in 22.7.x **infers** `test` targets with the shape:

```json
{
  "options": { "cwd": "<projectRoot>", "command": "jest" },
  "metadata": { "technologies": ["jest"] }
}
```

No `executor` field → defaults to `nx:run-commands` → falls into the `collectJestConfigFromRunCommandsExecutor` branch in `getJestProjectsAsync` → calls `collectJestConfigFromCommand` → triggers the failing `yargs(...)` call. So every workspace that uses `@nx/jest/plugin` will fail `npm test` on the root config.

## Steps to Reproduce

1. Generate a new Nx 22.7.1 workspace with at least one Angular or TS app.
2. Ensure `@nx/jest/plugin` is registered in `nx.json` (default).
3. Use the standard root `jest.config.ts`:
   ```ts
   const { getJestProjectsAsync } = require('@nx/jest');
   module.exports = async () => ({ projects: await getJestProjectsAsync() });
   ```
4. Run `jest --maxWorkers=2` from the workspace root.
5. Observe `TypeError: yargs is not a function`.

## Proposed Fix

Either revert to a plain `require` (as in 22.5.4):

```ts
const yargs = require('yargs-parser');
```

Or use `__importDefault` (or `yargs.default(match, ...)` at the call site).

Verified locally with a one-line `patch-package` patch — tests then discover and run cleanly across all 98 projects.

## Nx Report

```shell
Node           : 24.14.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 11.9.0
daemon         : Disabled

nx                     : 22.7.1
@nx/js                 : 22.7.1
@nx/eslint             : 22.7.1
@nx/workspace          : 22.7.1
@nx/angular            : 22.7.1
@nx/jest               : 22.7.1
@nx/cypress            : 22.7.1
@nx/devkit             : 22.7.1
@nx/esbuild            : 22.7.1
@nx/eslint-plugin      : 22.7.1
@nx/module-federation  : 22.7.1
@nx/rspack             : 22.7.1
@nx/storybook          : 22.7.1
@nx/web                : 22.7.1
@nx/webpack            : 22.7.1
typescript             : 5.9.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/jest/plugin
@nx/storybook/plugin
---------------------------------------
Community plugins:
```

**Comment by MaksymPlotnikov** [comment]
Thanks for the fix in #35672! Could this be backported to the 22.7.x line?
@nx/jest@22.7.2 (currently tagged `latest`) was published after the merge but still ships the broken `tslib_1.__importStar(require("yargs-parser"))`, so workspaces pinned to Nx 22 still need a patch-package workaround until Nx 23 goes stable.
