### PR TITLE
fix(devkit): split-create-tree should use nx cli

### LINKED ISSUE #11710: Upgrading to 14.5.10 fails to run migration split-create-tree
## Current Behavior

When upgrading to 14.5.10 migration fails on split-create-record migration

## Expected Behavior

Upgrading should work

## Steps to Reproduce
Not sure this is easily reproducable

### Failure Logs

 >  NX   Running migrations from 'migrations.json'

 >  NX   Failed to run split-create-tree from @nrwl/devkit. This workspace is NOT up to date!

 >  NX   rule is not a function

TypeError: rule is not a function
    at MergeMapSubscriber.project (/Users/justinhandley/IdeaProjects/pirateandfox/node_modules/@angular-devkit/schematics/src/rules/call.js:75:24)
    at MergeMapSubscriber._tryNext (/Users/justinhandley/IdeaProjects/pirateandfox/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/Users/justinhandley/IdeaProjects/pirateandfox/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/Users/justinhandley/IdeaProjects/pirateandfox/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/Users/justinhandley/IdeaProjects/pirateandfox/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/util/subscribeToArray.js:5:20)
    at Observable._trySubscribe (/Users/justinhandley/IdeaProjects/pirateandfox/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/justinhandley/IdeaProjects/pirateandfox/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:30:22)
    at MergeMapOperator.call (/Users/justinhandley/IdeaProjects/pirateandfox/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/mergeMap.js:37:23)
    at Observable.subscribe (/Users/justinhandley/IdeaProjects/pirateandfox/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/Observable.js:25:31)
    at MapOperator.call (/Users/justinhandley/IdeaProjects/pirateandfox/node_modules/@angular-devkit/schematics/node_modules/rxjs/internal/operators/map.js:32:23)
Command failed: /var/folders/39/yzpmnnjn5wbbv8j4jd38ryw80000gn/T/tmp-87999-7bswWl12B2oB/node_modules/.bin/nx _migrate --run-migrations --verbose

### Environment

Report complete - copy this into the issue template

   Node : 16.15.1
   OS   : darwin arm64
   yarn : 1.22.18
   
   nx : 14.5.10
   @nrwl/angular : 11.6.3
   @nrwl/cypress : 14.5.10
   @nrwl/detox : 14.5.10
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : 14.5.10
   @nrwl/next : Not Found
   @nrwl/node : 14.5.10
   @nrwl/nx-cloud : 14.5.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.5.10
   @nrwl/react-native : 14.5.10
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.8
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @nxpm/stack: 4.21.0

### PR DESCRIPTION
**Pull request by AgentEnder**
fixes: #11710

## Related Issue(s)

Fixes #

### CODE REVIEW

**Comment by gerardcastell** [comment]
Is this fix being included within the next release of @nrwl/cli ?
