### ISSUE TITLE
NX upgrade from 13.2.4 to 13.3.0 broke building libs

### ISSUE THREAD

**Issue by kylecannon** [nrwl/nx#8085]
## Current Behavior
After upgrading to 13.3.0 from 13.2.4, I am unable to build or serve projects

## Expected Behavior
would be able to build and serve.

## Steps to Reproduce

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs
```
yarn run v1.22.17
$ nx build cdk
/Volumes/Development/redacted/projects/redacted/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^



TypeError: tasksRunner is not a function
    at /Volumes/Development/redacted/projects/redacted/node_modules/@nrwl/workspace/src/tasks-runner/run-command/index.js:65:37
    at Generator.next (<anonymous>)
    at /Volumes/Development/redacted/projects/redacted/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/Volumes/Development/redacted/projects/redacted/node_modules/tslib/tslib.js:113:16)
    at runCommand (/Volumes/Development/redacted/projects/redacted/node_modules/@nrwl/workspace/src/tasks-runner/run-command/index.js:37:34)
    at Object.<anonymous> (/Volumes/Development/redacted/projects/redacted/node_modules/@nrwl/workspace/src/command-line/run-one.js:20:38)
    at Generator.next (<anonymous>)
    at fulfilled (/Volumes/Development/redacted/projects/redacted/node_modules/tslib/tslib.js:114:62)
```

### Environment
```
yarn nx report
yarn run v1.22.17
$ nx report

>  NX  Report complete - copy this into the issue template

  Node : 16.13.1
  OS   : darwin x64
  yarn : 1.22.17

  nx : 13.3.0
  @nrwl/angular : 13.3.0
  @nrwl/cli : 13.3.0
  @nrwl/cypress : 13.3.0
  @nrwl/devkit : 13.3.0
  @nrwl/eslint-plugin-nx : 13.3.0
  @nrwl/express : undefined
  @nrwl/jest : 13.3.0
  @nrwl/linter : 13.3.0
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : 13.3.0
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.0
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.0
  @nrwl/storybook : 13.3.0
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
  	 @angular/animations: 13.0.3
  	 @angular/cdk: 13.0.3
  	 @angular/common: 13.0.3
  	 @angular/compiler: 13.0.3
  	 @angular/core: 13.0.3
  	 @angular/forms: 13.0.3
  	 @angular/localize: 13.0.3
  	 @angular/material: 13.0.3
  	 @angular/platform-browser: 13.0.3
  	 @angular/platform-browser-dynamic: 13.0.3
  	 @angular/router: 13.0.3
  	 @angular/service-worker: 13.0.3
  	 @ngrx/component: 13.0.2
  	 @ngrx/component-store: 13.0.2
  	 @ngrx/effects: 13.0.2
  	 @ngrx/entity: 13.0.2
  	 @ngrx/router-store: 13.0.2
  	 @ngrx/store: 13.0.2
  	 @angular-devkit/build-angular: 13.0.4
  	 @angular/cli: 13.0.4
  	 @angular/compiler-cli: 13.0.3
  	 @angular/language-service: 13.0.3
  	 @ng-bootstrap/ng-bootstrap: 10.0.0
  	 @ngrx/schematics: 13.0.2
  	 @ngrx/store-devtools: 13.0.2
  	 @nrwl/nx-plugin: 13.3.0
  	 ng-mocks: 12.5.0
```

**Comment by kylecannon** [comment]
seems to be related to https://github.com/nrwl/nx/pull/8028

**Comment by kylecannon** [comment]
I also want to add that I can not reproduce this from a clean install of 13.2.4 and migrating to 13.3.0. This issue only seems to be happening on our project. I'll continue to look into it.

**Comment by AgentEnder** [comment]
The PR looks good to me, e2e failures are unrelated. @FrozenPandaz do you want to merge this or wait for e2e fixes in storybook and merge later
