### ISSUE TITLE
dataPersistence run throws compilation errors

### ISSUE THREAD

**Issue by pavelekNET** [nrwl/nx#2397]
## Expected Behavior
work as in 8.11.1

## Current Behavior
after updating to 8.12.0

in my effect i have:
> 	zajistitNactenyCiselnik$ = createEffect(() =>
		this.dataPersistence.fetch(zajistitNactenyCiselnik, {
			run: (action: ReturnType<typeof zajistitNactenyCiselnik>, state: any) => {
				const ciselnik = ciselnikySelectors.getCiselnik(action.typCiselniku)(state);
				if (ciselnik && (ciselnik.nacitaniProbiha || ciselnik.nacitaniDokonceno)) {
					return EMPTY;
				}
				return nacistCiselnik({ typCiselniku: action.typCiselniku });
			},
			onError: (_action: ReturnType<typeof zajistitNactenyCiselnik>, _error) => {
				return chybaAplikace()
			},
		})
	);

throws typescript error:

`Error:(15, 4) TS2322: Type '(action: { typCiselniku: TypCiselniku; } & TypedAction<string>, state: any) => Observable<never> | ({ typCiselniku: TypCiselniku; } & TypedAction<string>)' is not assignable to type '(a: { typCiselniku: TypCiselniku; } & TypedAction<string>, state?: any) => void | Action | Observable<Action>'.
  Type 'Observable<never> | ({ typCiselniku: TypCiselniku; } & TypedAction<string>)' is not assignable to type 'void | Action | Observable<Action>'.
    Type 'Observable<never>' is not assignable to type 'void | Action | Observable<Action>'.
      Type 'Observable<never>' is not assignable to type 'Observable<Action>'.
        Types of property 'source' are incompatible.
          Type 'import("C:/Users/pavel/Source/Repos/eleg/fe/node_modules/rxjs/internal/Observable").Observable<any>' is not assignable to type 'import("C:/Users/pavel/Source/Repos/eleg/fe/node_modules/@nrwl/angular/node_modules/rxjs/internal/Observable").Observable<any>'.
            Types of property 'operator' are incompatible.
              Type 'import("C:/Users/pavel/Source/Repos/eleg/fe/node_modules/rxjs/internal/Operator").Operator<any, any>' is not assignable to type 'import("C:/Users/pavel/Source/Repos/eleg/fe/node_modules/@nrwl/angular/node_modules/rxjs/internal/Operator").Operator<any, any>'.
                Types of property 'call' are incompatible.
                  Type '(subscriber: import("C:/Users/pavel/Source/Repos/eleg/fe/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("C:/Users/pavel/Source/Repos/eleg/fe/node_modules/rxjs/internal/types").TeardownLogic' is not assignable to type '(subscriber: import("C:/Users/pavel/Source/Repos/eleg/fe/node_modules/@nrwl/angular/node_modules/rxjs/internal/Subscriber").Subscriber<any>, source: any) => import("C:/Users/pavel/Source/Repos/eleg/fe/node_modules/@nrwl/angular/node_modules/rxjs/internal/types").TeardownLogic'.
                    Types of parameters 'subscriber' and 'subscriber' are incompatible.
                      Property '_parentOrParents' is missing in type 'Subscriber<any>' but required in type 'Subscriber<any>'.`

**Comment by jessejohnsohn** [comment]
I just opened up a similar issue, but it could be the same thing: [2405](https://github.com/nrwl/nx/issues/2405)

**Comment by vsavkin** [comment]
It looks like you have multiple copes of RxJS in `node_modules`, which results in this error.

What are the versions of:
* `C:/Users/pavel/Source/Repos/eleg/fe/node_modules/rxjs`
* `C:/Users/pavel/Source/Repos/eleg/fe/node_modules/@nrwl/angular/node_modules/rxjs`

You can look at your root `package.json`. Maybe you need to update the version of RxJS there. 

If nothing helps, you can force npm to have a single version of the package (in 99% cases it doesn't matter which one you pick):

1. If you are using `yarn`, use the yarn resolutions feature.
2. If you are using `npm`, use this package.`https://github.com/rogeriochaves/npm-force-resolutions`

**Comment by brandonroberts** [comment]
Closing as resolved
