### ISSUE TITLE
Incorrect types for publishable lib while importing other buildable libs

### ISSUE THREAD

**Issue by struggling-dev** [nrwl/nx#16189]
### Current Behavior

Let's assume I have two libs
- `lib-a`: buildable
- `lib-b`: buildable and publishable

and `lib-b` imports some components/types from `lib-a`. The bundled js file for `lib-b` correctly includes the imported stuff from `lib-a` as you can see below

<img width="1114" alt="bundled-js" src="https://user-images.githubusercontent.com/130234999/230730934-2217c19d-e3dd-40f9-b35f-a08c36cfda54.png">

However, the generated `d.ts` file for `lib-b` relies on the existence of `@my-scope/lib-a` which it won't be when I publish `lib-b`.
```
Cannot find module '@my-scope/lib-a' or its corresponding type declarations.
```
<img width="1195" alt="dts-import-error" src="https://user-images.githubusercontent.com/130234999/230730989-b0d4237c-87bf-4b14-a2b6-cfc06348c768.png">

Also while building `lib-b`, `vite-plugin-dts` throws these errors:
```
File '/Developer/nx-publishable-lib/libs/lib-a/src/lib/lib-a.tsx' is not under 'rootDir' '/Developer/nx-publishable-lib/libs/lib-b'. 'rootDir' is expected to contain all source files.
```
![dts-generate-error](https://user-images.githubusercontent.com/130234999/230731023-a82feac6-e850-4342-9468-65fc922ddb5b.png)

### Expected Behavior

I expect the `.d.ts` files from `lib-a` will be included in `lib-b` bundle.

### GitHub Repo

https://github.com/struggling-dev/nx-publishable-lib

### Steps to Reproduce

1. Run `nx build lib-b`. Please notice the errors in the console
2. The generate `dist/libs/lib-b/lib/lib-b.d.ts` relies on the existence of `@my-scope/lib-a`

### Nx Report

```shell
Node : 16.14.2
   OS   : darwin arm64
   npm  : 8.5.0
   
   nx (global)             : 15.9.2
   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/cypress           : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/react             : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/vite              : 15.9.2
   typescript              : 4.9.5
```

### Failure Logs

```shell
Cannot find module '@my-scope/lib-a' or its corresponding type declarations.

File '/Developer/nx-publishable-lib/libs/lib-a/src/lib/lib-a.tsx' is not under 'rootDir' '/Developer/nx-publishable-lib/libs/lib-b'. 'rootDir' is expected to contain all source files.
```

**Comment by binarybro** [comment]
After updating our Nx workspace to 15.9.2 I am facing similar issues. Did you ever get to resolve this?

**Comment by struggling-dev** [comment]
I ended up writing my own `dts` plugin using [`dts-bundle-generator`](https://github.com/timocov/dts-bundle-generator)

```ts
import { join } from 'path';
import { writeFile } from 'fs';
import { generateDtsBundle } from 'dts-bundle-generator';

function dts(): Plugin {
  return {
    name: 'dts',
    apply: 'build',
    writeBundle: () =>
      new Promise((res, rej) => {
        writeFile(
          'dist/libs/lib-b/index.d.ts',
          generateDtsBundle(
            [
              {
                filePath: join(__dirname, 'src/index.ts'),
                libraries: {
                  importedLibraries: ['react', 'react-dom'],
                },
              },
            ],
            { preferredConfigPath: join(__dirname, 'tsconfig.lib.json') }
          )[0],
          (err) => (err ? rej(err) : res())
        );
      }),
  };
}
```
