### ISSUE TITLE
Cant run migration when updating from 15.9.4 -> 16.3.2 with error Cannot find module '@angular-devkit/schematics/tools'

### ISSUE THREAD

**Issue by JWood48** [nrwl/nx#17516]
### Current Behavior

Trying to run yarn exec nx migrate --run-migrations results in error with the following message:

`Failed to run migration-v16-remove-module-id from @angular/core. This workspace is NOT up to date!`

`Cannot find module '@angular-devkit/schematics/tools'`

### Expected Behavior

Migrations should run without error

### Steps to Reproduce

1.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : win32 x64
   yarn   : 3.4.1
   Hasher : Native

   nx                 : 16.3.2
   @nx/js             : 16.3.2
   @nx/jest           : 16.3.2
   @nx/linter         : 16.3.2
   @nx/workspace      : 16.3.2
   @nx/angular        : 16.3.2
   @nx/cypress        : 16.3.2
   @nx/devkit         : 16.3.2
   @nx/eslint-plugin  : 16.3.2
   @nx/plugin         : 16.3.2
   @nx/react          : 16.3.2
   @nrwl/tao          : 16.3.2
   @nx/web            : 16.3.2
   @nx/webpack        : 16.3.2
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @fortawesome/angular-fontawesome : 0.11.1
   @ng-bootstrap/ng-bootstrap       : 14.1.1
   ng2-charts                       : 4.1.1
   ngx-bootstrap                    : 10.3.0
   ngx-spinner                      : 15.0.1
   ---------------------------------------
   Local workspace plugins:
         @robex/nx-tools-rbx-nx
```

### Failure Logs

```shell
>  NX   Running migrations from 'migrations.json'


 >  NX   Failed to run migration-v16-remove-module-id from @angular/core. This workspace is NOT up to date!


 >  NX   Cannot find module '@angular-devkit/schematics/tools'

   Require stack:
   - <redacted-app-folder>\node_modules\nx\src\adapter\ngcli-adapter.js
   - <redacted-app-folder>\node_modules\nx\src\command-line\migrate\migrate.js
   - <redacted-app-folder>\node_modules\nx\src\command-line\migrate\command-object.js
   - <redacted-app-folder>\node_modules\nx\src\command-line\nx-commands.js
   - <redacted-app-folder>\node_modules\nx\bin\init-local.js
   - <redacted-app-folder>\node_modules\nx\bin\nx.js

Error: Cannot find module '@angular-devkit/schematics/tools'
Require stack:
- <redacted-app-folder>\node_modules\nx\src\adapter\ngcli-adapter.js
- <redacted-app-folder>\node_modules\nx\src\command-line\migrate\migrate.js
- <redacted-app-folder>\node_modules\nx\src\command-line\migrate\command-object.js
- <redacted-app-folder>\node_modules\nx\src\command-line\nx-commands.js
- <redacted-app-folder>\node_modules\nx\bin\init-local.js
- <redacted-app-folder>\node_modules\nx\bin\nx.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at Module.require (<redacted-app-folder>\node_modules\nx\src\adapter\compat.js:35:40)
    at require (node:internal/modules/cjs/helpers:110:18)
    at createWorkflow (<redacted-app-folder>\node_modules\nx\src\adapter\ngcli-adapter.js:119:26)
    at Object.<anonymous> (<redacted-app-folder>\node_modules\nx\src\adapter\ngcli-adapter.js:487:26)
    at Generator.next (<anonymous>)
    at <redacted-app-folder>\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
Command failed: yarn exec nx _migrate --run-migrations --verbose

 >  NX   Command failed: yarn exec nx migrate --run-migrations --verbose


Error: Command failed: yarn exec nx migrate --run-migrations --verbose
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at runNxSync (<redacted-user-folder>\AppData\Local\Temp\tmp-35240-1PttG2SAmdAa\node_modules\nx\src\utils\child-process.js:26:34)
    at <redacted-user-folder>\AppData\Local\Temp\tmp-35240-1PttG2SAmdAa\node_modules\nx\src\command-line\migrate\migrate.js:972:43
    at Generator.next (<anonymous>)
    at <redacted-user-folder>\AppData\Local\Temp\tmp-35240-1PttG2SAmdAa\node_modules\tslib\tslib.js:167:75
    at new Promise (<anonymous>)
    at Object.__awaiter (<redacted-user-folder>\AppData\Local\Temp\tmp-35240-1PttG2SAmdAa\node_modules\tslib\tslib.js:163:16)
    at runMigrations (<redacted-user-folder>\AppData\Local\Temp\tmp-35240-1PttG2SAmdAa\node_modules\nx\src\command-line\migrate\migrate.js:965:20)
Command failed: <redacted-user-folder>\AppData\Local\Temp\tmp-35240-1PttG2SAmdAa\node_modules\.bin\nx _migrate --run-migrations --verbose
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Could you confirm you have the `@angular-devkit/schematics` package installed? Our app and lib generators install that package if it's not installed, so you should have it in your workspace. Otherwise, something outside Nx must have removed it, or things were generated differently.

**Comment by JWood48** [comment]
It is not part of my current **dependencies** or **devDependencies** - however in the **yarn.lock** file it is part of **peerDependencies** for **@nrwl/angular@npm:15.9.4** - should I add it as a devDependency?

**Comment by leosvelperez** [comment]
Yeah, that's the issue. Please add it to your `devDependencies` and run the migrations again.

As mentioned in the previous comment, our project generators (`@nx/angular:application` and `@nx/angular:library`) and `nx init` (if coming from an Angular CLI repo) add that package to the `package.json` to ensure the peer dependency is met.

I'm closing this since the issue is due to a missing dependency that Nx generators add to the workspace and the Angular plugin specifies it as a non-optional peer dependency.
