### ISSUE TITLE
compiler.__internal__registerBuiltinPlugin is not a function

### ISSUE THREAD

**Issue by rendmath** [nrwl/nx#33127]
### Current Behavior

After generating a Webpack Module federation host with 2 remotes and going through the workarounds detailed in #31029 (deleting the paths and adding the remote declarations), the issue mentioned in #32542 still happens.

The workaround mentioned in #32542 till seems to work (installing @rspack/core@1.3.8), but this contradicts the idea that it was fixed by #32509.

### Expected Behavior

Using the latest Nx CLI to generate Webpack host and remotes and building them works out-of-the-box.

### Steps to Reproduce

```
npx create-nx-workspace@21 mf-workspace   --name=mf-workspace   --nxCloud=skip   --interactive=false
cd mf-workspace/
npx nx g @nx/react:host apps/host   --bundler=webpack --style=css --unitTestRunner=none --e2eTestRunner=none   --remotes=remote1,remote2
```

Apply fixes from #31029.

```
nx build host
```

### Nx Report

```shell
Node           : 22.15.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 11.3.0

nx                     : 21.6.5
@nx/js                 : 21.6.5
@nx/eslint             : 21.6.5
@nx/workspace          : 21.6.5
@nx/devkit             : 21.6.5
@nx/eslint-plugin      : 21.6.5
@nx/module-federation  : 21.6.5
@nx/react              : 21.6.5
@nx/rollup             : 21.6.5
@nx/vite               : 21.6.5
@nx/web                : 21.6.5
@nx/webpack            : 21.6.5
typescript             : 5.9.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/eslint/plugin
@nx/vite/plugin
---------------------------------------
Cache Usage: 48.00 B / 46.49 GB
```

### Failure Logs

```shell
NX   compiler.__internal__registerBuiltinPlugin is not a function
TypeError: compiler.__internal__registerBuiltinPlugin is not a function
    at Plugin.apply (C:\Users\Admin\Desktop\webpack-mf\mf-workspace\node_modules\@rspack\core\dist\index.js:235:105)     
    at createCompiler (C:\Users\Admin\Desktop\webpack-mf\mf-workspace\node_modules\webpack\lib\webpack.js:86:12)
    at create (C:\Users\Admin\Desktop\webpack-mf\mf-workspace\node_modules\webpack\lib\webpack.js:171:16)
    at webpack (C:\Users\Admin\Desktop\webpack-mf\mf-workspace\node_modules\webpack\lib\webpack.js:199:32)
    at f (C:\Users\Admin\Desktop\webpack-mf\mf-workspace\node_modules\webpack\lib\index.js:99:21)
    at Observable._subscribe (C:\Users\Admin\Desktop\webpack-mf\mf-workspace\node_modules\@nx\webpack\src\executors\webpack\lib\run-webpack.js:12:33)
    at Observable._trySubscribe (C:\Users\Admin\Desktop\webpack-mf\mf-workspace\node_modules\rxjs\src\internal\Observable.ts:235:19)
    at C:\Users\Admin\Desktop\webpack-mf\mf-workspace\node_modules\rxjs\src\internal\Observable.ts:225:18
    at Object.errorContext (C:\Users\Admin\Desktop\webpack-mf\mf-workspace\node_modules\rxjs\src\internal\util\errorContext.ts:29:5)
    at Observable.subscribe (C:\Users\Admin\Desktop\webpack-mf\mf-workspace\node_modules\rxjs\src\internal\Observable.ts:211:5)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by Petdro** [comment]
I also encountered this issue when upgrading nx/angular from 21.3.11 --> 21.6.10

**Comment by Coly010** [comment]
I cannot reproduce this and similar issues were solved recently with a bump to rspack version/ I'm going to close this issue for now. If it is encountered again please provide a repo that I can reproduce it in
