### ISSUE TITLE
"Error: Cannot find module '@nrwl/workspace/presets/npm.json'" after upgrading to Nx 20

### ISSUE THREAD

**Issue by joshkel** [nrwl/nx#28342]
### Current Behavior

After upgrading from Nx 19.8.4 to 20, any `nx` commands started failing with errors similar to the following:

```
node:internal/modules/cjs/loader:1143
  throw err;
  ^
Error: Cannot find module '@nrwl/workspace/presets/npm.json'
Require stack:
- /builds/foo/bar/node_modules/nx/src/config/nx-json.js
- /builds/foo/bar/node_modules/nx/src/daemon/client/client.js
- /builds/foo/bar/node_modules/nx/src/utils/handle-errors.js
- /builds/foo/bar/node_modules/nx/src/command-line/activate-powerpack/command-object.js
- /builds/foo/bar/node_modules/nx/src/command-line/nx-commands.js
- /builds/foo/bar/node_modules/nx/bin/init-local.js
- /builds/foo/bar/node_modules/nx/bin/nx.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1[140](https://gitlab.com/foo/bar/-/jobs/8012177822#L140):15)
    at Function.resolve (node:internal/modules/helpers:188:19)
    at readNxJson (/builds/foo/bar/node_modules/nx/src/config/nx-json.js:14:48)
    at Object.<anonymous> (/builds/foo/bar/node_modules/nx/src/command-line/init/command-object.js:7:30)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:[142](https://gitlab.com/foo/bar/-/jobs/8012177822#L142)2:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/builds/foo/bar/node_modules/nx/src/config/nx-json.js',
    '/builds/foo/bar/node_modules/nx/src/daemon/client/client.js',
    '/builds/foo/bar/node_modules/nx/src/utils/handle-errors.js',
    '/builds/foo/bar/node_modules/nx/src/command-line/activate-powerpack/command-object.js',
    '/builds/foo/bar/node_modules/nx/src/command-line/nx-commands.js',
    '/builds/foo/bar/node_modules/nx/bin/init-local.js',
    '/builds/foo/bar/node_modules/nx/bin/nx.js'
  ]
}
```

### Expected Behavior

Successful execution.

### Steps to Reproduce

1. Take an Nx project with `"extends": "@nrwl/workspace/presets/npm.json"` in its `nx.json`.
2. Upgrade to Nx 20.

### Nx Report

Node           : 18.20.2
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 4.5.0

nx             : 20.0.0
@nx/workspace  : 20.0.0
@nx/devkit     : 20.0.0
typescript     : 5.6.2

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

This appears to be the result of an undocumented breaking change: `"extends": "@nrwl/workspace/presets/npm.json"` should now be `"extends": "nx/presets/npm.json"`.
