### ISSUE TITLE
Cypress Component Testing: "Module parse failed: parser.destructuringAssignmentPropertiesFor is not a function"

### ISSUE THREAD

**Issue by Nick-Lucas** [nrwl/nx#16803]
### Current Behavior

After upgrading from 15.x to 16.1.0 component testing does not run

### Expected Behavior

Component testing works as before

### Steps to Reproduce

Upgrade an existing project with component testing, and according to the error have a file like this:

`./src/environments/index.ts`: 
```ts
export * from './environment'
export * from './environment.types'
export const isE2E = process.env['NX_E2E'] && process.env['NX_E2E'].length > 0
```

### Nx Report

```shell
Node   : 18.14.2
   OS     : linux x64
   pnpm   : 8.4.0
   Hasher : Native
   
   nx                 : 16.1.0
   @nx/js             : 16.1.0
   @nx/jest           : 16.1.0
   @nx/linter         : 16.1.0
   @nx/workspace      : 16.1.0
   @nx/cypress        : 16.1.0
   @nx/devkit         : 16.1.0
   @nx/eslint-plugin  : 16.1.0
   @nx/nest           : 16.1.0
   @nx/node           : 16.1.0
   @nx/plugin         : 16.1.0
   @nx/react          : 16.1.0
   @nrwl/tao          : 16.1.0
   @nx/web            : 16.1.0
   @nx/webpack        : 16.1.0
   typescript         : 5.0.4
```

### Failure Logs

```shell
ERROR in ./src/environments/index.ts
Module parse failed: parser.destructuringAssignmentPropertiesFor is not a function
File was processed with these loaders:
 * ../../../node_modules/.pnpm/@nx+webpack@16.1.0_@types+node@18.7.18_esbuild@0.17.11_html-webpack-plugin@5.5.0_nx@16.1.0_typescript@5.0.4/node_modules/@nx/webpack/src/utils/web-babel-loader.js
You may need an additional loader to handle the result of these loaders.
TypeError: parser.destructuringAssignmentPropertiesFor is not a function
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.82.0_esbuild@0.17.11/node_modules/webpack/lib/DefinePlugin.js:575:16
    at Hook.eval (eval at create (/home/nick/dev/application-monorepo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at JavascriptParser.callHooksForInfoWithFallback (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:3022:24)
    at JavascriptParser.callHooksForInfo (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2971:15)
    at JavascriptParser.walkMemberExpressionWithExpressionName (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2866:24)
    at JavascriptParser.walkMemberExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2816:11)
    at JavascriptParser.walkExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2305:10)
    at JavascriptParser.walkLeftRightExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2483:8)
    at JavascriptParser.walkLogicalExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2496:9)
    at JavascriptParser.walkExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2299:10)
    at JavascriptParser.walkVariableDeclaration (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2126:33)
    at JavascriptParser.walkStatement (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:1620:10)
    at JavascriptParser.walkExportNamedDeclaration (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2007:9)
    at JavascriptParser.walkStatement (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:1584:10)
    at JavascriptParser.walkStatements (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:1481:9)
    at JavascriptParser.parse (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:3375:9)
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/NormalModule.js:1087:26
    at processResult (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/NormalModule.js:800:11)
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/NormalModule.js:860:5
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:407:3
    at iterateNormalLoaders (/home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:233:10)
    at iterateNormalLoaders (/home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:240:10)
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:255:3
    at context.callback (/home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/babel-loader@9.1.2_@babel+core@7.21.0_webpack@5.82.0/node_modules/babel-loader/lib/index.js:41:71
ERROR in ../../../node_modules/.pnpm/cypress@12.11.0/node_modules/cypress/react18/dist/cypress-react.esm-bundler.js
Module parse failed: parser.destructuringAssignmentPropertiesFor is not a function
File was processed with these loaders:
 * ../../../node_modules/.pnpm/source-map-loader@3.0.2_webpack@5.82.0/node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
TypeError: parser.destructuringAssignmentPropertiesFor is not a function
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.82.0_esbuild@0.17.11/node_modules/webpack/lib/DefinePlugin.js:575:16
    at Hook.eval (eval at create (/home/nick/dev/application-monorepo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at Hook.CALL_DELEGATE [as _call] (/home/nick/dev/application-monorepo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/Hook.js:14:14)
    at JavascriptParser.callHooksForInfoWithFallback (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:3022:24)
    at JavascriptParser.callHooksForInfo (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2971:15)
    at JavascriptParser.walkMemberExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2800:27)
    at JavascriptParser.walkExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2305:10)
    at JavascriptParser.walkLeftRightExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2484:8)
    at JavascriptParser.walkLogicalExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2496:9)
    at JavascriptParser.walkExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2299:10)
    at JavascriptParser.walkLeftRightExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2483:8)
    at JavascriptParser.walkLogicalExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2496:9)
    at JavascriptParser.walkExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2299:10)
    at JavascriptParser.walkLeftRightExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2483:8)
    at JavascriptParser.walkLogicalExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2496:9)
    at JavascriptParser.walkExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2299:10)
    at JavascriptParser.walkConditionalExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2577:9)
    at JavascriptParser.walkExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2287:10)
    at JavascriptParser.walkVariableDeclaration (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2126:33)
    at JavascriptParser.walkStatement (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:1620:10)
    at JavascriptParser.walkStatements (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:1481:9)
    at JavascriptParser.parse (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:3375:9)
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/NormalModule.js:1087:26
    at processResult (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/NormalModule.js:800:11)
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/NormalModule.js:860:5
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:407:3
    at iterateNormalLoaders (/home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:233:10)
    at iterateNormalLoaders (/home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:240:10)
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:255:3
    at context.callback (/home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/home/nick/dev/application-monorepo/node_modules/.pnpm/source-map-loader@3.0.2_webpack@5.82.0/node_modules/source-map-loader/dist/index.js:29:5)
    at LOADER_EXECUTION (/home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:132:14)
    at runSyncOrAsync (/home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:133:4)
    at iterateNormalLoaders (/home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:251:2)
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:224:4
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/NormalModule.js:834:15
    at Array.eval (eval at create (/home/nick/dev/application-monorepo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:12:1)
    at runCallbacks (/home/nick/dev/application-monorepo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/enhanced-resolve@5.12.0/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:200:4
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/graceful-fs@4.2.10/node_modules/graceful-fs/graceful-fs.js:123:16
    at /home/nick/.cache/Cypress/12.11.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:123:16
    at /home/nick/.cache/Cypress/12.11.0/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
ERROR in ../../../node_modules/.pnpm/styled-components@5.3.5_react-dom@18.2.0_react-is@18.2.0_react@18.2.0/node_modules/styled-components/dist/styled-components.browser.esm.js
Module parse failed: parser.destructuringAssignmentPropertiesFor is not a function
File was processed with these loaders:
 * ../../../node_modules/.pnpm/source-map-loader@3.0.2_webpack@5.82.0/node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
TypeError: parser.destructuringAssignmentPropertiesFor is not a function
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.82.0_esbuild@0.17.11/node_modules/webpack/lib/DefinePlugin.js:575:16
    at Hook.eval (eval at create (/home/nick/dev/application-monorepo/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at JavascriptParser.callHooksForInfoWithFallback (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:3022:24)
    at JavascriptParser.callHooksForInfo (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2971:15)
    at JavascriptParser.walkMemberExpressionWithExpressionName (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2866:24)
    at JavascriptParser.walkMemberExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2816:11)
    at JavascriptParser.walkExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2305:10)
    at JavascriptParser.walkLeftRightExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2483:8)
    at JavascriptParser.walkLogicalExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2496:9)
    at JavascriptParser.walkExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2299:10)
    at JavascriptParser.walkLeftRightExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2484:8)
    at JavascriptParser.walkLogicalExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2496:9)
    at JavascriptParser.walkExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2299:10)
    at JavascriptParser.walkLeftRightExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2483:8)
    at JavascriptParser.walkLogicalExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2496:9)
    at JavascriptParser.walkExpression (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2299:10)
    at JavascriptParser.walkVariableDeclaration (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:2126:33)
    at JavascriptParser.walkStatement (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:1620:10)
    at JavascriptParser.walkStatements (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:1481:9)
    at JavascriptParser.parse (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/javascript/JavascriptParser.js:3375:9)
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/NormalModule.js:1087:26
    at processResult (/home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/NormalModule.js:800:11)
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/webpack@5.75.0_esbuild@0.17.11/node_modules/webpack/lib/NormalModule.js:860:5
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:407:3
    at iterateNormalLoaders (/home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:233:10)
    at iterateNormalLoaders (/home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:240:10)
    at /home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:255:3
    at context.callback (/home/nick/dev/application-monorepo/node_modules/.pnpm/loader-runner@4.3.0/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/home/nick/dev/application-monorepo/node_modules/.pnpm/source-map-loader@3.0.2_webpack@5.82.0/node_modules/source-map-loader/dist/index.js:143:3)
ERROR in Conflict: Multiple assets emit different content to the same filename index.html
webpack compiled with 4 errors (6d8cf2a01e2d2491)
No errors found.
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Nick-Lucas** [comment]
This [stackoverflow post](https://stackoverflow.com/questions/76000975/nx-angular-project-build-failed-after-upgrading-to-webpack-5-79-0) suggested that:

1. using a custom webpack.config.js
2. having conflicting webpack versions

Could cause the error, looking at my repo:

* package.json and `./node_modules/webpack` contains webpack set at `^5.75.0`
*  `./node_modules/@nx/webpack/package.json` is set at `^5.80.0` though
* `./node_modules/@nx/webpack/node_modules/.bin/webpack` is referring to `webpack@5.82.0_esbuild@0.17.11/node_modules/webpack/bin/webpack.js`

Upgrading webpack to latest in `package.json` seems to resolve this error. Looks like Nx has let some verisons get out of line during migrations

**Comment by barbados-clemens** [comment]
@Nick-Lucas thanks for opening the issue.

do you have a repo I can take a look at?
what framework are you using with component testing? looks like react?
can you share the `cypress.config.ts` and webpack config you're using?

**Comment by Nick-Lucas** [comment]
Afraid I haven't had a chance to try and reproduce dry, and now we're getting a new King in Blighty so won't be able to share deeper details until Tuesday.

As above I've resolved the issue by upgrading the package.json webpack version. Nx is using a newer version internally than it upgraded me to during the migration path - this repo started out on Nx 13 or 14 and has been migrated regularly up until today - so I believe the next Nx version just needs a migration added to check that webpack is in-line with @nx/webpack's version. Cypress version is also what Nx prescribed I believe.

Full repro conditions as I understand them:

* Nx 16.1.0
* Webpack locked at `5.75.0` on the repo package.json
* Have a React app with Component-Testing added
* Add a custom webpack.config.js to the React app

**Comment by madelk** [comment]
I just had the same issue when going from 16.0.3 to 16.1.3 on my React application. I hope to dig in over the next day or so to isolate the issue, my upgrade only contained package version bumps.

**Comment by madelk** [comment]
I just had to change my `"webpack": "^5.76.2",` to `"webpack": "^5.82.0",` and that got me rolling

**Comment by rathpc** [comment]
as @madelk stated, I changed the same thing and was able to get past the issue. Mismatching webpack versions caused the issue. `npm ls webpack` will show you all the versions being requested and this is where I saw my application was trying to use 2 different ones

**Comment by barbados-clemens** [comment]
Hi all, sorry for getting back late on this. but confirmed that the mixed match webpack versions are the issue. 
it doesn't happen in new workspaces as the webpack dep isn't installed by default, so that package wasn't version bumped in the workspace package.json when changed in the @nx/webpack package causing the mismatch. 

I'll add a migration the @nx/webpack to bump that version in peoples package.json if it exists which should solve the issue for anyone down the road. also if you're not using webpack outside of @nx/webpack. i.e. not calling webpack directly anywhere. it should be safe to remove the dep from your package.json since it's a dep of @nx/webpack.

**Comment by rathpc** [comment]
@barbados-clemens Thanks Caleb, that will definitely help!
