### ISSUE TITLE
Generating react library causes tests to fail after upgrading to 10.3.0

### ISSUE THREAD

**Issue by maierson** [nrwl/nx#3885]
## Current Behavior
Generate a data-access library under an existing directory completes successfully. After this running jest tests errors out on any of the libs with 

```
(oldOptions[key] || []).map is not a function
```

## Expected Behavior
The tests should run successfully.

## Steps to Reproduce
Write some lib tests that pass for all libs
```
yarn nx run-many --target=test --all
```
Create a new library by running this command:
```
nx generate @nrwl/react:library --name=data-access --directory=ui/main --no-component --tags='scope:ui-main, type:data-access'
```
Run tests again

### Failure Logs
```
(oldOptions[key] || []).map is not a function
```

### Environment

```
  nx : 10.3.0
  @nrwl/angular : Not Found
  @nrwl/cli : 10.3.0
  @nrwl/cypress : 10.3.0
  @nrwl/eslint-plugin-nx : 10.3.0
  @nrwl/express : 10.3.0
  @nrwl/jest : 10.3.0
  @nrwl/linter : 10.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.3.0
  @nrwl/react : 10.3.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.0
  @nrwl/web : 10.3.0
  @nrwl/workspace : 10.3.0
  typescript : 4.0.3
```
Downgrading back to `10.2.1` fixes the problem.

One difference i noticed is in the lib's jest.config.js

```js
module.exports = {
  ...
  preset: "../../../../jest.config.js", // <-- this value is ../../../../jest.preset.js in 10.3.0
  ...
};
```

**Comment by tmakola** [comment]
I experience the same issue after upgrading to 10.3.0.
In my case, it was after adding a new node library which seems to me not at all to be related to React but libraries in general.  `nx g @nrwl/node:library now-version`.

What I noticed is the `jest.config.js` in the root folder had an additional property added to it that seemed to lock Jest to a specific project. Therefore only the newly added project was testable.

Removing the file, allowed all tests from all projects to function again.

```
module.exports = {
    ...
    passWithNoTests: true,
    projects: '<rootDir>/libs/now-version' // <--- newly added property. should be removed
};
```

**Comment by maierson** [comment]
This is still an issue in 10.3.1
@tmakola thank you for the comment above - I can confirm your fix restores testing functionality for us.

**Comment by Mobiletainment** [comment]
I can confirm that this is not react specific and happened to me on a node library as well. @tmakola's trick solved it for me, too!

**Comment by tsinghammer** [comment]
@tmakola thank you, too! Saved me a lot of time.

**Comment by bekos** [comment]
@maierson @Mobiletainment  can you please elaborate on the steps to reproduce it? I have tried both the latest and 10.3.0 and wasn't able to do so 🤔

**Comment by maierson** [comment]
@bekos Just the steps at the top of this thread. I started with nx when it was at version 8... and kept migrating up. I think the migration process might not have handled this properly at some point in the process which might be why this is happening.  Do you have a `jest.config.js` at the root of your project? And does it have a `"projects"` key in it?

**Comment by ZackDeRose** [comment]
👋 Hi all, I am able to reproduce this issue with

+ `npx create-nx-workspace@9.0.0 test`
+ `nx migrate 10.3.0` (and follow up commands to complete the migration)
+ `nx g @nrwl/react:library --name=test-lib`
+ `nx test test`

(reproduction [here](https://github.com/ZackDeRose/upgrading-messes-up-tests-3885) see commits for above steps)

I don't see this issue happening in most current, will attempt to identify when it started.

**Comment by ZackDeRose** [comment]
Asserted that this issue remains even with migrating up to Nx version 12.

I submitted #5346 to fix this issue (more details on the precise issue in the description), with eyes on a possible migration to adjust the `jest.config.js` in the future.

**Comment by ZackDeRose** [comment]
Hi all - going back to [my reproduction](https://github.com/ZackDeRose/upgrading-messes-up-tests-3885) if you trace back through the commits, you can see that while I create a `migrations.json` file, I entered the command incorrectly as:

`nx migrate --run-migrations`

Whereas prior versions (pre 11.4) required a target `migrations.json` file (so like so: `nx migrate --run-migrations=migrations.json`).

As such, these migrations were generated, but not ran. We've added more clarity around this in current versions - the cli prompts with `nx migrate --run-migrations=migrations.json` and we also now default to `migrations.json` if no explicit path is provided.

To others having issues with this in their workspaces after migrating, you can rerun this migration specifically by creating a `migrations.json` with the contents:

```json
{
  "migrations": [
    {
      "version": "10.3.0-beta.1",
      "description": "Adds all jest projects into the root jest config",
      "factory": "./src/migrations/update-10-3-0/update-projects-property",
      "package": "@nrwl/jest",
      "name": "update-projects-property"
    }
  ]
}
```

And then run `nx migrate --run-migrations=migrations.json` to correct your workspaces going forward.

Also note that the `projects` property on your root `jest.config.json` exists to enable tooling with VsCode (and other IDEs) that allows your IDE to target and these tests correctly (see below). Removing the `projects` property from your root `jest.config.json` - or removing this file entirely - will allow your tests to be run via the nx CLI, but running jest tests via your IDE may break.

![Screen Shot 2021-04-14 at 1 06 35 PM](https://user-images.githubusercontent.com/3788405/114772123-49f25800-9d22-11eb-9444-771fae7b94c5.png)

**Comment by prmichaelsen** [comment]
@ZackDeRose this worked. i just commented out projects in that file and it also still works in the ide. thanks!
