### ISSUE TITLE
 Failed to load plugin '@angular-eslint' after migrating to 19.2.0

### ISSUE THREAD

**Issue by ArielGueta** [nrwl/nx#26408]
### Current Behavior

Running nx lint give this error:

 Failed to load plugin '@angular-eslint' declared in 'foo/.eslintrc.json » ../.eslintrc.json#overrides[0] » plugin:@nx/angular': Cannot find module '@typescript-eslint/utils'

### Expected Behavior

No error

### Steps to Reproduce

Migrate

### Nx Report

```shell
Node   : 20.11.1
OS     : darwin-arm64
npm    : 10.2.4

nx                 : 19.2.0
@nx/js             : 19.2.0
@nx/jest           : 19.2.0
@nx/linter         : 19.2.0
@nx/eslint         : 19.2.0
@nx/workspace      : 19.2.0
@nx/angular        : 19.2.0
@nx/devkit         : 19.2.0
@nx/eslint-plugin  : 19.2.0
@nx/playwright     : 19.2.0
@nx/plugin         : 19.2.0
@nrwl/tao          : 19.2.0
@nx/vite           : 19.2.0
@nx/web            : 19.2.0
@nx/webpack        : 19.2.0
typescript         : 5.4.5
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ArielGueta** [comment]
Revert from:

    "@angular-eslint/eslint-plugin": "^18.0.1",
    "@angular-eslint/eslint-plugin-template": "18.0.1",
    "@angular-eslint/template-parser": "18.0.1",

to:
    "@angular-eslint/eslint-plugin": "^17.3.0",
    "@angular-eslint/eslint-plugin-template": "17.3.0",
    "@angular-eslint/template-parser": "17.3.0",


fix the issue, but it's still an issue
