### ISSUE TITLE
"npx nx" gives error "Error: Cannot find module '../src/utils/find-workspace-root'" since 19.3

### ISSUE THREAD

**Issue by mligtenberg** [nrwl/nx#26546]
### Current Behavior

When running any command via ``npx nx`` the error below is thrown:
``Error: Cannot find module '../src/utils/find-workspace-root'``

Downgrading only the nx package to 19.2.3 fixes the issue

### Expected Behavior

It should be able to run any ``npx nx`` command like ``npx nx [project] build``

### Steps to Reproduce

1. run ``npx create-nx-workspace@latest`` and setup a basic Angular App, without ssr, using scss and cypress, name the issuetest
2.run ``npx nx issuetest build``

### Nx Report

```shell
Node   : 20.14.0
OS     : darwin-arm64
npm    : 10.8.1

nx                 : 19.3.0
@nx/js             : 19.3.0
@nx/jest           : 19.3.0
@nx/linter         : 19.3.0
@nx/eslint         : 19.3.0
@nx/workspace      : 19.3.0
@nx/angular        : 19.3.0
@nx/cypress        : 19.3.0
@nx/devkit         : 19.3.0
@nx/eslint-plugin  : 19.3.0
@nrwl/tao          : 19.3.0
@nx/web            : 19.3.0
@nx/webpack        : 19.3.0
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/cypress/plugin
@nx/eslint/plugin
```

### Failure Logs

```shell
node:internal/modules/cjs/loader:1148
  throw err;
  ^

Error: Cannot find module '../src/utils/find-workspace-root'
Require stack:
- /Users/[user]/WebstormProjects/[projectname]/node_modules/.bin/nx
    at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
    at Module._load (node:internal/modules/cjs/loader:986:27)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
```

### Package Manager Version

npm 10.8.1

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Running nx as a global registered tool (without npx in front of it) works properly
This breaks nx-console in jetbrains IDE's since it uses the locally installed instance of nx

**Comment by mligtenberg** [comment]
some more information: My best guess is that it has something todo with the setup script.
I tried running an ``npm ci`` on a clean installation and got the following error:
``npm error `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.``

Basically the lock file generated by the installer script was missing some esbuild packages

running an ``npm i`` made the package file work correctly but ``npx nx`` was still broken.
after running ``npm ci`` ``npx nx`` worked again

**Comment by djlogan2** [comment]
It has not been fixed. A create of an nx project followed by an attempt to run the result fails with this error.

**Comment by nhhockeyplayer** [comment]
Guys... 

- Local: v20.3.0
- Global: v20.3.0

is not looking good
I've got a formidable NX Angular MFE (with custom webpack setup of unending BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default. PROBLEMS that wont resolve done every webpack attempt no resolve)

but worse now is latest migration

my entire project after migrating today to 20.3.0 cannot even find my buildable/non-publishable/local scaffold libs
like
         `  import { SharedRootUiSharedMaterialModule } from '@nhhockeyplayer/shared-root-ui-shared-material'
`
configured appropriately as 
```
            "@nhhockeyplayer/shared-root-ui-shared-material": [
                "libs/shared/root/ui-shared-material/src/index.ts"
            ],
```

TS2307: Cannot find module '@nhhockeyplayer/shared-root-ui-shared-material' or its corresponding type declarations.

just a heads up FYI... this stuff has to stop
the issues are overwhelming
especially the webpack < 5 flood
the amount of compiler errors are pages upon pages

something has to improve

we cant stay caught in the build mess 85% of the time

sorry... someone needs to step up here and tighten up this effort

**Comment by ManuelSch** [comment]
Running a brand new project after creation should be the bare minimum of what NX is supposed to do - how is this still not fixed?

**Comment by carlosnturing** [comment]
For `nx@20.8.1`, instead of running `nx serve foo` or even `npx nx serve foo` from an NPM script, running `node node_modules/nx/bin/nx.js` works to get around this.
