### ISSUE TITLE
Nx tasks fail after upgrading to 21.6.2 ("isAiAgent is not a function")

### ISSUE THREAD

**Issue by tjfroll** [nrwl/nx#32898]
### Current Behavior

Our repository is currently on Nx 21.2.4. After performing the upgrade to 21.6.2 (using `pnpm nx migrate latest` -> `pnpm i` -> `pnpm nx migrate --run-migrations`), any attempt to run a task via Nx immediately fails with the following error:

```
> nx build

(0 , native_1.isAiAgent) is not a function
```

This occurs for any and all tasks executed via Nx, regardless of the executor type (`run-commands`, `vite`, etc), and regardless of location in the repository (repo root or within individual apps/packages).

### Expected Behavior

Nx tasks should execute without error.

### Steps to Reproduce

I suspect this may be related to our use of pnpm catalogs, as Nx has had issues with this in other features. Our setup is as follows:

```
/root/
- apps/
  - my-app/
    - project.json
    - package.json
- packages/
  - my-package/
    - project.json
    - package.json
- package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
- nx.json
```

Before the upgrade migration, our Nx and Typescript dependencies in the root package.json were defined as `catalog:` and defined in the `catalog` field of `pnpm-workspace.yaml`. After migration, the root package.json was updated to have these versions defined directly, not from the catalog.

### Nx Report

Before:
```shell
NX  Unable to locate swc-node or ts-node. Nx will be unable to run local ts files without transpiling.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 NX   Report complete - copy this into the issue template

Node           : 22.18.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 10.15.1

nx          : 21.2.4
@nx/js      : 21.2.4
@nx/plugin  : 21.2.4
@nx/vite    : 21.2.4
typescript  : 5.8.2
---------------------------------------
Cache Usage: 0.00 B / 46.04 GB
```

After:
 ```shell
NX  Unable to locate swc-node or ts-node. Nx will be unable to run local ts files without transpiling.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 NX   Report complete - copy this into the issue template

Node           : 22.18.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 10.15.1

nx          : 21.6.2
@nx/js      : 21.6.2
@nx/plugin  : 21.6.2
@nx/vite    : 21.6.2
typescript  : 5.9.2
---------------------------------------
Cache Usage: 0.00 B / 46.04 GB
```

### Failure Logs

```shell

```

### Package Manager Version

pnpm@10.15.1

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by JumBay** [comment]
Got the same issue, just running `nx` command does this:
```
$ nx
(0 , native_1.isAiAgent) is not a function
```

I'm using pnpm too.

**Comment by johanndev** [comment]
Getting the same error on windows + node:

```bash
$ npx nx
(0 , native_1.isAiAgent) is not a function

$ npx nx --version
Nx Version:
- Local: v21.6.2
- Global: Not found

$ node --version  
v22.5.1
```

**EDIT:** Just did a check with `nx@21.6.1` - the older version does not throw the error.

**Comment by astanb** [comment]
Same with bun

**Comment by hamdardSingh** [comment]
same issue using pnpm 
```
pnpm nx
(0 , native_1.isAiAgent) is not a function

**Comment by hamdardSingh** [comment]
There seems to be an issue with the interactive terminal. Setting `export NX_TUI=false` resolves it for me for now

**Comment by leosvelperez** [comment]
Thanks for reporting this!

We're looking into this issue. A workaround in the meantime is to delete your lockfile or update it so that the Nx native packages are updated to match the `nx` package version. If it still doesn't work after doing so, run `nx reset` and try again.
