### ISSUE TITLE
Migration from 14.8.6 to 15.0.4 makes our libs unbuildable with "is not under 'rootDir'" errors

### ISSUE THREAD

**Issue by leandro-branco** [nrwl/nx#12874]
## Current Behavior

After migrating from v14.8.6 to v15.04, some libraries start showing errors regarding `File is not under 'rootDir'`. Using the v14.8.6, it used to work fine. 

The reproduction repo contains three libraries:
* `libs/frame/common`
* `libs/frame/core/errors`
* `libs/frame/core/valid`.

When trying to build the lib `libs/frame/core/valid`, it fails with the following error:

```bash
Compiling TypeScript files for project "frame-core-valid"...
libs/frame/common/src/index.ts:1:15 - error TS6059: File '/Users/leand/github.com/leandro-branco/nx-rootdir-issue/libs/frame/common/src/lib/grpc-status.ts' is not under 'rootDir' 'libs/frame/core/valid'. 'rootDir' is expected to contain all source files.

1 export * from './lib/grpc-status'
                ~~~~~~~~~~~~~~~~~~~
libs/frame/common/src/index.ts:2:15 - error TS6059: File '/Users/leand/github.com/leandro-branco/nx-rootdir-issue/libs/frame/common/src/lib/http-status.ts' is not under 'rootDir' 'libs/frame/core/valid'. 'rootDir' is expected to contain all source files.

2 export * from './lib/http-status'
```

Note that the `libs/frame/core/valid` doesn't import any code from `libs/frame/common`, only from `libs/frame/core/errors.` If we force the import of the common library, the build works fine.

I've already tried to remove cache `rm -rf ./node_modules/.cache/nx` and reset nx and to include `"analyzeSourceFiles": true` into nx.json.

Not sure if it's related to https://github.com/nrwl/nx/issues/12338#issuecomment-1284276013 

## Expected Behavior
To build with no errors

## Steps to Reproduce

Clone the repro code: https://github.com/leandro-branco/nx-rootdir-issue
Run the commands:
```bash
yarn install
nx run frame-core-valid:build
```

### Environment

```bash
 >  NX   Report complete - copy this into the issue template

   Node : 16.16.0
   OS   : darwin x64
   yarn : 1.22.19
   
   nx : 15.0.4
   @nrwl/angular : 15.0.4
   @nrwl/cypress : 15.0.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.0.4
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.0.4
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.0.4
   @nrwl/js : 15.0.4
   @nrwl/linter : 15.0.4
   @nrwl/nest : 15.0.4
   @nrwl/next : 15.0.4
   @nrwl/node : 15.0.4
   @nrwl/nx-cloud : 15.0.0
   @nrwl/nx-plugin : 15.0.4
   @nrwl/react : 15.0.4
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.0.4
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.0.4
   @nrwl/web : 15.0.4
   @nrwl/webpack : 15.0.4
   @nrwl/workspace : 15.0.4
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @storybook/angular: 6.5.12
```

**Comment by darckoune** [comment]
Hello ! For information, this bug is caused by the version 15.0.4 specificaaly.
I tried upgrading from 15.0.3 to 15.0.4 and my builds started to fail with these errors messages !

Thank you ! :)

**Comment by acburdine** [comment]
can confirm I'm seeing the same issue with v15.0.4. If a project `a` depends on project `b`, and `b` depends on `c` -> attempting to build `a` does not cause `c` to be built automatically, which causes the "rootDir" error message.

Adding `c` to the `implicitDependencies` of `a` fixes the issue.

**Comment by FrozenPandaz** [comment]
@jaysoo This is caused by https://github.com/nrwl/nx/commit/5f584eaf4928ef7636571f67aa3e2f69dd89cd3e

**Comment by tinesoft** [comment]
@FrozenPandaz the commit https://github.com/nrwl/nx/commit/5f584eaf4928ef7636571f67aa3e2f69dd89cd3e from @jaysoo  and released in 
 [15.0.4](https://github.com/nrwl/nx/releases/tag/15.0.4) had fixed the issue of **"dependencies of a `packageA` being wrongly included in packages depending on `packageA`"**. For example:

- packageA 
  - depA,
  - depB

- packageB
	- packageA

when building `packageB`, prior to Nx `v15.0.4`, the generated `package.json` would contain:
- packageB
	- dep1  `// should NOT contains this dep`
	- dep2 `// should NOT contains this dep`
	- packageA `// should ONLY contains this`

With the new fix [37ae27a](https://github.com/jaysoo/nx/commit/37ae27a2269ef69fcaabd393c5b43151db4186a0) released in [15.0.5](https://github.com/nrwl/nx/releases/tag/15.0.5) the above issue above is back again (see in this [repo](https://github.com/tinesoft/nxrocks)) ... :-(
