### ISSUE TITLE
Cannot find module or its corresponding type declarations.

### ISSUE THREAD

**Issue by JuniusBBD** [nrwl/nx#33204]
### Current Behavior

Cannot find module or its corresponding type declarations.

<img width="920" height="163" alt="Image" src="https://github.com/user-attachments/assets/ee16194c-c7b1-4e98-b626-76f918d4d65d" />

### Expected Behavior

Nx should correctly resolve the module and its type declarations without throwing this error.

### GitHub Repo

https://gitlab.com/Junius.Lekgwara/nx-mono

### Steps to Reproduce

1. Clone the repository. (https://gitlab.com/Junius.Lekgwara/nx-mono)
2. run `bun install`
3. start the app. `bunx nx dev apps/app2`

### Nx Report

```shell
$ bunx nx report                                                                                                                                                                                 (main*) [~/t/mono]

 NX   Report complete - copy this into the issue template

Node           : 20.19.0
OS             : darwin-x64
Native Target  : x86_64-macos
bun            : 1.3.1

nx                 : 22.0.1
@nx/js             : 22.0.1
@nx/eslint         : 22.0.1
@nx/workspace      : 22.0.1
@nx/devkit         : 22.0.1
@nx/eslint-plugin  : 22.0.1
@nx/playwright     : 22.0.1
@nx/react          : 22.0.1
@nx/vite           : 22.0.1
@nx/web            : 22.0.1
typescript         : 5.9.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/eslint/plugin
@nx/vite/plugin
@nx/playwright/plugin
---------------------------------------
```

### Failure Logs

```shell
tsc --build --emitDeclarationOnly
src/app/app.tsx(1,23): error TS2307: Cannot find module '@mono/mylib' or its corresponding type declarations.
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by Tenpeter** [comment]
I'm also getting the same issue, I downgraded to v20 and everything works.

**Comment by matttrawicki** [comment]
Seeing this after upgrading to 22.5.4 from 20.8.2

**Comment by matheo** [comment]
I'm getting this after upgrading Nx from v22.6.5 to v22.7.1

**Comment by ssc-io** [comment]
I'm getting this after upgrading Nx from v22.3.3 to v22.7.1

**Comment by ssc-io** [comment]
Fixed it by removing a trailing comma from my tsconfig.json file..

Issue solved by Copilot ❤:

> Root cause: Nx 22.7.1 introduced a new resolvePathsBaseUrl function that walks the tsconfig extends chain using JSON.parse (strict JSON) to resolve path mappings to absolute paths. The trailing comma in tsconfig.json is valid JSONC (which TypeScript accepts) but invalid strict JSON, causing a silent parse failure. This broke the extends chain.

**Comment by matheo** [comment]
> Fixed it by removing a trailing comma from my tsconfig.json file..

I had no trailing commas but one tsconfig had inline comments, maybe that one broke the chain 😕 

Edit: my build still fails after a node_modules refresh, rolling back to v22.6.5

**Comment by FrozenPandaz** [comment]
This was fixed by https://github.com/nrwl/nx/pull/35539 🎉
