### ISSUE TITLE
Workspace schematics fail to run after updating from NX 10 to 11

### ISSUE THREAD

**Issue by CookieNick** [nrwl/nx#4759]
## Current Behavior
When I run the `nx workspace-schematic` command

## Expected Behavior
I expect it to run fine like it did in NX 10.

## Steps to Reproduce
I'm not sure what changed, but after migrating to NX 11, the schematics were moved to generators, and now all of them give a weird error about a non-existing file.

I've made a repro; https://github.com/CookieNick/nx-issue-4759 with most bloat removed. To reproduce;
1. `npm i`
2. Run `nx workspace-schematic test --name=a --no-interactive --dry-run`
3. See error

Doesn't matter if I don't do dry run. The schematic (or generator) is generated with `nx generate @nrwl/workspace:workspace-generator`, so you can generate your own and see the error.

### Failure Logs
```
PS C:\Source\Web> nx workspace-schematic react-webapp-component --name=standard-processes
npx: installed 1 in 2.159s
error TS5014: Failed to parse file 'C:/Source/Web/tools/tsconfig.generated.json/tsconfig.json': Unexpected token u in JSON at position 0.
PS C:\Source\Web>
```

### Environment
>  NX  Report complete - copy this into the issue template

  Node : 14.14.0
  OS   : win32 x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.2.11
  @nrwl/cypress : 11.2.11
  @nrwl/devkit : 11.2.11
  @nrwl/eslint-plugin-nx : 11.2.11
  @nrwl/express : Not Found
  @nrwl/jest : 11.2.11
  @nrwl/linter : 11.2.11
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 11.2.11
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.2.11
  @nrwl/web : 11.2.11
  @nrwl/workspace : 11.2.11
  typescript : 4.1.3

**Comment by CookieNick** [comment]
I've tried to reproduce it on the example repro, but I'm not able to. I've even replaced the files in the root with the files I have in my repro, including installing other packages.

Can you shed any light on this?

**Comment by mandarini** [comment]
Hi there @CookieNick !  Thanks for filing an issue!

I generated a new workspace with Nx v10, I generated a workspace-schematic named `test` and I used it successfully. Then I migrated to Nx v11, and I ran it again, and it worked, so I could not reproduce your issue.

Here are the commands I ran:

```
npx create-nx-workspace@10.4.7 nx-ten
cd nx-ten
nx generate @nrwl/workspace:workspace-schematic --name=test
nx workspace-schematic test --name=test-lib
```
WORKED!

So, now I migrate to Nx `11.2.11` (which you are using):

```
nx migrate @nrwl/workspace@11.2.11
yarn
nx migrate --run-migrations=migrations.json
```
Migration successful
Now let's try the schematic again:
```
nx workspace-schematic test --name=other-lib
```

So, running these steps everything was successful.
Let me know if you can reproduce!

Thank you!

**Comment by CookieNick** [comment]
@mandarini Thanks for getting back to me!

Yeah it works for me on the [example repo](https://github.com/nrwl/nx-examples) too, but somehow it doesn't work on my repo. I already tried replacing most settings from my repo to the example to see if I could reproduce, but I somehow can't. My repo has a lot of projects, so I would like to avoid creating a new workspace from scratch.

I've already made a repo to reproduce this issue at; https://github.com/CookieNick/nx-issue-4759

To reproduce;
1. npm i (yarn probably works too, but we use npm and I saw you also used npm)
2. `Run nx workspace-schematic test --name=a --no-interactive --dry-run`
3. See error;
 
```
PS C:\Source\Web> nx workspace-schematic react-webapp-component --name=standard-processes
npx: installed 1 in 2.159s
error TS5014: Failed to parse file 'C:/Source/Web/tools/tsconfig.generated.json/tsconfig.json': Unexpected token u in JSON at position 0.
PS C:\Source\Web>
```

I'm guessing it's something in my settings, but I've already tried moving all my settings to the [example project](https://github.com/nrwl/nx-examples) but it still works then. Your example repository (https://github.com/mandarini/test-4759) also works for me, but mine (https://github.com/CookieNick/nx-issue-4759) doesn't...

**Comment by vsavkin** [comment]
@CookieNick if you rename the root tsconfig to tsconfig.base.json and update tsconfig.tools.json, would you still have same issue?

**Comment by CookieNick** [comment]
@vsavkin Thanks for your reply!

I've been working the problem basically since I've reported it, and found it strange it worked on your repo's even when I synchronized everything. In one attempt I reinstalled all node_modules in my repro with the ones you have, then installed my own again... And it worked! Somehow something weird in the package-lock I guess. I've done the same in the main repo and it works.

Old schematics work, though I had to do a little trickery to get a custom schematic that calls the `nrwl/jest` schematic to work as you've migrated to `nrwl/devkit` and we're still on the angular devkit. New schematics don't work because I get an error on, like you said, `tsconfig.base.json`. I've renamed those too, and all the references, and now generating a new schematic and generating based on that also works. There is no migration for renaming `tsconfig.json` to `tsconfig.base.json`? Or I might have reverted that to fix other issues.

Thank you so much for your help! I hope my steps can help someone with similar issues.

**Comment by mandarini** [comment]
Hi @CookieNick! I just used the `nx migrate` to migrate everything from one version to the other, and made no other changes/renames on my end! So maybe you reverted something.. :( I hope you are able to move forward now, and you issue is solved! Thank you very much for taking the time to report it!

**Comment by CookieNick** [comment]
Hello @mandarini  I'm sorry if I didn't explain correctly, my repo is a snapshot from _after_ I've ran the migrations. Then if you do `nx workspace-schematic test --name=a --no-interactive --dry-run`, it will fail with the message. The problem was probably is some weird npm issue, so you'd have to do `npm i` or even `npm ci` to reproduce succesfully, and even then it might just have failed on my machine somehow. Thanks for getting back to me though, I really appreciate it!

**Comment by ohabash** [comment]
@CookieNick any solution?

**Comment by CookieNick** [comment]
@ohabash  I couldn't find the real cause, so if you're having the same problem on your code, but not on the example repo, you can try reinstalling the packages or changing the versions of them. Never figured out what fixed it precisely though, so I'm afraid that's all I can tell to help...

**Comment by ohabash** [comment]
@CookieNick I think it was a node installation problem? It worked when switching to linux. Some pc related issue. Not sure
