### ISSUE TITLE
Mismatch Between Type Declaration File Names and types Field in Generated package.json

### ISSUE THREAD

**Issue by ashkanhosseini** [nrwl/nx#29308]
### Current Behavior

When generating a publishable library using the @nx/js generator with the Rollup bundler, the nx build command produces a type declaration file (index.cjs.d.ts) that is not consistent with the types field in the generated package.json.

Specifically:

1. The Rollup config generates index.cjs.d.ts in the dist directory.
2. The types field in package.json is set to ./dist/index.d.ts.
3. Similarly, the exports section refers to ./dist/index.d.ts for the types key

```json
"exports": {
  "./package.json": "./package.json",
  ".": {
    "types": "./dist/index.d.ts",
    "import": "./dist/index.esm.js",
    "default": "./dist/index.cjs.js"
  },
"types": "./dist/index.d.ts"
}
```

As a result, when the package is consumed outside the workspace, TypeScript fails to locate the type declarations.

Error example:
```lua
Could not find a declaration file for module '@myorg/example'. 
Module implicitly has an 'any' type because 'index.cjs.d.ts' does not match the 'types' field.

```

### Expected Behavior

The generated file names and package.json configuration should align. The following adjustments could resolve the issue:

1. The Rollup bundler should produce a type declaration file named index.d.ts (instead of index.cjs.d.ts).
2. Alternatively, the types field and exports key in the package.json should point to index.cjs.d.ts to match the generated output.

Either approach would ensure proper type declaration resolution in external projects but probably #1 makes more sense.

### Steps to Reproduce

1. Create a publishable library with Rollup bundler: `npx nx g @nx/js:library packages/example-types --bundler=rollup --publishable --importPath=@myorg/example
`
2. Build the library: `npx nx build example-types`
3. Inspect the output directory and package.json:

- Output includes index.cjs.d.ts in the dist folder.
- package.json has a types field pointing to ./dist/index.d.ts and an exports entry for types pointing to the same file.

4.  Attempt to use the package in an external project:
- Install the package and observe that TypeScript cannot resolve the type declarations.

resulting `dist` directory: 
```
dist/
  index.cjs.js
  index.esm.js
  index.cjs.d.ts

```

generated package.json: 
```json
{
  "types": "./dist/index.d.ts",
  "exports": {
    "./package.json": "./package.json",
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.esm.js",
      "default": "./dist/index.cjs.js"
    }
  }
}

```

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 22.11.0
OS             : darwin-arm64
Native Target  : aarch64-macos
yarn           : 4.5.3

nx                     : 20.2.2
@nx/js                 : 20.2.2
@nx/jest               : 20.2.2
@nx/eslint             : 20.2.2
@nx/workspace          : 20.2.2
@nx/devkit             : 20.2.2
@nx/eslint-plugin      : 20.2.2
@nx/module-federation  : 20.2.2
@nx/next               : 20.2.2
@nx/react              : 20.2.2
@nx/rollup             : 20.2.2
@nx/web                : 20.2.2
@nx/webpack            : 20.2.2
typescript             : 5.6.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/eslint/plugin
@nx/jest/plugin
@nx/next/plugin
@nx/rollup/plugin
```

### Failure Logs

```shell

```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by ptaranto** [comment]
I have also been facing this since upgrading from v14 to v17. 

When building and publishing a lib: `index.esm.d.ts` is generated, bundled and published instead of `index.d.ts`, when consuming the published package this is the error:

```
undefined
TypeScript error in undefined(undefined,undefined):
Cannot find type definition file for 'MY-PACKAGE'.
  The file is in the program because:
    Entry point for implicit type library 'MY-PACKAGE'  TS2688
```

**Comment by ashkanhosseini** [comment]
> I have also been facing this since upgrading from v14 to v17.
> 
> When building and publishing a lib: `index.esm.d.ts` is generated, bundled and published instead of `index.d.ts`, when consuming the published package this is the error:
> 
> ```
> undefined
> TypeScript error in undefined(undefined,undefined):
> Cannot find type definition file for 'MY-PACKAGE'.
>   The file is in the program because:
>     Entry point for implicit type library 'MY-PACKAGE'  TS2688
> ```

Hey @ptaranto, 
For now we came up with this workaround by having a rollup base config at the root and adding this to the plugins and extending this file by all the other roll up configs in the projects: 

```js
const copy = require('rollup-plugin-copy') 

const baseConfig = {
  rollupConfig: {
    plugins: [
      copy({
        targets: [{src: 'dist/index.esm.d.ts', dest: 'dist', rename: 'index.d.ts'}],
        hook: 'writeBundle',
      }),
    ],
  },
}

```

hope this helps. 
It's a bit inconvenient to extend this file in every package that is generated but it does the trick for now.

**Comment by Lonli-Lokli** [comment]
I have doubts regarding realization - why do we need prefixes in libs? 
I would say better approach will be naming file.mjs (file.d.mts)/file.cjs (file.d.cts), also it will remove types field in generated package.json as TypeScript will always resolve corresponding types.
