### PR TITLE
feat(schematics): support @angular/cli@6.1.1

### LINKED ISSUE #640: newTree.optimize is not a function - Error with  `ng g lib`
### Command 
```bash
ng generate lib mylib --dry-run
```

### Error

```
newTree.optimize is not a function
```

### Env

```
./node_modules/.bin/nx --version
6.1.1

 ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 6.1.0-rc.3
Node: 10.5.0
OS: darwin x64
Angular: 6.1.0-rc.3
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.7.0-rc.3
@angular-devkit/build-angular      0.7.0-rc.3
@angular-devkit/build-ng-packagr   0.7.0-rc.3
@angular-devkit/build-optimizer    0.7.0-rc.3
@angular-devkit/build-webpack      0.7.0-rc.3
@angular-devkit/core               0.6.8
@angular-devkit/schematics         0.6.8
@angular/cdk                       6.4.0
@angular/cdk-experimental          6.4.0
@angular/flex-layout               6.0.0-beta.16
@angular/material                  6.4.0
@angular/material-moment-adapter   6.4.0
@angular/pwa                       0.6.8
@ngtools/json-schema               1.1.0
@ngtools/webpack                   6.1.0-rc.3
@schematics/angular                0.6.8
@schematics/update                 0.7.0-rc.3
ng-packagr                         4.0.0
rxjs                               6.2.2
typescript                         2.9.2
webpack                            4.9.2
```

### LINKED ISSUE #645: Issue with Angular CLI 6.1.0
### Issue type

**I'm submitting a ...**

* [X ] bug report
* [ ] feature request

### Issue description

**Current behavior:**
Create new app using: 

`create-nx-workspace myworkspacename`

Then upgrade to Angular 6.1 using:

`ng update --all --force`

After that try to type:

`ng generate lib --help`

You'd get this error:

`Cannot find module '@schematics/angular/utility/route-utils'
Error: Cannot find module '@schematics/angular/utility/route-utils'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\hmuba\Downloads\Angular\myworkspacename\node_modules\@nrwl\schematics\src\collection\library\index.js:13:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)`

After some debugging, in Angular CLI 6.1.0 this file doesn't exist:
@schematics/angular/utility/route-utils

After reverting Angular CLI to version 6.0.1 the file is there so everything works

**Expected behavior:**

To work with Angular CLI 6.1.0

### PR DESCRIPTION
**Pull request by FrozenPandaz**
This updates dependencies and adds migrations necessary for the 6.2.0 release.

*  Angular (Framework) has been updated to 6.1.0
*  Angular CLI has been updated to 6.1.1
*  RxJS has been updated to 6.2.2
*  NgRx has been updated to 6.0.1
*  codelyzer has been updated to 4.2.2
*  Typescript has not been updated since we cannot use typescript 2.9.x yet.. 
   >  due to incompatibility with  Angular Devkit `nx affected:libs` has been added to scripts in `package.json`

Some Breaking Changes were addressed:

*  imports from devkit moved around
*  workspace-schematics was broken

Fixes #645,  Fixes #640.

### CODE REVIEW

File: packages/schematics/src/collection/ngrx/index.ts [hunk 1]
```diff
@@ -30,6 +30,11 @@ import { formatFiles } from '../../utils/rules/format-files';
 export default function generateNgrxCollection(_options: Schema): Rule {
   return (host: Tree, context: SchematicContext) => {
     const options = normalizeOptions(_options);
+
+    if (!host.exists(options.module)) {
+      throw new Error('Specified module does not exist');
```
Comment (ThomasBurleson) [inline packages/schematics/src/collection/ngrx/index.ts]: Please specify the module name in the error. Otherwise the error message is simply not clear.

```ts
throw new Error(`Specified module '${options.module}' does not exist.`);
```

File: packages/schematics/src/collection/ngrx/rules/add-imports-to-module.ts [hunk 2]
```diff
@@ -16,9 +16,6 @@ import { RequestContext } from './request-context';
 
 export function addImportsToModule(context: RequestContext): Rule {
   return (host: Tree) => {
-    if (!host.exists(context.options.module)) {
```
Comment (ThomasBurleson) [inline packages/schematics/src/collection/ngrx/rules/add-imports-to-module.ts]: @FrozenPandaz - why was this removed in favor of allowing a blank `""` module path?
In fact, I recommend:

```ts
if (!context.options.module) {
  throw new Error(`Required option 'module' was not specified`);
} else if (!host.exists(options.module)) {
  throw new Error(`Specified module '${options.module}' does not exist`);
}
```

Comment (FrozenPandaz) [reply packages/schematics/src/collection/ngrx/rules/add-imports-to-module.ts]: I asserted that options are valid here before any of these rules are called: https://github.com/nrwl/nx/pull/650/files/60cc67423e235d8a9baf889985614cc60f6add28#diff-f09349e38e598f4ec3630bd791e92d80R35

I added the error for providing an empty string.

File: packages/bazel/package.json [hunk 3]
```diff
@@ -4,17 +4,18 @@
   "description": "Nrwl Extensions for Angular: Bazel Schematics",
   "main": "index.js",
   "types": "index.d.js",
-  "peerDependencies": {},
   "author": "Victor Savkin",
   "license": "MIT",
   "schematics": "./src/collection.json",
   "dependencies": {
     "@ngrx/schematics": "6.0.1",
```
Comment (vsavkin) [inline packages/bazel/package.json]: should be made a peer dependency too
