### ISSUE TITLE
BUG [tao]: Error logging fails when logger.error is called with an Error instead of a string

### ISSUE THREAD

**Issue by fdeslandes-wk** [nrwl/nx#6364]
## Current Behavior
After migrating from 12.0.6 to 12.5.7, I have some problems with `npx ng run projectName:storybook`.  This was not working and the only error in the console, when using the --verbose option, was:

> Executing task: npx ng run shared-common-ui-core:storybook --verbose <

> nx run shared-common-ui-core:storybook --verbose 
> s.startsWith is not a function
> TypeError: s.startsWith is not a function
>    at Object.error (C:\projects\wkc-web\node_modules\@nrwl\tao\src\shared\logger.js:10:15)
>   at C:\projects\wkc-web\node_modules\@nrwl\storybook\src\executors\storybook\storybook.impl.js:43:33
>    at processTicksAndRejections (internal/process/task_queues.js:97:5)
>
> ———————————————————————————————————————————————
>
>  NX   ERROR  Running target "shared-common-ui-core:storybook" failed
>
>  Failed tasks:
>  
>  - shared-common-ui-core:storybook
>  
>  Hint: run the command with --verbose for more details.
>
>The terminal process "C:\windows\System32\cmd.exe /d /c npx ng run shared-common-ui-core:storybook --verbose" terminated with exit code: 1.

I found this is caused by this code, in tao logger.js:

```javascript
error: (s) => {
        if (s.startsWith('NX ')) {
            console.error(`\n${exports.NX_ERROR} ${chalk.bold(chalk.red(s.substr(3)))}\n`);
        }
        else {
            console.error(chalk.bold(chalk.red(s)));
        }
    },
```

which is called by this, in storybook.impl.js:

```javascript
return server_1.buildDevStandalone(Object.assign(Object.assign({}, options), { ci: true, configType: env.toUpperCase() })).catch((error) => {
        var _a;
        // TODO(juri): find a better cleaner way to handle these. Taken from:
        // https://github.com/storybookjs/storybook/blob/dea23e5e9a3e7f5bb25cb6520d3011cc710796c8/lib/core-server/src/build-dev.ts#L138-L166
        if (error instanceof Error) {
            if (error.error) {
                devkit_1.logger.error(error.error);
            }
            else if (error.stats &&
                error.stats.compilation.errors) {
                error.stats.compilation.errors.forEach((e) => devkit_1.logger.log(e));
            }
            else {
                devkit_1.logger.error(error);
            }
        }
```
I could quick fix it locally by doing this:
```javascript
error: (s) => {
        if (typeof s === 'string' && s.startsWith('NX ')) {
            console.error(`\n${exports.NX_ERROR} ${chalk.bold(chalk.red(s.substr(3)))}\n`);
        }
        else {
            console.error(chalk.bold(chalk.red(s)));
        }
    },
```

## Expected Behavior
The logger should accept an object of type `Error` as a valid parameter.

The error message should have been this, in my case, YMMV depending on the missing dependency / executor causing the error:

> Error: Cannot find module '@storybook/manager-webpack5'
> Require stack:
> - C:\projects\wkc-web\node_modules\@storybook\core-server\dist\cjs\utils\get-manager-builder.js
> - C:\projects\wkc-web\node_modules\@storybook\core-server\dist\cjs\build-static.js
> - C:\projects\wkc-web\node_modules\@storybook\core-server\dist\cjs\index.js
> - C:\projects\wkc-web\node_modules\@storybook\core\dist\cjs\server.js
> - C:\projects\wkc-web\node_modules\@storybook\core\server.js
> - C:\projects\wkc-web\node_modules\@nrwl\storybook\src\executors\storybook\storybook.impl.js
> - C:\projects\wkc-web\node_modules\@nrwl\tao\src\shared\workspace.js
> - C:\projects\wkc-web\node_modules\@nrwl\tao\src\commands\run.js
> - C:\projects\wkc-web\node_modules\@nrwl\tao\index.js
> - C:\projects\wkc-web\node_modules\@nrwl\cli\lib\run-cli.js
>
>
>         Broken build, fix the error above.
>          You may need to refresh the browser.

## Steps to Reproduce
Run the storybook executor on a project, with missing dependencies in your package.json

### Environment
Node : 12.18.3
OS   : win32 x64
npm  : 6.14.6

nx : Not Found
@nrwl/angular : 12.5.7
@nrwl/cli : 12.5.7
@nrwl/cypress : 12.5.7
@nrwl/devkit : 12.5.7
@nrwl/eslint-plugin-nx : 12.5.7
@nrwl/express : Not Found
@nrwl/jest : 12.5.7
@nrwl/linter : 12.5.7
@nrwl/nest : 12.5.7
@nrwl/next : Not Found
@nrwl/node : 12.5.7
@nrwl/react : Not Found
@nrwl/schematics : Not Found
@nrwl/tao : 12.5.7
@nrwl/web : 12.5.7
@nrwl/workspace : 12.5.7
@nrwl/storybook : 12.5.7
@nrwl/gatsby : Not Found
typescript : 4.2.4

**Comment by FrozenPandaz** [comment]
This was actually _just_ fixed here https://github.com/nrwl/nx/pull/6320!

Can you please try upgrading to `12.5.8`?

**Comment by fdeslandes-wk** [comment]
It works.  Thanks.
