### ISSUE TITLE
New @nrwl/node:node doesn't link transitive dependencies correctly

### ISSUE THREAD

**Issue by jahumes** [nrwl/nx#9346]
## Current Behavior

After upgrading to 13.8.4, the new `@nrwl/node:node` executor is doing something to our code that is causing the linking of our transitive dependencies to not be linked correctly. An example is that we include `rxjs@7.4.0` in our application, but one of our main dependencies depends on `rxjs@5.4.3`. After the 13.8.4 version was implemented with the new version, when our node executor runs to serve our application for development, our dependency gets `rxjs@7.4.0` which immediately causes it to crash.

We spent about 6 hours digging into everything we can in our application and have figured out that the only difference between when it works and when it breaks is the upgrade of nx from 13.8.3 to 13.8.4 (quick side note, this change doesn't really abide by semantic versioning because the API changed 😄 ). Our current theory is that something is brakes when the new executor creates child processes for node applications.

## Expected Behavior

This is a regression and the expected behavior is that our dependencies' dependencies are linked correctly.

## Steps to Reproduce

I will attempt to reproduce this, but this is internal code that I can't share. Since the basic functionality is that a dependency is getting the application's version of one of its' dependencies, hopefully, this isn't too hard to reproduce.

### Failure Logs

`Possibly unhandled TypeError: rxjs_1.Observable.timer is not a function`

### Environment

```
   Node : 14.19.0
   OS   : darwin x64
   yarn : 3.2.0

   nx : 13.8.8
   @nrwl/angular : undefined
   @nrwl/cli : 13.8.8
   @nrwl/cypress : 13.8.8
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.8
   @nrwl/eslint-plugin-nx : 13.8.8
   @nrwl/express : 13.8.8
   @nrwl/jest : 13.8.8
   @nrwl/js : 13.8.8
   @nrwl/linter : 13.8.8
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.8.8
   @nrwl/nx-cloud : undefined
   @nrwl/react : 13.8.8
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.8
   @nrwl/tao : 13.8.8
   @nrwl/web : 13.8.8
   @nrwl/workspace : 13.8.8
   typescript : 4.4.4
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
```

**Comment by jahumes** [comment]
I am wondering if this is what has changed that could possibly cause this issue.

https://github.com/nrwl/nx/blob/fd645460214bfb45726f983c1ce570a4bfb4e2fe/packages/node/src/executors/node/node-with-require-overrides.ts#L1-L20

**Comment by hellivan** [comment]
https://github.com/nrwl/nx/pull/9284 should fix this issue

**Comment by FrozenPandaz** [comment]
Closed with https://github.com/nrwl/nx/pull/9284
