### ISSUE TITLE
Since 22.7.0-beta.13 there are rootDir path issues with sub packages

### ISSUE THREAD

**Issue by danielritter** [nrwl/nx#35696]
### Current Behavior

I’m working with a monorepo setup where several packages contain nested sub-packages. In these cases, the source code is located at the root of each package rather than under `src/lib`.

To accommodate this, I removed `src/` from the `include` and `exclude` fields in the TypeScript configuration. This setup was working correctly until version 22.7.0-beta.13.

Since upgrading, I’m no longer able to build these packages and now encounter the following error:

```
 error TS6059: File 'C:/path-to/development/packages/backend-nest-util-common/decorators/src/description.decorator.ts' is not under 'rootDir' '/path-to/development/packages/backend-nest-util-common'. 'rootDir' is expected to contain all source files.
```

I haven’t made any changes to the `rootDir` setting, so I’m unsure why this error is now occurring.

I have seen that there were multiple "path" changes in version 22.7.0-beta.13.

### Expected Behavior

Building packages and its sub packages without errors.

### Steps to Reproduce

1. Create new package
2. Remove `src/` from `include` and `exclude` config
3. Add a folder in package root with a `src` folder and add a `ng-package.json` file in it with:
```
{
	"lib": {
		"entryFile": "src/index.ts"
	}
}
```
4. Add code and an `index.ts` file in `src` folder
5. Add sub package path in `paths` in `tsconfig.base.json`

### Nx Report

```shell
Node           : 24.9.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 11.6.2
daemon         : Disabled

nx (global)            : 22.7.2
nx                     : 22.7.2
@nx/js                 : 22.7.2
@nx/eslint             : 22.7.2
@nx/workspace          : 22.7.2
@nx/angular            : 22.7.2
@nx/jest               : 22.7.2
@nx/cypress            : 22.7.2
@nx/devkit             : 22.7.2
@nx/eslint-plugin      : 22.7.2
@nx/module-federation  : 22.7.2
@nx/nest               : 22.7.2
@nx/node               : 22.7.2
@nx/plugin             : 22.7.2
@nx/rspack             : 22.7.2
@nx/storybook          : 22.7.2
@nx/web                : 22.7.2
@nx/webpack            : 22.7.2
@nx/docker             : 22.7.2
typescript             : 5.9.3
---------------------------------------
Registered Plugins:
@development/targets
@development/schematics
@nx/webpack/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
@compodoc/compodoc   : 1.2.1
@ng-doc/builder      : 21.0.0
@ng-icons/core       : 33.1.0
@ngrx/effects        : 21.0.1
@ngrx/entity         : 21.0.1
@ngrx/operators      : 21.0.1
@ngrx/router-store   : 21.0.1
@ngrx/schematics     : 21.0.1
@ngrx/signals        : 21.0.1
@ngrx/store          : 21.0.1
@ngrx/store-devtools : 21.0.1
@storybook/angular   : 10.2.10
angular-eslint       : 21.2.0
---------------------------------------
Local workspace plugins:
@development/schematics
---------------------------------------
Cache Usage: 21.88 KB / 372.51 GB
```

### Failure Logs

```shell
Imported via '@development/backend-nest-util-common/interfaces' from file '/path-to/development/packages/backend-nest-util-common/decorators/src/description.decorator.ts'

  /path-to/development/packages/backend-nest-util-common/mixins/src/with-description.mixin.ts:1:29
    1 import { Description } from '@development/backend-nest-util-common/decorators';
                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    File is included via import here.

 error TS6059: File 'C:/path-to/development/packages/backend-nest-util-common/decorators/src/description.decorator.ts' is not under 'rootDir' '/path-to/development/packages/backend-nest-util-common'. 'rootDir' is expected to contain all source files.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by BadMachine** [comment]
Same here

**Comment by danielritter** [comment]
@BadMachine Do you use Windows? I think the issue is because the `rootDir` is always without the drive letter, `C:` in this case, but the file contains the drive letter. I need to check the issue on a UNIX/Linux machine.

**Comment by danielritter** [comment]
@leosvelperez I investigated the issue further. My project uses barrel files, and within a package, I avoid relative imports to its subpackages—using relative imports would likely resolve the problem, as it did in this small demo project.

Here’s a minimal demo project: https://github.com/danielritter/nestjs.

I’m now checking whether the issue occurs only on Windows.

**Comment by danielritter** [comment]
I believe this issue was caused by https://github.com/nrwl/nx/pull/34965/changes.

**Comment by danielritter** [comment]
@leosvelperez @BadMachine Yes, the issue is because of Windows and the drive letter `C:`. I could run my big repository successfully on a mac machine. The issues didn't occur there.

```
packages/backend-nest-util-common/types/src/index.ts:4:15 - error TS6059: File 'C:/dev/path/to/development/packages/backend-nest-util-common/types/src/primary-generated-id.type.ts' is not under 'rootDir' '/dev/path/to/development/packages/backend-nest-util-common'. 'rootDir' is expected to contain all source files.

4 export * from './primary-generated-id.type';
```

There is a dismatch with `C:`, and occurs only on Windows.

**Comment by danielritter** [comment]
@FrozenPandaz @leosvelperez Reproduction was given here: https://github.com/nrwl/nx/issues/35696#issuecomment-4719058539. Please unstale it. 
@leosvelperez  Is there a way how we can build and test your fix on a Windows machine?

**Comment by lppedd** [comment]
@FrozenPandaz wondering if it's still possible to backport to the 22.7.x branch. It will take a while for us to migrate to 23.

Otherwise I'll patch it myself with `patch-package`.

**Comment by lppedd** [comment]
Note that this apparently also affected what is outputted to the terminal (e.g., in case of error). Transitively, AI tools like Copilot were mistakenly pointing to non-existing paths, requesting permissions to edit "out of workspace" files, and so on.
