### ISSUE TITLE
Angular 16.0.0-rc.1 : TypeError: validator is not a function

### ISSUE THREAD

**Issue by yjaaidi** [nrwl/nx#16368]
### Current Behavior

On an Nx 15.9.2 repo, after upgrading Angular to 16.0.0-rc.1 using 
```sh
nx migrate @angular/cli@next
nx migrate @angular/core@next
```

I stumbled upon the following error when running `nx build my-app`

```
TypeError: validator is not a function
    at /.../node_modules/@angular-devkit/architect/src/jobs/simple-scheduler.js:219:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

After some investigation, I noticed that this error happens because `@angular-devkit/architect` version here is 16.0.0-rc.0 while `@angular-devkit/core` is 15.2.6.
Using `yarn why @angular-devkit/core` I noticed that the hoisted version of the package is `16.0.0-rc.0` which is shadowed by a `15.2.6` version in `node_modules/nx/node_modules/@angular-devkit/core`

Cf. yarn why output
<img width="778" alt="yarn-why" src="https://user-images.githubusercontent.com/2674658/232778773-30336467-5ea4-41ba-9798-3eaa1672e962.png">

How is that possible?
Is it because Nx depends on RxJS which depends on @angular-devkit/schematics?

### Expected Behavior

no error

### Steps to Reproduce

TODO: I'll add this as soon as I can

### Nx Report

```shell
TODO: I'll add this as soon as I can
```

**Comment by yjaaidi** [comment]
Oups! My bad!

I had the following Yarn PnP configuration which is probably the culprit:

```yaml
packageExtensions:
  'nx@*':
    dependencies:
      '@angular-devkit/core': '*'
```

I needed this previously otherwise Nx couldn't import `@angular-devkit/core` which is imported lazily I guess depending on project's config without being in Nx dependencies.

**Comment by dennisluitwieler** [comment]
We are also running into the same error, but:

- we're currently still running Angular & NX 15. 
- we don't use yarn but npm

Our package.json imports `@angular-devkit/core` simply like this:
`"@angular-devkit/core": "15.2.8",`
And we have no libraries that are already on Angular/NX 16

Our problem started when we installed the devkit to create a generator.
The stacktrace we see is the same as the original poster.

Not sure where to start looking for the cause of this problem.

**Comment by pixtim** [comment]
@dennisluitwieler 

I also encountered this problem when upgrading an Nx Angular project from 14 to 15. I did the upgrade using `nx migrate` with Nx 15 local.

It seems that the code failing in `simple-scheduler.js` is related to a mismatching expectation how the validator is invoked. In `node_modules/@angular-devkit/architect/package.json` I noticed an Angular 16 `@angular-devkit/architect@0.1600.1` was installed (even though I am not using Angular 16).

I added NPM `overrides` configuration to force the transitive dependency to align with Angular 15:
```json
{
  "overrides": {    
    "@angular-devkit/architect": "^0.1502.8"
  }
}
```

The `TypeError: validator is not a function` error was resolved when using the correct architect package.
