### ISSUE TITLE
Workspace Schematics throw an error after migrating to v11

### ISSUE THREAD

**Issue by s4m0r4m4** [nrwl/nx#4853]
## Current Behavior
When I try to run a schematic:
`nx workspace-schematic my-component --name=test --project=ui`

It throws the following error:
```
error TS18003: No inputs were found in config file 'C:/Development/greenatlas/tools/tsconfig.generated.json'. Specified 'include' paths were '["C:\\Development\\greenatlas\\tools\\generators\\**\\*.ts"]' and 'exclude' paths were '["../node_modules","../tmp"]'.
```

## Expected Behavior
In nx v10, this worked just fine. I'd expect vanilla angular schematics to run just fine in nx 11.

## Steps to Reproduce
I tried to make a reproduction from the nx-examples repo: https://github.com/s4m0r4m4/nx-examples
However, whenever I try to run _any_ workspace schematic it fails with `'yarn' is not recognized as an internal or external command, operable program or batch file.`. That's not my problem, it must be some issue with the nx-examples repo (unless I need to have yarn installed globally as a prerequisite for using nx, which I did not believe was the case...)
1. The command to run the custom schematic, which worked before, is: `nx workspace-schematic aim-component --name=asdfasdf --project=cart` (I just picked a random project).

### Failure Logs
See above error.

### Environment
```
  Node : 14.15.3
  OS   : win32 x64
  npm  : 6.14.9
  
  nx : Not Found
  @nrwl/angular : 11.0.20
  @nrwl/cli : 11.0.20
  @nrwl/cypress : 11.0.20
  @nrwl/devkit : 11.0.20
  @nrwl/eslint-plugin-nx : 11.0.20
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.20
  @nrwl/linter : 11.0.20
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.20
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.20
  typescript : 4.0.5```

**Comment by vsavkin** [comment]
Thank you for submitting the issue! 

You have to have yarn installed if the repo uses yarn, which the nx-examples repo does. Nx detects it by seeing the yarn.lock file. So you can remove the yarn.lock file and run npm install. This will create a package-lock.json file, and then you can create a repro.

Could you provide a repro given the instructions above? 

Thank you!

**Comment by s4m0r4m4** [comment]
Thanks for the quick reply! I did as you said and committed the update to my repo.

When I run this command:

`nx workspace-schematic aim-class --name=test --project=cart --dry-run`

I get this error:

`error TS18003: No inputs were found in config file 'C:/Development/nx-examples/tools/tsconfig.generated.json'. Specified 'include' paths were '["C:\\Development\\nx-examples\\tools\\generators\\**\\*.ts"]' and 'exclude' paths were '["../node_modules","../tmp"]'.`

**Comment by s4m0r4m4** [comment]
Update: I've been able to get it to work in the following setup (from nx report):
```
  nx : Not Found
  @nrwl/angular : 10.4.4
  @nrwl/cli : 10.4.4
  @nrwl/cypress : 10.4.4
  @nrwl/eslint-plugin-nx : 10.4.4
  @nrwl/express : Not Found
  @nrwl/jest : 10.4.4
  @nrwl/linter : 10.4.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.4.4
  @nrwl/web : Not Found
  @nrwl/workspace : 10.4.4
  typescript : 4.0.7
```
My hunch is that something didn't go right with the upgrade to v11. Let me try that again and see what happens.

**Comment by s4m0r4m4** [comment]
After running the upgrade from v10 to v11 and doing the migrations again, everything seems to be working. We can close this out, sorry for the hassle.
