### ISSUE TITLE
Unable to resolve @nx/webpack:webpack

### ISSUE THREAD

**Issue by AM-77** [nrwl/nx#18872]
### Current Behavior

after migrating from v14.5.5 to v16.7.4, I tried to run the nest app that I already created with nx v14 I got this error

```
> nx run api:serve

>  NX   Unable to resolve @nx/webpack:webpack.

Cannot find module '@nx/webpack/package.json'
```

### Expected Behavior

expect the nest app to be started

```
[Nest] 73446  - 08/28/2023, 11:19:25 PM     LOG [NestApplication] Nest application successfully started +2ms
[Nest] 73446  - 08/28/2023, 11:19:25 PM     LOG 🚀 Application is running on: http://localhost:3001/api
```

### Steps to Reproduce

1. nx migrate latest
2. npm install
3. nx migrate --run-migrations
4. npm run start

### Nx Report

```shell
Node   : 16.20.1
   OS     : linux-x64
   npm    : 8.19.4
   
   nx                 : 16.7.4
   @nx/js             : 16.7.4
   @nx/jest           : 16.7.4
   @nx/linter         : 16.7.4
   @nx/workspace      : 16.7.4
   @nx/cypress        : 16.7.4
   @nx/devkit         : 16.7.4
   @nx/eslint-plugin  : 16.7.4
   @nx/nest           : 16.7.4
   @nx/next           : 16.7.4
   @nx/node           : 16.7.4
   @nx/playwright     : 16.7.4
   @nx/react          : 16.7.4
   @nrwl/tao          : 16.7.4
   @nx/vite           : 16.7.4
   @nx/web            : 16.7.4
   nx-cloud           : 16.3.0
   typescript         : 5.1.6
```

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Installing `@nrwl/webpack` by running `npm i -D @nrwl/webpack` seems to fix the issue.

**Comment by AgentEnder** [comment]
It looks possible that a migration was missed that should have installed `@nx/webpack` (not `@nrwl/webpack`), see: https://nx.dev/recipes/other/rescope

I'm not sure why that migration was missed, but the fix is just to install the package.
