### ISSUE TITLE
19.8.x (0 , native_1.connectToNxDb) is not a function

### ISSUE THREAD

**Issue by gregroyal** [nrwl/nx#28205]
### Current Behavior

any version 19.8.0 and higher completely breaks NX for me

### Expected Behavior

to work as normal

### Steps to Reproduce

1. after upgrading from 19.7 to 19.8, it breaks when running **nx run** commands

### Nx Report

```shell
Node           : 20.12.2
OS             : linux-x64
Native Target  : wasm32
pnpm           : 8.15.3

nx (global)  : 19.8.2
nx           : 19.8.2
```

### Failure Logs

```shell
NX   (0 , native_1.connectToNxDb) is not a function

TypeError: (0 , native_1.connectToNxDb) is not a function
    at myRepo/node_modules/.pnpm/nx@19.8.2/node_modules/nx/src/utils/db-connection.js:11:93
    at getEntryOrSet (myRepo/node_modules/.pnpm/nx@19.8.2/node_modules/nx/src/utils/db-connection.js:19:17)
    at getDbConnection (myRepo/node_modules/.pnpm/nx@19.8.2/node_modules/nx/src/utils/db-connection.js:11:24)
    at new TaskHistory (myRepo/node_modules/.pnpm/nx@19.8.2/node_modules/nx/src/utils/task-history.js:11:91)
    at getTaskHistory (myRepo/node_modules/.pnpm/nx@19.8.2/node_modules/nx/src/utils/task-history.js:48:23)
    at new TasksSchedule (myRepo/node_modules/.pnpm/nx@19.8.2/node_modules/nx/src/tasks-runner/tasks-schedule.js:16:62)
    at new TaskOrchestrator (myRepo/node_modules/.pnpm/nx@19.8.2/node_modules/nx/src/tasks-runner/task-orchestrator.js:32:30)
    at runAllTasks (myRepo/node_modules/.pnpm/nx@19.8.2/node_modules/nx/src/tasks-runner/default-tasks-runner.js:59:26)
    at defaultTasksRunner (myRepo/node_modules/.pnpm/nx@19.8.2/node_modules/nx/src/tasks-runner/default-tasks-runner.js:51:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Package Manager Version

pnpm 8.15.3 AND 9.11.0 (tried both)

### Operating System

- [ ] macOS
- [X] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

no troubleshooting help. I'm just stuck

**Comment by gregroyal** [comment]
also opened a thread on discord, but no answers https://discord.com/channels/1143497901675401286/1290341387895570535

**Comment by mjmarianetti** [comment]
I had to go back to 19.8.0 and the problem is no longer there. Also tried adding to `nx.json`
```
"neverConnectToCloud": true,
```

**Comment by jlanng** [comment]
is there a workaround?

**Comment by vdhpieter** [comment]
I think this is not an NX problem but an NPM problem. Sometimes optional dependencies used for native code disappear from the `package-lock.json` (except the ones you need on your local computer). To add them back my workaround is:

1. Look for all optional dependencies by looking through the package-lock for `darwin-arm64` or `darwin-x64` (it's easier if you look for the one that is not installed anymore)
2. for all lists of optional dependencies you find that way copy the full list and add them to the optional dependencies in your `package.json`
3. run `npm install`
4. remove all those optional dependencies again from your `package.json`
5. run `npm install` again
6. see that your `package-lock.json` still is edited with all optional dependencies added again

Hope this works for you as well!

**Comment by bmvantunes** [comment]
After lots of debugging found the error on our machines.

For us the error was caused by NX trying to copy the "native files" into a temp folder, but our users didn't have permissions to write on /tmp/** 

**Solution**: Set TMPDIR environment variable (Linux) to something your users have permissions to write to. Usually something in your home directly should do the trick.

The line were NX copies the "native files" from the temp folder (in our case the folder+file didn't exist) and from that point everything went bad: https://github.com/nrwl/nx/blob/ec801b4c16896c601e536444fd3032baca100de1/packages/nx/src/native/index.js#L81

Because that file didn't exist, later in code the "Native Target" rather than being "x86_64-linux" was "wasm32" (both running npx nx reset and npx nx report)

Question for NX team: Any reason NX copies the binaries to a temp folder rather than using it directly from node_modules?

I was lucky to have 2 machines where one was working and the other was getting this error, otherwise it would have been pretty hard to find a solution.

**Comment by gregroyal** [comment]
oh man! i've been dealing with the wasm thing for months. This fixed it. thanks!!!

upgrading worked after setting this env

**Comment by BleedingDev** [comment]
I meet same error, but in Vercel, here's the error:
```bash
TypeError: (0 , native_1.connectToNxDb) is not a function
    at /vercel/path0/node_modules/nx/src/utils/db-connection.js:11:93
    at getEntryOrSet (/vercel/path0/node_modules/nx/src/utils/db-connection.js:19:17)
    at getDbConnection (/vercel/path0/node_modules/nx/src/utils/db-connection.js:11:24)
    at new TaskHistory (/vercel/path0/node_modules/nx/src/utils/task-history.js:11:91)
    at getTaskHistory (/vercel/path0/node_modules/nx/src/utils/task-history.js:48:23)
    at new TasksSchedule (/vercel/path0/node_modules/nx/src/tasks-runner/tasks-schedule.js:16:62)
    at new TaskOrchestrator (/vercel/path0/node_modules/nx/src/tasks-runner/task-orchestrator.js:33:30)
    at runAllTasks (/vercel/path0/node_modules/nx/src/tasks-runner/default-tasks-runner.js:59:26)
    at defaultTasksRunner (/vercel/path0/node_modules/nx/src/tasks-runner/default-tasks-runner.js:51:22)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Command "npx nx build coursition --prod --verbose --skip-nx-cache" exited with 1
```

I have Nx v19.8.4. Trying to update to 20.

**Comment by origxm** [comment]
Same here.

Tried to migrate to the latest version 20.0.6.

Any update on this?

**Comment by jdnichollsc** [comment]
Same issue here with a Nx repo using @nx/nest and @nx/remix

**Comment by gcode-yunex** [comment]
Also encountered this issue but on an earlier version of NX (19.6.0)

I was also able to use the `NX_DISABLE_DB=true` environment variable to workaround the problem, as captured below.

Am not able to capture a report am continuing to investigate.

```
D:\workspace\utc1\webui\client\utc>npm run build:login

> utc@0.0.0 build:login
> nx run-many --target=build --projects=login --base-href=. --verbose


 NX   (0 , native_1.connectToNxDb) is not a function

TypeError: (0 , native_1.connectToNxDb) is not a function
    at D:\workspace\utc1\webui\client\utc\node_modules\nx\src\utils\db-connection.js:11:93
    at getEntryOrSet (D:\workspace\utc1\webui\client\utc\node_modules\nx\src\utils\db-connection.js:19:17)
    at getDbConnection (D:\workspace\utc1\webui\client\utc\node_modules\nx\src\utils\db-connection.js:11:24)
    at getTaskDetails (D:\workspace\utc1\webui\client\utc\node_modules\nx\src\hasher\hash-task.js:19:84)
    at invokeTasksRunner (D:\workspace\utc1\webui\client\utc\node_modules\nx\src\tasks-runner\run-command.js:367:56)
    at runCommandForTasks (D:\workspace\utc1\webui\client\utc\node_modules\nx\src\tasks-runner\run-command.js:117:31)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async D:\workspace\utc1\webui\client\utc\node_modules\nx\src\tasks-runner\run-command.js:105:29
    at async handleErrors (D:\workspace\utc1\webui\client\utc\node_modules\nx\src\utils\handle-errors.js:9:24)
    at async runCommand (D:\workspace\utc1\webui\client\utc\node_modules\nx\src\tasks-runner\run-command.js:104:20)


D:\workspace\utc1\webui\client\utc>SET NX_DISABLE_DB=true

D:\workspace\utc1\webui\client\utc>npm run build:login

> utc@0.0.0 build:login
> nx run-many --target=build --projects=login --base-href=. --verbose


 NX   Running target build for project login and 12 tasks it depends on:
```

**Comment by samarpanda** [comment]
> I was able to get this to work in our CI environment by setting: `NX_DISABLE_DB=true`

This is perfect. It worked for me 👍
