### ISSUE TITLE
Add native module support for riscv64

### ISSUE THREAD

**Issue by anonymouscowhead** [nrwl/nx#20914]
- [ ] I'd be willing to implement this feature ([contributing guide](https://github.com/nrwl/nx/blob/master/CONTRIBUTING.md))

## Description
I'd like to no longer see "Error: Cannot find module '@nx/nx-linux-riscv64-gnu'" when I try to build Arduino IDE on a riscv64 SBC.

## Motivation
Cheap riscv boards capable of running linux are now hitting the market such as Star64, Lichee Pi 4a, BeagleV.  One of the most popular use cases will involve further software dev on the board itself.

## Suggested Implementation
At this point, I'm clueless as to how a native module would be added, besides understanding that riscv64 is an architecture that has a lot in common with arm64.

**Comment by bitsk** [comment]
Hi@anonymouscowhead,  I have successfully built the yarn package containing nx.linux-riscv64-gnu.node, and it works very well,  unfortunately, the arduino ide still has many other dependency packages that do not support the riscv architecture, and there is still a lot of work to do. 
[nx-19.5.4.zip](https://github.com/user-attachments/files/16454114/nx-19.5.4.zip)

**Comment by bitsk** [comment]
build on Ubuntu 24.04 x64
