### ISSUE TITLE
Nx tsconfig paths alias resolution is not working as expected

### ISSUE THREAD

**Issue by Diboby** [nrwl/nx#28945]
### Current Behavior

Hello !

The `@nx/vite/plugins/nx-tsconfig-paths.plugin` path resolution is not working as expected.

I think the first tsconfig is supposed to be the project tsconfig (https://github.com/nrwl/nx/blob/master/packages/vite/plugins/nx-tsconfig-paths.plugin.ts#L117) but in my case, it resolves to the tsconfig under the workspace root foder.

![Image](https://github.com/user-attachments/assets/396ab876-6595-4748-baf3-f1ffed8721e9)

### Expected Behavior

I think the first tsconfig is supposed to be the project tsconfig (https://github.com/nrwl/nx/blob/master/packages/vite/plugins/nx-tsconfig-paths.plugin.ts#L117) but in my case, it resolves to the tsconfig under the workspace root foder.

### GitHub Repo

https://github.com/nrwl/nx/blob/master/packages/vite/plugins/nx-tsconfig-paths.plugin.ts#L117

### Steps to Reproduce

1. root tsconfig

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "rootDir": ".",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "module": "esnext",
    "lib": ["es2020", "dom"],
    "skipLibCheck": true,
    "skipDefaultLibCheck": true,
    "baseUrl": ".",
    "paths": {}
  },
  "exclude": ["node_modules", "tmp"]
}
```

2. project tsconfig

```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "allowJs": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "types": ["vite/client", "vitest"],
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "files": [],
  "include": [],
  "references": [
    {
      "path": "./tsconfig.app.json"
    },
    {
      "path": "./tsconfig.spec.json"
    }
  ],
  "extends": "../../tsconfig.base.json"
}

```

### Nx Report

```shell
Node           : 20.17.0
OS             : darwin-x64
Native Target  : x86_64-macos
npm            : 10.8.2

nx                 : 20.0.3
@nx/js             : 20.0.3
@nx/jest           : 20.0.3
@nx/eslint         : 20.0.3
@nx/workspace      : 20.0.3
@nx/cypress        : 20.0.3
@nx/devkit         : 20.0.3
@nx/eslint-plugin  : 20.0.6
@nx/react          : 20.0.3
@nx/vite           : 20.0.3
@nx/web            : 20.0.3
typescript         : 5.6.3
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/cypress/plugin
@nx/jest/plugin
---------------------------------------
```

### Failure Logs

```shell
[Nx Vite TsPaths] Resolved @/contexts to undefined
```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by zargham-leanix** [comment]
facing the same issue while setting up `@nx/vite:test` for angular.

**Comment by ram95krishh** [comment]
Facing the same issue with executor @nx/jest:jest.. `nx run test` works fine from rootDir/frontend folder. But resolves modules incorrectly when run from the root folder. Always off by one `../` folder extra. Added module aliases in tsconfig.json, added moduleNameMapper to jest.config.js. No luck.

My frontend/jest.config.js file:
```
const path = require('path');

module.exports = {
  collectCoverage: true,
  collectCoverageFrom: [
    "2.0/**/**/*.{ts,tsx}",
    "!**/node_modules/**",
    "!**/vendor/**"
  ],
  coverageDirectory: 'coverage', // Output directory for coverage reports
  coverageReporters: ['html', 'text'], // Generate HTML and text coverage reports
  reporters: [
    'default'
  ],
  preset: 'react-native',
  transform: {
    '^.+\\.tsx?$': 'babel-jest',
  },
  rootDir: path.resolve(__dirname),
  roots: ['<rootDir>/2.0'], // Only look for tests inside the 2.0 folder
  testMatch: ['**/?(*.)+(spec|test).ts?(x)'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json'],
  moduleNameMapper: {
    '^~/(.*)$': '<rootDir>/src/$1',
    '^2\\.0/(.*)$': '<rootDir>/2.0/$1',
  }
};

console.log('Jest rootDir:', path.resolve(__dirname)); // prints `rootDir/frontend` as expected
```
My frontend/tsconfig.json
```
{
  "extends": "@react-native/typescript-config/tsconfig.json",
  "baseUrl": ".",
  "compilerOptions": {
    "noEmit": true,
    "paths": {
      "2.0/*": ["./2.0/*"],
      "~/*": ["./src/*"]
    }
  },
  "include": ["./src/**/*", "./2.0/**/*"]
}

```

Like mentioned by @Diboby it is incorrectly mapping modules with respect to root directory and not from my frontend folder. Unlike his issue, I don't even have a rootDir/tsconfig.json file.

When I run a spec in `2.0/components/typography/heading-text.spec.tsx`
It gives this error 
```
Cannot find module '../../../../2.0/core/utils' from '2.0/components/typography/heading-text.spec.tsx'
// when it should be looking instead for `../../../2.0/core/utils`
```

**Comment by mc-julian** [comment]
For me it worked to move the

"extends": "../../tsconfig.base.json",

to

"references": [ { "path": "../../tsconfig.base.json" } ],
inside the tsconfig.json.

Can someone answer if this is an official workaround?

**Comment by everythinginjs** [comment]
+1
[the goes here](https://github.com/nrwl/nx/issues/29320)

**Comment by Lonli-Lokli** [comment]
Probably my issue related too https://github.com/nrwl/nx/issues/29998

**Comment by Coly010** [comment]
@Diboby Can you provide a repo with a minimal reproduction so that I can investigate this further?

**Comment by valenttur** [comment]
@Coly010 
I think I have the same problem.
Here is a minimal reproduction repository

I downgraded the nx version to 19.5.7 because the following ones do not work for me. both 19.8.14 and ^20

https://github.com/valenttur/nx-bug-paths-reproduction

**Comment by valenttur** [comment]
I wonder if this is a problem with the "external" option.

warning when build with @nx/js:tsc 19.5.7
> Option "external" is deprecated: Make sure all dependencies are buildable by running `nx g @nx/js:setup-build`. This option will be removed in Nx 20.

**Comment by Coly010** [comment]
@claude please analyze this and make a suggestion what the root cause could be

**Comment by Coly010** [comment]
@claude your analysis looks good. Can you make a PR and fix this using the recommended option 1 using `getProjectTsConfigPath` as a fallback. Make sure the path to the projectRoot is correct and in the format required, using `join` if needed.
