### ISSUE TITLE
Angular workspace to nx workspace transform error after upgrade nx from 12.4 to 12.5

### ISSUE THREAD

**Issue by gdznela** [nrwl/nx#6290]
## Current Behavior

Running `ng add @nrwl/workspace` from angular 12 workspace with single project results in error:
```
An unhandled exception occurred: Cannot find module 'prettier'
Require stack:
- C:\nx-test\test\node_modules\@nrwl\workspace\src\utilities\prettier.js
- C:\nx-test\test\node_modules\@nrwl\workspace\src\generators\init\init.js
- C:\nx-test\test\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\nx-test\test\node_modules\@angular-devkit\schematics\tools\index.js
- C:\nx-test\test\node_modules\@angular\cli\utilities\json-schema.js
- C:\nx-test\test\node_modules\@angular\cli\models\command-runner.js
- C:\nx-test\test\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\user\AppData\Local\Temp\ng-GdAyEH\angular-errors.log" for further details.
```
## Expected Behavior

Angular workspace should be transfomed to nx workspace

## Steps to Reproduce

1. Create new empty angular application using ng cli (12.1.1) 
`ng new test`
2. Run `ng add @nrwl/workspace` (latest, 12.5.7)
Error is displayed after installing @nrwl/workspace@12.5.7 package

With nx 12.4 version everything works.
### Failure Logs

C:\Users\user\AppData\Local\Temp\ng-GdAyEH\angular-errors.log:
```
[error] Error: Cannot find module 'prettier'
Require stack:
- C:\nx-test\test\node_modules\@nrwl\workspace\src\utilities\prettier.js
- C:\nx-test\test\node_modules\@nrwl\workspace\src\generators\init\init.js
- C:\nx-test\test\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\nx-test\test\node_modules\@angular-devkit\schematics\tools\index.js
- C:\nx-test\test\node_modules\@angular\cli\utilities\json-schema.js
- C:\nx-test\test\node_modules\@angular\cli\models\command-runner.js
- C:\nx-test\test\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\user\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (C:\nx-test\test\node_modules\@nrwl\workspace\src\utilities\prettier.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
```
### Environment

```
  Node : 14.17.1
  OS   : win32 x64
  npm  : 6.14.13

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.5.7
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.5.7
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 12.5.7
  @nrwl/linter : 12.5.7
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.5.7
  @nrwl/web : Not Found
  @nrwl/workspace : 12.5.7
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```
