### ISSUE TITLE
Generate App: "Cannot find module '@schematics/angular/strings'"

### ISSUE THREAD

**Issue by Springrbua** [nrwl/nx#273]
I updated my project to use @angular/cli version 1.7.0, since it should fix #250 according to [this comment](https://github.com/nrwl/nx/issues/140#issuecomment-365470665).  
Howevery, when I now execute a command like `ng g app my-app` I get the error `Cannot find module '@schematics/angular/strings'` .  

Versions:
```
Angular CLI: 1.7.0
Node: 8.5.0
OS: win32 x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

@angular/cdk: 5.2.1
@angular/cli: 1.7.0
@angular/flex-layout: 2.0.0-beta.12
@angular/material: 5.2.1
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.6.2
webpack: 3.11.0
```

I also have `@nrwl/schematics` Version 0.7.3 installed.  

I have seen #92, however that issue is only talking about the creation of a new workspace, which I have already done.

**Comment by vsavkin** [comment]
The current version of Nx only works with CLI 1.6.5, or to be more precise, it only work with this patched version of 1.6.5 (see here: https://github.com/nrwl/nx/wiki/FAQ). We are planning to release Nx 0.8 soon, which will include CLI 1.7.
