### ISSUE TITLE
Migration from 14.8.1 to 14.8.2 makes our libs unbuildable with "is not under 'rootDir'" errors

### ISSUE THREAD

**Issue by ziacik** [nrwl/nx#12346]
## Current Behavior
After migration from 14.8.1 to 14.8.2, libraries that import from other libraries start showing errors like this:

```
Compiling TypeScript files for project "common"...
libs/common/src/lib/Resco/bindingList/asyncBindingList.ts:1:20 - error TS6059: File '/home/kolik/Workspaces/resco2/web-projects-nx/libs/logger/src/index.ts' is not under 'rootDir' 'libs/common'. 'rootDir' is expected to contain all source files.

1 import logger from "@resconet/logger";
                     ~~~~~~~~~~~~~~~~~~
libs/logger/src/index.ts:1:34 - error TS6059: File '/home/kolik/Workspaces/resco2/web-projects-nx/libs/logger/src/lib/customExLog.ts' is not under 'rootDir' 'libs/common'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via "./lib/customExLog" from file '/home/kolik/Workspaces/resco2/web-projects-nx/libs/logger/src/index.ts'
    Imported via "./customExLog" from file '/home/kolik/Workspaces/resco2/web-projects-nx/libs/logger/src/lib/loggerCore.ts'
```

After reverting to 14.8.1, the lib builds OK.

## Expected Behavior
To build without errors.

### Environment

```bash
   NX   Report complete - copy this into the issue template

   Node : 16.17.1
   OS   : linux x64
   npm  : 8.16.0
   
   nx : 14.8.2
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.8.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.2
   @nrwl/js : 14.8.2
   @nrwl/linter : 14.8.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.8.2
   @nrwl/react-native : Not Found
   @nrwl/rollup : 14.8.2
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.2
   @nrwl/web : 14.8.2
   @nrwl/webpack : 14.8.2
   @nrwl/workspace : 14.8.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by skrtheboss** [comment]
Should be related to https://github.com/nrwl/nx/issues/12338

**Comment by mgrejanin** [comment]
Same issue here. It works locally but not in CircleCi.

**Comment by mkaufmaner** [comment]
This broke for me, reverting to 14.8.1 solved my problem.

**Comment by starfish719** [comment]
When I exec remove Nx cache, solved CI.

```
rm -rf ./node_modules/.cache/nx
```

**Comment by gentobi** [comment]
> Can you check in 14.8.3? I think this may be resolved.

It's works for me 🙌

**Comment by ziacik** [comment]
> Can you check in 14.8.3? I think this may be resolved.

Seems to be working now. Thanks!
