### ISSUE TITLE
Collecting secondary entry points causes error in some cases

### ISSUE THREAD

**Issue by rathpc** [nrwl/nx#28139]
### Current Behavior

As a result of the change introduced in https://github.com/nrwl/nx/pull/27999, there are some cases where the start operation simply fails with the following error:

```shell
 NX   exportOptions?.default?.search is not a function
```

I believe this is due to [the following line](https://github.com/nrwl/nx/pull/27999/files/ab2052e7bd92505487f7db692d43bb611ede7aef#diff-799ced2c00fa97867840b85f0eefd12db170e63997e6ebb4b98001b988ebb70fR118), which is not optionally chaining the actual call to the search function.

If we change this:

```ts
if (exportOptions?.['default']?.search(/\.(js|mjs|cjs)$/)) {
```

**to this:**

```ts
if (exportOptions?.['default']?.search?.(/\.(js|mjs|cjs)$/)) {
```

 then the error is no longer present.
 
 For further detail, the libraries I have found which cause this error to happen in my workspace are: `axios`, `clsx`, `dexie` and `zustand`. Although I am sure there are many others that suffer from this same issue.

### Expected Behavior

To be able to run module federation locally without any errors.

### Steps to Reproduce

1. Have a module federation (react) workspace with a host and several remotes.
2. Install one of the 4 libraries I mentioned and make sure to use them in one of the remote apps
3. Run start on the host with 2 remotes also running as dev servers
4. You should see the error come up and the start process fail.

### Nx Report

```shell
nx report

 NX   Report complete - copy this into the issue template

Node           : 20.16.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 8.15.9

nx (global)        : 19.8.0
nx                 : 19.8.0
@nx/js             : 19.8.0
@nx/jest           : 19.8.0
@nx/eslint         : 19.8.0
@nx/workspace      : 19.8.0
@nx/cypress        : 19.8.0
@nx/devkit         : 19.8.0
@nx/esbuild        : 19.8.0
@nx/eslint-plugin  : 19.8.0
@nx/express        : 19.8.0
@nx/node           : 19.8.0
@nx/playwright     : 19.8.0
@nx/plugin         : 19.8.0
@nx/react          : 19.8.0
@nx/storybook      : 19.8.0
@nx/web            : 19.8.0
@nx/webpack        : 19.8.0
typescript         : 5.5.4
```

### Package Manager Version

pnpm 8.15.9

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

There have been several performance issues as well relating to the introduction of the module-federation/enhanced package especially if you are trying to run more than 2 dev remotes in addition to your host. This has made it very hard to upgrade beyond `19.4.4` aside from the issue mentioned above.

**Comment by el-davo** [comment]
Same issue - https://github.com/nrwl/nx/issues/28129. Would be good to get this one fixed as its blocking our upgrade

**Comment by Coly010** [comment]
Closing as duplicate of #28129
