### ISSUE TITLE
Migration to v20 missing @nx/linter

### ISSUE THREAD

**Issue by DaSchTour** [nrwl/nx#28363]
### Current Behavior

After migration to v20 and running `nx affected:lint` it fails with `Cannot find module '@nx/linter/package.json'`

### Expected Behavior

The migration checks if `@nx/linter` is installed as it worked without a direct dependency and does not work now. Or maybe some package should have `@nx/linter` as a dependency.

### Steps to Reproduce

1. Create a NX workspace with an old version
2. Do migrations without installing @nx/linting explicitly

### Nx Report

Node           : 20.17.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.8.2

nx                 : 20.0.0
@nx/js             : 20.0.0
@nx/jest           : 20.0.0
@nx/eslint         : 20.0.0
@nx/workspace      : 20.0.0
@nx/angular        : 20.0.0
@nx/cypress        : 20.0.0
@nx/devkit         : 20.0.0
@nx/eslint-plugin  : 20.0.0
@nx/plugin         : 20.0.0
@nx/storybook      : 20.0.0
@nx/web            : 20.0.0
@nx/webpack        : 20.0.0
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
---------------------------------------
Community plugins:
@ngneat/hot-toast     : 6.1.0
@ngneat/spectator     : 19.0.0
@ngrx/component       : 18.0.2
@ngrx/component-store : 18.0.2
@ngrx/effects         : 18.0.2
@ngrx/entity          : 18.0.2
@ngrx/eslint-plugin   : 18.0.2
@ngrx/operators       : 18.0.1
@ngrx/router-store    : 18.0.2
@ngrx/schematics      : 18.0.2
@ngrx/store           : 18.0.2
@ngrx/store-devtools  : 18.0.2
@storybook/angular    : 8.3.5
apollo-angular        : 7.2.0
ng-mocks              : 14.13.1
ngx-build-plus        : 18.0.0

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by tobenna** [comment]
linter has been renamed to https://www.npmjs.com/package/@nx/eslint

**Comment by xiongemi** [comment]
as mentioned above, it has been renamed and there is a migration script to do it: https://github.com/nrwl/nx/blob/master/packages/eslint/src/migrations/update-17-0-0-rename-to-eslint/update-17-0-0-rename-to-eslint.ts.
if you have not run this migration script:
- do a search and replace `@nx/linter` with `@nx/eslint`
- then search and replace `@nx/eslint:eslint` with `@nx/eslint:lint`

**Comment by DaSchTour** [comment]
> as mentioned above, it has been renamed and there is a migration script to do it: https://github.com/nrwl/nx/blob/master/packages/eslint/src/migrations/update-17-0-0-rename-to-eslint/update-17-0-0-rename-to-eslint.ts. if you have not run this migration script:
> 
> * do a search and replace `@nx/linter` with `@nx/eslint`
> * then search and replace `@nx/eslint:eslint` with `@nx/eslint:lint`

Yeah, the issue probably was, that the migration was only run on 95% of the project.
