### ISSUE TITLE
After migration to 19.1.0 -> findCacheDirectory is not a function

### ISSUE THREAD

**Issue by bstrob** [nrwl/nx#26235]
### Current Behavior

After migrating to Nx 19.1.0 we are getting the following error (on my local machine, as well in our Jenkins pipeline):

> findCacheDirectory is not a function

See below for stack trace.

### Expected Behavior

Lib will be successfully build 

### Steps to Reproduce

I migrated our workspace with the following command to stay on Angular 16:

```
nx migrate @nx/workspace@19 --to="@angular/animations@16.2.12,@angular/cdk@16.2.6,@angular/common@16.2.12,@angular/compiler@16.2.12,@angular/core@16.2.12,@angular/forms@16.2.12,@angular/platform-browser@16.2.12,@angular/platform-browser-dynamic@16.2.12,@angular/router@16.2.12,@angular-devkit/build-angular@16.2.4,@angular-devkit/core@16.2.4,@angular-devkit/schematics@16.2.4,@angular-eslint/eslint-plugin@16.0.3,@angular-eslint/eslint-plugin-template@16.0.3,@angular-eslint/template-parser@16.0.3,@angular/cli@16.2.0,@angular/compiler-cli@16.2.12,@angular/language-service@16.2.12,@ngrx/effects@16.3.0,@ngrx/router-store@16.3.0,@ngrx/store@16.3.0,@ngrx/schematics@16.3.0,@ngrx/store-devtools@16.3.0,ng-packagr@16.2.3,zone.js@0.13.3,typescript@5.1.6"
```

### Nx Report

```shell
+ npx nx report

 NX   Report complete - copy this into the issue template

Node   : 20.13.1
OS     : linux-x64
npm    : 10.5.2

nx                 : 19.1.0
@nx/js             : 19.1.0
@nx/jest           : 19.1.0
@nx/linter         : 19.1.0
@nx/eslint         : 19.1.0
@nx/workspace      : 19.1.0
@nx/angular        : 19.1.0
@nx/devkit         : 19.1.0
@nx/eslint-plugin  : 19.1.0
@nx/playwright     : 19.1.0
@nrwl/tao          : 19.1.0
@nx/web            : 19.1.0
@nx/webpack        : 19.1.0
typescript         : 5.1.6
---------------------------------------
Community plugins:
@compodoc/compodoc   : 1.1.21
@ngrx/effects        : 16.3.0
@ngrx/router-store   : 16.3.0
@ngrx/schematics     : 16.3.0
@ngrx/store          : 16.3.0
@ngrx/store-devtools : 16.3.0
ng-mocks             : 14.11.0
```

### Failure Logs

Jenkins log:

```shell
NX   Running target build for project XXXX and 1 task it depends on:

> nx run api:build:production

NX   findCacheDirectory is not a function

TypeError: findCacheDirectory is not a function
    at findCachePath (/root/.jenkins/workspace/XXXX-pr-check_PR-532/node_modules/@nx/angular/src/executors/ng-packagr-lite/ng-packagr-adjustments/pre-v17/ng-package/options.di.js:34:12)
    at normalizeOptions (/root/.jenkins/workspace/XXXX-pr-check_PR-532/node_modules/@nx/angular/src/executors/ng-packagr-lite/ng-packagr-adjustments/pre-v17/ng-package/options.di.js:25:52)
    at nxProvideOptions (/root/.jenkins/workspace/XXXX-pr-check_PR-532/node_modules/@nx/angular/src/executors/ng-packagr-lite/ng-packagr-adjustments/pre-v17/ng-package/options.di.js:18:15)
    at Object.<anonymous> (/root/.jenkins/workspace/XXXX-pr-check_PR-532/node_modules/@nx/angular/src/executors/ng-packagr-lite/ng-packagr-adjustments/pre-v17/ng-package/options.di.js:21:68)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)

 NX   Running target build for project XXXX and 1 task it depends on failed

Failed tasks:

- api:build:production
```

### Operating System

- [ ] macOS
- [X] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

We are currently running Angular 16.2.7, because of third-party dependencies.

**Comment by mattiaslvv** [comment]
Facing exact same issue here, just migrated a NX angular library to 19.1.0, but with Angular 16.2.12.

**Comment by mattiaslvv** [comment]
Downgrading specifically @nx/angular to "18.1.3" while the other @nx deps where at 19.1.0 fixed the issue for me, it built correctly.

**Comment by ArgV04** [comment]
Facing the same issue!

**Comment by bstrob** [comment]
The issue exists also on 19.1.1.
