### PR TITLE
fix(react): not breaking jest.config.js when no projects exist

### LINKED ISSUE #3885: Generating react library causes tests to fail after upgrading to 10.3.0
## Current Behavior
Generate a data-access library under an existing directory completes successfully. After this running jest tests errors out on any of the libs with 

```
(oldOptions[key] || []).map is not a function
```

## Expected Behavior
The tests should run successfully.

## Steps to Reproduce
Write some lib tests that pass for all libs
```
yarn nx run-many --target=test --all
```
Create a new library by running this command:
```
nx generate @nrwl/react:library --name=data-access --directory=ui/main --no-component --tags='scope:ui-main, type:data-access'
```
Run tests again

### Failure Logs
```
(oldOptions[key] || []).map is not a function
```

### Environment

```
  nx : 10.3.0
  @nrwl/angular : Not Found
  @nrwl/cli : 10.3.0
  @nrwl/cypress : 10.3.0
  @nrwl/eslint-plugin-nx : 10.3.0
  @nrwl/express : 10.3.0
  @nrwl/jest : 10.3.0
  @nrwl/linter : 10.3.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : 10.3.0
  @nrwl/react : 10.3.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 10.3.0
  @nrwl/web : 10.3.0
  @nrwl/workspace : 10.3.0
  typescript : 4.0.3
```
Downgrading back to `10.2.1` fixes the problem.

One difference i noticed is in the lib's jest.config.js

```js
module.exports = {
  ...
  preset: "../../../../jest.config.js", // <-- this value is ../../../../jest.preset.js in 10.3.0
  ...
};
```

### PR DESCRIPTION
**Pull request by ZackDeRose**
## Current Behavior

Legacy workspaces have `jest.config.js` files that can look like this:

```js
module.exports = {
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
  transform: {
    '^.+\\.(ts|js|html)$': 'ts-jest',
  },
  resolver: '@nrwl/jest/plugins/resolver',
  moduleFileExtensions: ['ts', 'js', 'html'],
  coverageReporters: ['html'],
  passWithNoTests: true,
};
```

Note no `projects` property on the config object. Currently, when adding a new react lib, this updates the contents of this file to:

```js
module.exports = {
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
  transform: {
    '^.+\\.(ts|js|html)$': 'ts-jest',
  },
  resolver: '@nrwl/jest/plugins/resolver',
  moduleFileExtensions: ['ts', 'js', 'html'],
  coverageReporters: ['html'],
  passWithNoTests: true,
  projects: '<rootDir>/libs/my-lib'
};
```

This causes all other project tests to fail. See #3885.

## Expected Behavior

This changes behavior on legacy `jest.config.js` files to not update (and therefore break) them.

I believe we may want to investigate a migration to update these legacy `jest.config.js` files in the future, but I also believe that work is not mutually exclusive with this fix.

## Related Issue(s)

Fixes #3885

### CODE REVIEW

File: packages/jest/src/generators/jest-project/lib/update-jestconfig.ts [hunk 1]
```diff
@@ -1,9 +1,26 @@
...
+
+/**
+ * Will parse a single-statement `jest.config.js` file to see if the `projects`
+ * property exists on the exported config object.
+ *
+ * Expects a single assignment statement to an Object literal.
+ */
+function hasProjectsProperty(tree: Tree) {
+  const ast = parse(tree.read('jest.config.js').toString());
+  return !!(ast.program.body[0] as any).expression.right.properties.find(
```
Comment (FrozenPandaz) [inline packages/jest/src/generators/jest-project/lib/update-jestconfig.ts:14]: This is fancy. :sweat_smile:

Though to make it simpler, I think we can use the `jestConfigObject` to get the jest config as an object.

cc @Cammisuli

**Comment by ZackDeRose** [comment]
Closing. Properly running migrations will prevent root cause from occurring.
