### ISSUE TITLE
Jest option "transformIgnorePatterns" don't work with Nx 14.8/15 and React

### ISSUE THREAD

**Issue by DominikPieper** [nrwl/nx#12723]
We have a generator for React Ionic templates but trying with a default react app adding Ionic dependencies, the result is the same.

## Expected Behavior
Jest is able to run the test.
I'm not sure what version it broke. With 14.5 it was working; with 14.8 not. At some point in between it broke.

## Steps to Reproduce
- Create a React app using @nrwl/react package.
- Import a component from Ionic:
e.g.
```
import {IonApp, setupIonicReact} from '@ionic/react';

setupIonicReact();

export function App() {
  return (
    <IonApp>
      <h1>Hello World</h1>
    </IonApp>
  );
}

export default App;
```
- add transformIgnorePatterns to the jest config
```
  transformIgnorePatterns: [
    'node_modules/(?!(@ionic/react|@ionic/react-router|@ionic/core|@stencil/core|ionicons)/)',
  ],
```
- run 'nx test <appname>'

### Failure Logs
nx run reactapp:test

 FAIL   reactapp  apps/reactapp/src/app/app.spec.tsx
  ● Test suite failed to run

    TypeError: transformer.process is not a function

      at Object.process (../../packages/react/plugins/jest.ts:37:43)
      at ScriptTransformer.transformSource (../../node_modules/@jest/transform/build/ScriptTransformer.js:619:31)
      at ScriptTransformer._transformAndBuildScript (../../node_modules/@jest/transform/build/ScriptTransformer.js:765:40)
      at ScriptTransformer.transform (../../node_modules/@jest/transform/build/ScriptTransformer.js:822:19)
      at Object.<anonymous> (../../node_modules/@stencil/core/internal/client/index.js:24:1)
      at Object.<anonymous> (../../node_modules/@ionic/core/components/index.js:4:1)
      at Object.<anonymous> (../../node_modules/@ionic/react/dist/index.js:7:20)
      at Object.<anonymous> (src/app/app.tsx:2:1)
      at Object.<anonymous> (src/app/app.spec.tsx:3:1)

### Environment
Node : 16.13.1
   OS   : darwin x64
   yarn : 1.22.15

   nx : 14.8.5
   @nrwl/angular : 14.8.5
   @nrwl/cypress : 14.8.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.5
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.5
   @nrwl/js : 14.8.5
   @nrwl/linter : 14.8.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 14.8.5
   @nrwl/nx-cloud : 15.0.0
   @nrwl/nx-plugin : 14.8.5
   @nrwl/react : 14.8.5
   @nrwl/react-native : Not Found
   @nrwl/rollup : 14.8.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.5
   @nrwl/web : 14.8.5
   @nrwl/webpack : 14.8.5
   @nrwl/workspace : 14.8.5
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @nxext/ionic-react: 999.9.9

**Comment by barbados-clemens** [comment]
Most likely will be fixed in https://github.com/nrwl/nx/pull/12614

Are you using jest 28? I think installing swc/jest should get you around the issue today while I work on that PR.

**Comment by DominikPieper** [comment]
Yes it’s jest 28. okay thanks, I’ll try the swc version

**Comment by DominikPieper** [comment]
@barbados-clemens I tried with swc/jest but result is the same ^^'

**Comment by barbados-clemens** [comment]
it's most likely from Jest 28 changes to babel-jest API that I missed. 

it's now `require('babel-jest').default.createTransformer()` instead of `require('babel-jest')`

which that linked PR will fix. I'm going to test locally to see if that works. If you want to jump in your node_modules and try it in the `@nrwl/react/jest` transformer to verify you can.

**Comment by neil-hughes** [comment]
So relieved to find this thread. We hit the same problem with frontend testing but only when importing enums generated from Prisma. This took me down quite a long rabbit hole exploring different configs for importing/exporting then stumbled on this issue.

I can confirm that the fix mentioned above by @barbados-clemens solves this issue - hopefully it will be merged in soon.

Thanks!
