### PR TITLE
fix(core): allow ts-node to read tsconfig when registering transpiler…

### LINKED ISSUE #28711: After upgrading from NX17.3.0 to 17.3.1 loading file using .js extension fails with error Cannot find module
### Current Behavior

After upgrading from NX17.3.0 to 17.3.1 loading file using .js extension fails with error Cannot find module

example

import { Example as ExampleBase } from './example.js';

Module not found: Error: Cannot find module './example'

### Expected Behavior

When loading files using extensions they should load without issue.

### GitHub Repo

_No response_

### Steps to Reproduce

1. Create react nx repo with version 17.3.1
2. Add import with .js extension

### Nx Report

   Node   : 20.17.0
   OS     : darwin-x64
   pnpm   : 9.10.0
   
   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/linter         : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/workspace      : 17.3.1
   @nx/cypress        : 17.3.1
   @nx/devkit         : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nx/plugin         : 17.3.1
   @nx/react          : 17.3.1
   @nx/storybook      : 17.3.1
   @nrwl/tao          : 17.3.1
   @nx/web            : 17.3.1
   @nx/webpack        : 17.3.1
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   ts-check : 1.0.0
   ---------------------------------------
   Local workspace plugins:
         @ecp/workspace-plugin

### Failure Logs

_No response_

### Package Manager Version

_No response_

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

ERROR in ../../../Example.info.tsx 5:0-60
Module not found: Error: Cannot find module './Example'

### PR DESCRIPTION
**Pull request by wcwcaseman**
… to allow read of .js imports.

closed #28711

## Related Issue(s)

Fixes #28711

### CODE REVIEW

**Comment by wcwcaseman** [comment]
@Cammisuli Please review and let me know if this can be merged.

**Comment by wcwcaseman** [comment]
@AgentEnder any update on this?

**Comment by wcwcaseman** [comment]
@AgentEnder , @FrozenPandaz any update on this?

**Comment by FrozenPandaz** [comment]
Can you confirm that this is still an issue on the latest version and rebase this onto `master` please? We won't be cutting a patch for Nx 17 at this point. Thank you.

**Comment by leosvelperez** [comment]
Thanks for taking the time to contribute!

As @FrozenPandaz mentioned, we won't be cutting a patch for Nx v17, which is already out of our support window. Additionally, this fix doesn't seem appropriate for the linked issue. The transpiler is only used for in-memory transpilation of config files or Nx local plugins. It shouldn't be used when running the build tool itself. If that's the case, the issue is separate. 

I'm closing this PR. Let's chat over the issue to troubleshoot this properly.
