### ISSUE TITLE
Can no longer build publishable libraries that import other publishable libraries after migrate to v14

### ISSUE THREAD

**Issue by sir-captainmorgan21** [nrwl/nx#10785]
## Current Behavior
All Libraries are Angular.
Running the build target on a publishable library that imports another publishable library fails with the following error message after I migrated our repo to NX 14.

```
packages/design-system/bottom-sheet/src/lib/bottom-sheet.component.ts:10:44 - error TS6059: File '/Users/zach.morgan/Development/Web.CO2/packages/design-system/cdk/overlay/src/index.ts' is not under 'rootDir' '/Users/zach.morgan/Development/Web.CO2/packages/design-system/bottom-sheet/src'. 'rootDir' is expected to contain all source files.
  The file is in the program because:
    Imported via '@snagajob/cdk/overlay' from file '/Users/zach.morgan/Development/Web.CO2/packages/design-system/bottom-sheet/src/lib/bottom-sheet.component.ts'
    Imported via '@snagajob/cdk/overlay' from file '/Users/zach.morgan/Development/Web.CO2/packages/design-system/bottom-sheet/src/lib/bottom-sheet.service.ts'
    Imported via "@snagajob/cdk/overlay" from file '/Users/zach.morgan/Development/Web.CO2/packages/design-system/bottom-sheet/src/lib/types/bottom-sheet-options.ts'
    Imported via "@snagajob/cdk/overlay" from file '/Users/zach.morgan/Development/Web.CO2/packages/design-system/bottom-sheet/src/lib/types/bottom-sheet-ref.ts'

10 import { SAJOverlayContentContainer } from '@snagajob/cdk/overlay';
                                              ~~~~~~~~~~~~~~~~~~~~~~~

  packages/design-system/bottom-sheet/src/lib/bottom-sheet.service.ts:3:35
    3 import { SAJOverlayService } from '@snagajob/cdk/overlay';
                                        ~~~~~~~~~~~~~~~~~~~~~~~
    File is included via import here.
  packages/design-system/bottom-sheet/src/lib/types/bottom-sheet-options.ts:1:35
    1 import { SAJOverlayOptions } from "@snagajob/cdk/overlay";
                                        ~~~~~~~~~~~~~~~~~~~~~~~
    File is included via import here.
  packages/design-system/bottom-sheet/src/lib/types/bottom-sheet-ref.ts:2:44
    2 import { SAJOverlayContentContainer } from "@snagajob/cdk/overlay";
                                                 ~~~~~~~~~~~~~~~~~~~~~~~
    File is included via import here.
```

We were having no issues building prior to the migration.

## Expected Behavior
Previously it would make sure that any libraries it relied on were built and would build them if they weren't. It would then successfully build.

## Steps to Reproduce
- Migrate from v13 to 14 (It put me at `14.3.5`)
- Create a publishable library (lib A) with a basic angular component
- Create another publishable library (lib B) with another basic angular component
- import component from lib B into lib A
- attempt to build lib A

### Failure Logs
You can see error message up above

### Environment
```
 Node : 16.12.0
   OS   : darwin x64
   npm  : 8.1.0
   
   nx : 14.3.5
   @nrwl/angular : 14.3.5
   @nrwl/cypress : 14.3.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.3.5
   @nrwl/eslint-plugin-nx : 14.3.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.3.5
   @nrwl/js : 14.3.5
   @nrwl/linter : 14.3.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.3.5
   @nrwl/web : Not Found
   @nrwl/workspace : 14.3.5
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
   	 @compodoc/compodoc: 1.1.18
   	 @storybook/angular: 6.5.9
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, I can't reproduce the issue following the provided steps. Could you please provide a repo where this can be reproduced so we can troubleshoot it?

**Comment by Grompie** [comment]
Have the same issue here with version 14.3.1.
Think it's the same bug as #10733.
Error keeps popping up:
 error TS6059: File '...index.ts' is not under 'rootDir' '/some_file'. 'rootDir' is expected to contain all source files.

**Comment by leosvelperez** [comment]
Could you confirm which preset you used to create the workspace? Do you have a `"extends": "nx/presets/npm.json"` or `"extends": "nx/presets/core.json"` in your `nx.json`?

**Comment by Grompie** [comment]
In my project I don't have a extends property in nx.json. I tested with both and none seemed to have any effect.
when creating the workspace I chose the preset apps.

**Comment by leosvelperez** [comment]
@Grompie can you provide a reproduction? Or at the very least, could you share the content of your `nx.json`? You can strip out the Nx Cloud key if you're using it or any secrets you might have.

**Comment by sir-captainmorgan21** [comment]
@leosvelperez thanks for getting to this so quickly: Here is my nx.json contents:

```
{
  "implicitDependencies": {
    ".circleci/config.yml": "*"
  },
  "extends": "nx/presets/core.json",
  "npmScope": "snagajob",
  "affected": {
    "defaultBase": "main"
  },
  "cli": {
    "defaultCollection": "@nrwl/angular"
  },
  "tasksRunnerOptions": {
    "default": {
      "runner": "nx/tasks-runners/default",
      "options": {
        "cacheableOperations": [
          "build",
          "lint",
          "test",
          "e2e",
          "build-storybook"
        ]
      }
    }
  },
  "generators": {
    "@nrwl/angular:library": {
      "linter": "eslint",
      "unitTestRunner": "karma",
      "prefix": "saj"
    },
    "@schematics/angular:component": {
      "prefix": "saj",
      "style": "scss"
    },
    "@schematics/angular:directive": {
      "prefix": "saj"
    },
    "@nrwl/angular:application": {
      "linter": "eslint",
      "unitTestRunner": "karma"
    },
    "@nrwl/angular:component": {}
  },
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "targetDefaults": {
    "build": {
      "dependsOn": ["^build"]
    }
  }
}

```

**Comment by leosvelperez** [comment]
@sir-captainmorgan21 thanks for sharing!

There seems to have been an issue with a migration that was schedule for a version but the migration itself was released in another version, so that might have caused the migration to not run in some scenarios. That migration should have added the following in `nx.json` for anyone having their `nx.json` extending from `nx/presets/core.json` or `nx/presets/npm.json`:

```json
{
  ...
  "pluginsConfig": {
    "@nrwl/js": {
      "analyzeSourceFiles": true
    }
  }
}
```

Could you please add the above snippet to your `nx.json` and try again? If after applying the change it doesn't pick it up immediately, run `nx reset` and then try again.

**Comment by leosvelperez** [comment]
Great! I'm going to close this issue.

For anyone else having this issue, please see https://github.com/nrwl/nx/issues/10785#issuecomment-1158916416 for an explanation and solution.

**Comment by nhhockeyplayer** [comment]
Im very uncomfortable with the library features
Im not getting anything done
for buildable + publishable....

I got 20 libraries all buildable and publishable and nothing is holding water build fails 

Has the Nx team shaken this out with a repo that does such? Like a large monorepo for apps and libs whereby libs are buildable AND publishable. And also to provide a best practice momentum tech doc on how to keep your code in a chronic synchronized state in DEV MODE (not publishing but developing) whereby a synchronization occurs when the library code changes a across the monorepo, node_modules not the library registry (beit npm or github actions) in a functional manner so developers do not have to do round trip npm install setup cycle for every line of code that changes inside node_modules?

Can someone help here and add to these semantics.

a tech doc

whats the best practice for a heavy library developer in Nx who creates libs that are buildable and publishable at same time? How do you sync node_modules without havign to reinstall changes every time? DO we need to do npm pack ? DO we need to embellish tsconfig.base.json?

Can anyone speak to this? The field is promising clients the world and we need answers not build issues.
