### PR TITLE
feat(core): refactor lock file parsing and pruning

### LINKED ISSUE #13863: Pruning does not always generate accurate lock file
### Current Behavior

The generated lock file with NPM and PNPM is sometimes not matching the expected versions of package manager.

### Expected Behavior

The generated lock file with NPM and PNPM should be installable with the locked lock file

### Github Repo

_No response_

### Steps to Reproduce

1. Generate a new workspace with the NextJS app using NPM or PNPM as a package manager
2. Build app
3. Go to `dist/apps/yourapp` and run `npm ci` or `pnpm install --frozen-lockfile`
4. Installation fails because some packages are out of sync

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.12.1
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx : 15.3.0
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.3.0
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.3.0
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.3.0
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.3.0
   @nrwl/js : 15.3.0
   @nrwl/linter : 15.3.0
   @nrwl/nest : Not Found
   @nrwl/next : 15.3.0
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.3.0
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.3.0
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.3.0
   @nrwl/web : 15.3.0
   @nrwl/webpack : 15.3.0
   @nrwl/workspace : 15.3.0
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
         @nrwl/react-native
         @nrwl/nx-plugin
         @nrwl/storybook
         @nrwl/workspace
         @nrwl/angular
         @nrwl/cypress
         @nrwl/esbuild
         @nrwl/express
         @nrwl/webpack
         @nrwl/linter
         @nrwl/rollup
         @nrwl/detox
         @nrwl/react
         @nrwl/expo
         @nrwl/jest
         @nrwl/nest
         @nrwl/next
         @nrwl/node
         @nrwl/vite
         @nrwl/web
         @nrwl/js
         nx
   ---------------------------------------
   Community plugins:
         @ngrx/effects: 15.0.0
         @ngrx/router-store: 15.0.0
         @ngrx/store: 15.0.0
         @nguniversal/builders: 15.0.0
         @storybook/angular: 6.5.13
         lerna: 6.0.0
         rxjs: 6.6.7
```

### Failure Logs

npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.

### Additional Information

Yarn lock file generation seems to be working fine

### LINKED ISSUE #14096: generatePackageJson is missing packages
### Current Behavior

Some dependencies are missing from the generated package.json file.

### Expected Behavior

All dependencies used by the project should be included in the generated package.json file.

### Github Repo

_No response_

### Steps to Reproduce

1. Use generatePackageJson: true in 15.3.2+

### Nx Report

```shell
Node : 16.18.0
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx : 15.4.2
   @nrwl/angular : 15.4.2
   @nrwl/cypress : 15.4.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.2
   @nrwl/esbuild : 15.4.2
   @nrwl/eslint-plugin-nx : 15.4.2
   @nrwl/expo : Not Found
   @nrwl/express : 15.4.2
   @nrwl/jest : 15.4.2
   @nrwl/js : 15.4.2
   @nrwl/linter : 15.4.2
   @nrwl/nest : 15.4.2
   @nrwl/next : Not Found
   @nrwl/node : 15.4.2
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.4.2
   @nrwl/workspace : 15.4.2
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
   	 @compodoc/compodoc: 1.1.19
   	 @trumbitta/nx-plugin-unused-deps: 1.12.1
```

### Failure Logs

```shell
Error: Cannot find module '@nestjs/common'
```

### Additional Information

We recently upgraded to Nx 15.4.2 and started having issues with all of our API projects suddenly missing dependencies. I began slowly rolling back one minor version a time until suddenly it started working at 15.3.0. I then stepped forward patch versions and saw it immediately broke at 15.3.2. Comparing the [diff](https://github.com/nrwl/nx/compare/15.3.0...15.3.2) between 15.3.2 and 15.3.0 showed that there were some changes to the generatePackageJson option that we use.

In 15.3.2, Nx began also generating a pruned lockfile in addition to the package.json file. I'm guessing somewhere in these changes something functionally changed with the implementation for the package.json file. In our case, some were very obviously actual dependencies that should be included in the package.json. For example, a NestJS-based API that explicitly imports @nestjs/core and @nestjs/common but for some reason these packages were missing. Here's a screenshot that shows a lot of the errors and the packages that we saw now missing:

image

For now we've rolled everything back to 15.3.0 to keep things operating normally. I did try the next beta version to see if maybe a fix had already been planned, but unfortunately it still didn't work as expected. I haven't tried reproducing this in a brand new project. Also the build executor we use is `@nrwl/webpack:webpack` incase that has any implication.

### LINKED ISSUE #14275: After upgrade to 15.4.5 peerDependancies are no longer added to lib package.jsons (@nrwl/js:tsc)
### Current Behavior

Hello,
I upgraded our project to `15.4.5` from `14.x`. I ran all migrations and the internal apps do run without any problems. 

But I recognized that our libs build is missing all peer dependencies from the root. All internal libs are added without a problem. 

### Expected Behavior

All peer dependencies from the root for all libs are included in the created package.json of each lib.

### Github Repo

_No response_

### Steps to Reproduce

1. npm install
2. nx run X:build 

### Nx Report

```shell
nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : darwin arm64
   npm  : 8.19.2
   
   nx : 15.4.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : 15.4.5
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.4.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.5
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : 15.4.5
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : 15.4.5
   typescript : 4.9.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
no logs
```

### Additional Information

After some hours of debugging, I narrowed the problem down to the `package.lock` parsing.

While building the dependencys graph the missing packages are not found because not all have a version in the runtime object. They only have a property called `actualVersion`. The source of this lies in the npm.ts resolving [here](https://github.com/nrwl/nx/blob/b4dbdf60b5a080ba9b0c4f4a5fee8d44a60e86a0/packages/nx/src/lock-file/npm.ts#L163) and [here](https://github.com/nrwl/nx/blob/b4dbdf60b5a080ba9b0c4f4a5fee8d44a60e86a0/packages/nx/src/lock-file/npm.ts#L206).

We have a lot of dependencies like the following:

```
{
  version: "3.7.0",
  license: "MIT",
  dependencies: {
    ...
  },
  peerDependencies: {
    ...
  },
  peerDependenciesMeta: {
    ...
  },
}
```

The problem is that they have a `version` but no `integrity` and `resolved` property. So the used version is `undefined`. And the metadata stored in the graph is:

```
{
    actualVersion: "3.7.0",
    version: undefined,
}
```

And the `undefined` version is used while building to write the `package.json` for the libs. As the JSON serializer ignores these undefined the peer dependencies are missing.

### LINKED ISSUE #14721: Yarn lockfile parsing change between 15.5.x and 15.6.x causing issues for npm
### Current Behavior

When building a library that has its own external dependency explicitly set in its package.json file with nx@15.6.3 the generated package.json contains a version entry for an internal package that conflicts with npm. e.g. npm will fail installing the library post publish due to the version field being an unconventional tarball URL. This behaviour leaks out the registry configuration. 

e.g.

```json
{
  "@foo/package": "npm:5.1.1::__archiveUrl=<encoded-url-to-foo-package-tarball>.tgz"
}
```

This is how yarn writes the resolution field in the `yarn.lock` file for this dependency.

### Expected Behavior

When building the library i expect the package.json to include the conventional semver version. 

```json
{
  "@foo/package": "5.1.1"
}
```

### GitHub Repo

_No response_

### Steps to Reproduce

1. Use yarn berry package manager
2. Generate a library that is publishable
3. In newly created library add an external dependency that would create a unconventional resolution

- e.g. resolution: "@foo/package@npm:1.0.56::__archiveUrl=tarball-url.tgz"

4. Build library
5. Observe that the generated package.json contains an uncontentional version which will fail if published and installed with npm. 

### Nx Report

```shell
➜ nx report

 >  NX   Report complete - copy this into the issue template

   Node : 16.18.0
   OS   : darwin arm64
   yarn : 3.2.3
   
   nx : 15.6.3
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.6.3
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.6.3
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.6.3
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.6.3
   @nrwl/js : 15.6.3
   @nrwl/linter : 15.6.3
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 15.0.2
   @nrwl/nx-plugin : 15.6.3
   @nrwl/react : 15.6.3
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.6.3
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.6.3
   @nrwl/web : 15.6.3
   @nrwl/webpack : Not Found
   @nrwl/workspace : 15.6.3
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

### Failure Logs

```shell
{
  "@ruter-ds-next/tokens": "npm:5.1.1::__archiveUrl=https%3A%2F%2Fgitlab.com%2Fapi%2Fv4%2Fprojects%2F35624188%2Fpackages%2Fnpm%2F%40ruter-ds-next%2Ftokens%2F-%2F%40ruter-ds-next%2Ftokens-5.1.1.tgz",
}
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by meeroslav**
Progress tracking:
- [X] Parsing
  - [X] Alias packages
  - [X] Duplicate packages
  - [X] Tarball packages
  - [X] Workspaces
  - [X] NPM
  - [X] Yarn
  - [X] Pnpm 
- [X] Mapping to project graph
- [x] Pruning
- [x] Stringification
  - [x] NPM 1
  - [x] NPM 2
  - [X] NPM 3 
  - [x] Yarn Classic
  - [x] Yarn Berry
  - [x] Pnpm (map to default)  
- [x] Cleanup of old functionality
 - [x] E2E tests for pruning
 - [x] Implement/Unit tests workspaces support
 - [x] Unit tests for pruning alias and tarball packages

## Current Behavior
State of the existing implementation:
- It’s heavily guided by final stringification, so the intermediate structure carries a lot of metadata from lock files
- The structure has flaws that are not verified on the construction
- The resulting lock file is sometimes inaccurate (leading to failed installation)
- We have no way to test the validity of the parsed/pruned structure
- The code/logic is very complex, hacky and hard to read

## Expected Behavior
The goal of the rewriting:
- Simplify the graph representation
- Have a way to check the validity
- Prune graph instead of metadata
- Separate graph logic from package manager specifics

## Implementation clarification
- New logic uses a builder similar to ProjectGraphBuilder to construct a graph from packages and dependencies, which allows us to:
  - Check the consistency (all nodes should have incoming nodes, each edge must have defined from and to node, etc.)
  - Easily tree-shake and traverse graph when pruning
- The graph contains minimal information from lock files:
  - Dependency name
  - Package name (if different from dependency name)
  - Version (or URL for tarball packages)
- Stringification is decoupled from the actual pruning process
  - We prune the LockFileGraph and then use this as a base for lock file stringification
  - Stringification uses content from the original lock file. This is trivial for Yarn and Pnpm but requires some gymnastics for Npm (find the package hierarchy and handle V1 and V3 mapping separately).
- Unit tests use actual generated lock files as input params
  - Unit tests are grouped around logic problems
    - Alias and tarball packages
    - Same package with same version installed twice in different locations
    - Real-world NextJS examples
    - Pruning single and multiple dependencies
    - Optional children
    - Workspaces
  - Additional manually crafted will be added to test a few corner cases which are not that easy to generate
- The resulting code has a lot of validations all over the place to ensure we detect broken things

Note, due to complexity and differences between PRs, the code is larger than 1000 loc (without warnings, etc.)
We can compress files more, but that would come at the expense of readability.

## Related Issue(s)

Fixes #13863
Fixes #14096
Fixes #14275
Fixes #14721
Related to #9761
Related to #14106

### CODE REVIEW

**Comment by sushruth** [comment]
Cant wait to have this merged!

**Review by FrozenPandaz — APPROVED** [review]
