### ISSUE TITLE
Production build fails after updating to v8.8.0

### ISSUE THREAD

**Issue by puku0x** [nrwl/nx#2092]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency)

## Expected Behavior
`nx build project-name --prod` should work.

## Current Behavior

It does not work because there are some missing dependencies.
```
Cannot find module '@angular/compiler'
Cannot find module '@angular/compiler-cli'
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Run `create-nx-workspace` to make a React app
2. Build it with `--prod`

If you can provide steps to reproduce from scratch, that would be enormously appreciated (i.e. where the first step is `npx create-nx-workspace@latest repro-workspace`)

### Context
```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 8.8.0
  @nrwl/cypress : 8.8.0
  @nrwl/eslint-plugin-nx : 8.8.0
  @nrwl/express : Not Found
  @nrwl/jest : 8.8.0
  @nrwl/linter : 8.8.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 8.8.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.8.0
  @nrwl/web : 8.8.0
  @nrwl/workspace : 8.8.0
  typescript : 3.5.3
```

## Other

https://github.com/nrwl/nx/commit/c2ed286d5a7f1b9c1f49ce05384877721dd4d7ae#diff-4b4c52bbc2d97ac4bebf2aaac826ca86 in https://github.com/nrwl/nx/pull/2004

**Comment by mbriggs** [comment]
Thank you for the report! We will get this fixed asap

**Comment by vsavkin** [comment]
Fixed it in 8.8.1:
https://github.com/nrwl/nx/commit/11b92d0b9f4ca19ad6952188e99776daeb5a3c0b

Thank you for reporting the issue.
