### ISSUE TITLE
Cypress - Error: Webpack Compilation Error, Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by nemonemi** [nrwl/nx#15737]
### Current Behavior

Everything worked fine up until I abstracted a library from the app.

Now, everything works, except Cypress tests.

![225959596-9a462f2d-9f06-4fa4-8529-89859619f6fc](https://user-images.githubusercontent.com/77624664/225969905-d8edd2b5-d8fd-4528-baa4-6ea34e6f7e73.png)
![225966774-2d585004-1d3d-4c34-b3fa-9f2e11564a7a](https://user-images.githubusercontent.com/77624664/225969940-2dd5a616-f813-40dd-bd4e-4d2e38920381.png)

However, there are no missing dependencies or syntax errors. Builds pass without any issues, and the runtime also works as it should.

### Expected Behavior

It should work as it did before.

### Steps to Reproduce

1.

### Nx Report

```shell
Node : 16.14.0
   OS   : linux x64
   yarn : 3.4.1
   
   nx                      : 15.8.6
   @nrwl/js                : 15.8.6
   @nrwl/jest              : 15.8.6
   @nrwl/linter            : 15.8.6
   @nrwl/workspace         : 15.8.6
   @nrwl/cli               : 15.8.6
   @nrwl/cypress           : 15.8.6
   @nrwl/devkit            : 15.8.6
   @nrwl/eslint-plugin-nx  : 15.8.6
   @nrwl/react             : 15.8.6
   @nrwl/rollup            : 15.8.6
   @nrwl/storybook         : 15.8.6
   @nrwl/tao               : 15.8.6
   @nrwl/web               : 15.8.6
   @nrwl/webpack           : 15.8.6
   @nrwl/schematics        : 8.12.11
   typescript              : 4.9.5
```

### Failure Logs

```shell
Oops...we found an error preparing this test file:

  > src/e2e/test.spec.ts

The error was:

Error: Webpack Compilation Error
/home/path/libs/utilities/src/lib/jwt-token-provider.tsx 21:23
Module parse failed: Unexpected token (21:23)
File was processed with these loaders:
 * ../../../../../.cache/Cypress/12.8.0/Cypress/resources/app/node_modules/@packages/server/node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
|     }, [isUsingQASBackendInsteadOfLocalMock]);
|     if (isLocalDevelopment && isUsingQASBackendInsteadOfLocalMock) {
>         return token ? <JWTContext.Provider value={token}>{children}</JWTContext.Provider> : null;
|     }
|     return children;

```

**Comment by charleskoehl** [comment]
I had a similar error after migrating to 15.8.6. I had to downgrade to 15.8.5 and then the builds worked. No other code was changed.

**Comment by nemonemi** [comment]
I've just noticed that if I exclude my newly generated library, that I've abstracted the code from the application to create it, then the tests start passing.
What should I configure in the application, or the library, to make the tests recognize the JSX coming from the library?

**Comment by charleskoehl** [comment]
> 

This seems relevant: https://github.com/nrwl/nx/issues/15794

**Comment by nemonemi** [comment]
It is not obvious to me that they are related.
I've managed to resolve my issue by splitting the code even further.

The reason why my problem was occurring is that I had a file that contained an exported Context and an exported Context provider.
After splitting them into two separate libraries, the problem went away, however, that is not how I'd like my code to be, and it is not evident why this problem occurs.

This error is not indicative of the exact problem and makes the debugging difficult and time-consuming.
```
Module parse failed: Unexpected token (21:23)
File was processed with these loaders:
```

**Comment by jaysoo** [comment]
Just to confirm, this is a React app created through `@nrwl/react` with a Cypress test suite?

Can someone share their `webpack.config.js` that is having issues?

**Comment by nemonemi** [comment]
I've resolved it by splitting the content from one into multiple libraries.

**Comment by jaysoo** [comment]
Interesting, if you have a reproduction I can take a look. Otherwise I'll see if I can reproduce it locally.
