### ISSUE TITLE
After upgrading from NX17.3.0 to 17.3.1 loading file using .js extension fails with error Cannot find module

### ISSUE THREAD

**Issue by wcwcaseman** [nrwl/nx#28711]
### Current Behavior

After upgrading from NX17.3.0 to 17.3.1 loading file using .js extension fails with error Cannot find module

example

import { Example as ExampleBase } from './example.js';

Module not found: Error: Cannot find module './example'

### Expected Behavior

When loading files using extensions they should load without issue.

### Steps to Reproduce

1. Create react nx repo with version 17.3.1
2. Add import with .js extension

### Nx Report

   Node   : 20.17.0
   OS     : darwin-x64
   pnpm   : 9.10.0
   
   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/linter         : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/workspace      : 17.3.1
   @nx/cypress        : 17.3.1
   @nx/devkit         : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nx/plugin         : 17.3.1
   @nx/react          : 17.3.1
   @nx/storybook      : 17.3.1
   @nrwl/tao          : 17.3.1
   @nx/web            : 17.3.1
   @nx/webpack        : 17.3.1
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   ts-check : 1.0.0
   ---------------------------------------
   Local workspace plugins:
         @ecp/workspace-plugin

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

ERROR in ../../../Example.info.tsx 5:0-60
Module not found: Error: Cannot find module './Example'

**Comment by wcwcaseman** [comment]
This problem exists in the latest version of NX 20.0.8. I have added a merge request for the version where this functionality was broken.

In packages/nx/src/plugins/js/utils/register.ts 

skipProject: true,

was added to service = register({

it needs to be removed to allow .js extension imports to work.

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Do you still have this issue? If so, please provide a minimal repo where the issue can be reproduced. Please try to use a newer version of Nx, preferably the latest version.

**Comment by leosvelperez** [comment]
This was fixed by https://github.com/nrwl/nx/pull/31323.
