### ISSUE TITLE
Barrel file missing? Importing @nx/angular/src/utils results in "Cannot find module" error

### ISSUE THREAD

**Issue by timtos** [nrwl/nx#22588]
### Current Behavior

Writing a custom nx generator I am trying to import the angular utility `addProviderToComponent`:

`import { addProviderToComponent } from '@nx/angular/src/utils';`

Unfortunately, I am getting an error:
> Cannot find module '@nx/angular/src/utils' or its corresponding type declarations.ts(2307)

The generator is running happily but the build throws an error.

Please also have a look at the "Additional Information" provided at the bottom.

### Expected Behavior

There should be no error and it should be easy to use this helper function.

### Steps to Reproduce

Try to use addProviderToComponent within a generator:

const componentPath = 'apps/my-app/src/app/app.component.ts';
const text = tree.read(componentPath);
const sourceX = ts.createSourceFile(componentPath, text.toString(), ts.ScriptTarget.Latest, true);
addProviderToComponent(tree, sourceX, componentPath, 'MyProvider');

### Nx Report (custom)

Cannot run the nx report due to an invalid token in my path:
Error: Cannot find module 'C:\Users\T├╝m...

But I am using version:

```shell
"nx": "~18.0.7",
"@nx/angular": "~18.0.7",
"@nx/cypress": "~18.0.7",
"@nx/eslint": "~18.0.7",
"@nx/eslint-plugin": "~18.0.7",
"@nx/devkit": "~18.0.7",
"@nx/js": "~18.0.7",
"@nx/plugin": "~18.0.7",
"@nx/storybook": "~18.0.7",
"@nx/web": "~18.0.7",
"@nx/workspace": "~18.0.7",
```
### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

In the folder **@nx\angular\src\utils** I see the file **public-api.d.ts** with the following content:

```
export { isStandalone, addImportToComponent, addImportToDirective, addImportToPipe, addImportToModule, addProviderToBootstrapApplication, addProviderToAppConfig, addProviderToComponent, addProviderToModule, } from './nx-devkit/ast-utils';
export { addRoute, addProviderToRoute } from './nx-devkit/route-utils';
```

**If I place an index.ts file in the same location with the same content, everything works as expected.**

Is there an index.ts file missing?
Is there another way to import this functionality?

**Comment by timtos** [comment]
A related change was introduced with the 3895696f8a6593bbf583ffeaf8b7412e1bd0e5a4 by @Coly010.

**Comment by Jad31** [comment]
Hi, I have the same issue trying to use the `addRoute` function. I'm on `Ubuntu 22.04.4 LTS`.
