### ISSUE TITLE
Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by Himadu2000** [nrwl/nx#5907]
## Current Behavior
Running `nx run app:serve` provide following error (Failure Logs)

## Expected Behavior
Open the app without errors or warnings
Is this a regression? No

## Steps to Reproduce
[Here's a Github repo](https://github.com/Himadu2000/nx-tap-error-recreate)
[And the following actions run](https://github.com/Himadu2000/nx-tap-error-recreate/runs/2758680216?check_suite_focus=true)

Steps,
1. Create an nx workspace with react preset
2. Add following package.json file `{
  "dependencies": {
    "core-js": "^3.13.1",
    "document-register-element": "1.14.10",
    "gatsby": "^3.6.2",
    "gatsby-image": "3.6.0",
    "gatsby-plugin-manifest": "3.6.0",
    "gatsby-plugin-offline": "4.6.0",
    "gatsby-plugin-react-helmet": "4.6.0",
    "gatsby-plugin-sharp": "3.6.0",
    "gatsby-plugin-svgr": "3.0.0-beta.0",
    "gatsby-plugin-typescript": "3.6.0",
    "gatsby-source-filesystem": "3.6.0",
    "gatsby-transformer-sharp": "3.6.0",
    "next": "10.2.3",
    "prop-types": "15.7.2",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-helmet": "6.1.0",
    "regenerator-runtime": "0.13.7",
    "tslib": "^2.2.0"
  },
  "devDependencies": {
    "@babel/core": "7.14.3",
    "@babel/preset-env": "7.14.4",
    "@babel/preset-react": "7.13.13",
    "@babel/preset-typescript": "7.13.0",
    "@emotion/babel-preset-css-prop": "11.2.0",
    "@nrwl/cli": "12.3.6",
    "@nrwl/cypress": "12.3.6",
    "@nrwl/eslint-plugin-nx": "12.3.6",
    "@nrwl/express": "^12.3.6",
    "@nrwl/gatsby": "^12.3.6",
    "@nrwl/jest": "12.3.6",
    "@nrwl/linter": "12.3.6",
    "@nrwl/next": "^12.3.6",
    "@nrwl/node": "12.3.6",
    "@nrwl/nx-cloud": "12.1.8",
    "@nrwl/react": "^12.3.6",
    "@nrwl/storybook": "^12.3.6",
    "@nrwl/tao": "12.3.6",
    "@nrwl/web": "^12.3.6",
    "@nrwl/workspace": "12.3.6",
    "@storybook/addon-knobs": "^6.2.9",
    "@storybook/react": "^6.2.9",
    "@svgr/webpack": "^5.5.0",
    "@testing-library/react": "11.2.7",
    "@types/jest": "26.0.23",
    "@types/node": "15.12.0",
    "@types/reach__router": "^1.3.8",
    "@types/react": "17.0.9",
    "@types/react-dom": "17.0.6",
    "@types/react-redux": "7.1.16",
    "@types/webpack": "5.28.0",
    "@typescript-eslint/eslint-plugin": "4.26.0",
    "@typescript-eslint/parser": "4.26.0",
    "babel-jest": "27.0.2",
    "babel-loader": "8.2.2",
    "babel-plugin-module-resolver": "4.1.0",
    "babel-preset-gatsby": "1.6.0",
    "cypress": "^7.4.0",
    "dotenv": "10.0.0",
    "eslint": "7.27.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-plugin-cypress": "^2.11.3",
    "eslint-plugin-import": "2.23.4",
    "eslint-plugin-jsx-a11y": "6.4.1",
    "eslint-plugin-react": "7.24.0",
    "eslint-plugin-react-hooks": "4.2.0",
    "jest": "27.0.4",
    "prettier": "2.3.0",
    "ts-jest": "27.0.2",
    "ts-node": "~10.0.0",
    "tslint": "~6.1.3",
    "typescript": "~4.3.2",
    "url-loader": "^4.1.1"
  }
}
`
3. Install dependencies with yarn
4. Run the app with serve

### Failure Logs
`> nx run test:serve 
Starting type checking service...
Using 1 worker with 2048MB memory limit
Cannot read property 'tap' of undefined

———————————————————————————————————————————————

>  NX   ERROR  Running target "test:serve" failed

  Failed tasks:
  
  - test:serve

Error: Process completed with exit code 1.`

### Environment
  Node : 14.17.0
  OS   : linux x64
  yarn : 1.22.10
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.3.6
  @nrwl/cypress : 12.3.6
  @nrwl/devkit : 12.3.6
  @nrwl/eslint-plugin-nx : 12.3.6
  @nrwl/express : 12.3.6
  @nrwl/jest : 12.3.6
  @nrwl/linter : 12.3.6
  @nrwl/nest : Not Found
  @nrwl/next : 12.3.6
  @nrwl/node : 12.3.6
  @nrwl/react : 12.3.6
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.6
  @nrwl/web : 12.3.6
  @nrwl/workspace : 12.3.6
  @nrwl/storybook : 12.3.6
  @nrwl/gatsby : 12.3.6
  typescript : 4.3.2

**Comment by r-hannuschka** [comment]
Got the same problem:

```bash
npx ng serve workbook
> nx run workbook:serve
Starting type checking service...
Using 2 workers with 2048MB memory limit
Cannot read property 'tap' of undefined
———————————————————————————————————————————————
>  NX   ERROR  Running target "workbook:serve" failed
  Failed tasks:
  - workbook:serve
~/work/gucci$ events.js:292
      throw er; // Unhandled 'error' event
      ^
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:705:16)
    at RpcProvider._dispatch (/home/ralf/work/gucci/node_modules/@nrwl/node/node_modules/fork-ts-checker-webpack-plugin/lib/cluster.js:30:17)
    at /home/ralf/work/gucci/node_modules/worker-rpc/lib/RpcProvider.js:107:52
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
Emitted 'error' event on process instance at:
    at internal/child_process.js:709:35
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
```

looks like a webpack problem ? Not sure i checked "fork-ts-checker-webpack-plugin" this seems to be version 3.1.1 which uses webpack.5.0.0-alpha but Angular 12 uses Webpack 5.38.1

**Comment by shardyMBAI** [comment]
I am seeing this after updating from nx@12.3.6 to 12.3.6 in our angular project, we also make use of a custom webpack config

**Comment by nestorvanz** [comment]
I got the same error after installing Webpack. 

I installed Webpack due the error: `Cannot find module 'webpack'`.

For some reason in a fresh installation I don't have Webpack installed, already reported in this [issue](https://github.com/nrwl/nx/issues/5949).

**Comment by kunjee17** [comment]
I also got the same problem. After couple of tries I was able to build angular project but once I add next js to mix, it just don't compile with similar issue.

**Comment by marvelbark2** [comment]
Try to add this to your package.json : 
```
"resolutions": {
      "webpack": "4.44.0"
  }
```

**Comment by kunjee17** [comment]
@marvelbark2 didn't work for me. :(

**Comment by kunjee17** [comment]
```
├─┬ @angular-devkit/build-angular@12.0.3
│ └── webpack@5.38.1
├─┬ @nrwl/next@12.3.6 invalid
│ └─┬ @nrwl/web@12.3.6
│   └── UNMET PEER DEPENDENCY webpack@4.42.0
├─┬ @nrwl/web@12.5.7
│ └── UNMET PEER DEPENDENCY webpack@4.42.0
└─┬ jest-preset-angular@9.0.3
  └── webpack@5.36.2
```

It seems to be issue with `@nrwl/web` not updated to webpack 5. Any idea when it going to happen ?

**Comment by marvelbark2** [comment]
Your issue is there's many versions of webpack !

**Comment by kunjee17** [comment]
@marvelbark2 any way to work around this one ? Basically Angular is on web pack and nrwl/web is still on webpack 4 so next is still on webpack 4.

**Comment by marvelbark2** [comment]
You know what add this to your package.json :
```
"webpack": "~4.42.0",
"webpack-dev-server": "3.11.2"
```

**Comment by kunjee17** [comment]
Now at least there is new error. 

```
./pages/index.module.less
TypeError: this.getOptions is not a function

```

But it is still not working. @marvelbark2

**Comment by marvelbark2** [comment]
Can you share with me your git repo ? or ./pages/index.module.less code ?

**Comment by kunjee17** [comment]
Here you go. It is empty class 

```less
.page {
}

```

@marvelbark2

**Comment by marvelbark2** [comment]
I don't know about less but i think you need to add sass to your deps : 
"sass-loader": "^10"

**Comment by kunjee17** [comment]
@marvelbark2 Have tried installing all deps. Same issue. Already have less and less loader in deps. Now, only thing can be done is to wait for nrwl to update to webpack 5 and latest next js.

**Comment by xiongemi** [comment]
I played with your repo as well. after I added:
```
"resolutions": {
    "webpack": "4.46.0"
  }
  ```
in package.json and run yarn install, I was able to serve up the site using `test:serve`.

**Comment by Himadu2000** [comment]
> I played with your repo as well. after I added:
> 
> ```
> "resolutions": {
>     "webpack": "4.46.0"
>   }
> ```
> 
> in package.json and run yarn install, I was able to serve up the site using `test:serve`.

Thanks @xiongemi, It works. You're a life saver. Keeping issue open until Nx update it's dependencies soon.

**Comment by Himadu2000** [comment]
@xiongemi, However there's something I'm unsure, could you try creating gatsby app and running it. Maybe resolutions needs to be changed.

**Comment by xiongemi** [comment]
@Himadu2000 
i submit a pr to your repo. so basically to have react and gatsby in the same nx workspace, you need to have webpack 5. this is what I did:
- run `nx migrate latest` to install the latest nx packages
- run `npx nx g @nrwl/web:webpack5` to upgrade to webpack 5
- then I added a gatsby app just to test

**Comment by Himadu2000** [comment]
@xiongemi You solution works, but when I start a react-app It takes 1.5GB of RAM and 500MB for a server, and vs-code crashes, Is this normal? I have a feeling this is a memory leak.

**Comment by Himadu2000** [comment]
```
 Fatal error in , line 0
 Fatal process out of memory: Zone

FailureMessage Object: 0000008EE5AF98C0

 Fatal error in , line 0
 Fatal process out of memory: Zone

FailureMessage Object: 0000008EE58F96F0
(node:12552) UnhandledPromiseRejectionWarning: RpcIpcMessagePortClosedError: Process 3736 exited with code "3221225725"
```

**Comment by Himadu2000** [comment]
Well I'm kinda 99% sure I have memory leak.

**Comment by jaysoo** [comment]
Closing this issue since we've moved Gatsby plugin to the labs repo. https://github.com/nrwl/nx-labs

Feel free to open it there.
