### ISSUE TITLE
Migration-Related Notes: Nx 9 -> Nx 10 -> Nx 11

### ISSUE THREAD

**Issue by vsavkin** [nrwl/nx#4333]
Folks, migrating workspaces is hard. Every workspace is different, with different combinations of versions, packages, package managers etc.. Also, every workspace evolves differently: as you migrate from version to version, you make small changes making your workspace unique.

Please read the following to learn about the migrate command: [https://nx.dev/workspace/update](https://nx.dev/workspace/update).

To reiterate a few things from the doc:

## Important: Use Latest Version of Migration Logic

- If you are on the latest Nx 10 or Nx 11, we will automatically use the latest version of the migration logic to update your workspace. There is nothing you need to do. 

If you aren't on the latest 10x or 11x:
- If you are on the earlier version of Nx and you are using npm 6 (or yarn, pnpm), you have to do it yourself by running `npx @nrwl/tao@latest migrate latest`. 
- NPM 7 broke npx, so `npx @nrwl/tao@latest migrate latest` won't work. So you have to manually update the version of `@nrwl/tao` in your `package.json` to `latest` (or latest 10x) and then run `npx nx migrate latest`.
- If you are seeing `Cannot find module '@angular-devkit/architect'`, you are an unlucky person who is using Nx 10.4.11. I--Victor Savkin--screwed up that patch release. I'm sorry about this. Run `nx migrate 10.4.12`, run `npm/yarn/pnpm install`, which will fix it, and then follow the instructions above.

## One Major at a Time

It's easier to migrate one major version at a time. If you want to migrate from 9x to 11x (latest), you could run:

```
> npx @nrwl/tao@latest migrate latest
```

For most workspace it will work, but for some it won't. In this case run:

```
> npx @nrwl/tao@latest migrate 10.4.12 (do the whole migration process to 10x). See instructions above for npm 7 users.
> nx migrate atest (do the whole migration process to 11x)
```

## If You Use Angular, Don't Use Ng Update

Please read [https://nx.dev/latest/core-concepts/updating-nx](https://nx.dev/latest/core-concepts/updating-nx) to see why `nx migrate` is a more reliable way to migrate your workspace. \

## We Can Help

If you see an exception while migrating, file an issue. Troubleshooting migration-related issues tends to be challenging, but we will do our best to unblock you.

**Comment by cyrus-za** [comment]
I am having issues. I logged it in slack here: https://nrwlcommunity.slack.com/archives/C015WMB2A8P/p1608372515058900

Basically getting this error
`ENOENT: no such file or directory, open 'root/libs/lib-b/package.json'`

Why would it look for package.json inside a lib? 

Works fine on 10.4.7

Changelog below:
![Uploading image.png…]()

**Comment by x87** [comment]
@vsavkin & Nrwl Just stopped by to say that you guys are great. Thank you for all your hard work on Nx tools. Let the next year be rock solid for all frontend communities that you support: Angular, React, Vue and, of course, Nx itself. Take a break, and enjoy holiday time!

**Comment by royling** [comment]
@vsavkin recently I was trying to upgrade to Nx10 from v8, however I found a breaking issue which is likely introduced in these lines: https://github.com/nrwl/nx/blob/10.4.7/packages/angular/src/schematics/application/application.ts#L800-L803.

From the comment, this is likely a workaround for some Angular 10 versions...Do you think this is a bug? I do see those are already removed in Nx11, is it ok for me to use Nx11 for Angular10 projects?

Thanks!

**Comment by royling** [comment]
Found the original review comments, @FrozenPandaz would you please check my question?
https://github.com/nrwl/nx/pull/3056/files#r551133198

**Comment by markgoho** [comment]
- How do we know which Angular-related packages will be updated via nx migrate and which ones won't? E.g. NgRx, RxJS, etc.
- How do we know which version of Angular nx migrate is targeting when we run the command? E.g. version 11.1 of Angular is out, but when I run `nx migrate latest` I'm not getting the latest version of Angular. 
- Does that mean I wait until Nx updates to Angular 11.1? 
- What harm might I cause by manually updating to a newer version of Angular outside of nx migrate?

Also: https://nx.dev/workspace/update is redirecting to nx.dev

**Comment by markgoho** [comment]
@vsavkin should I try and get these questions answered in a different place? I'm currently sitting at a minor version behind Angular and wondering what the recommended path is for updating. If it's "wait until Nx updates its dependency" that's fine, but I think we should be very clear about this.

**Comment by vandermore** [comment]
I'm currently going from ng/nx 9 to 11.

These are the steps I am using and the versions I was on before I started the update.

_Versions:_
- Angular 9.1.0 -> 10.2.4
- NX 9.2.3 -> 10.4.13 ( I've been at this for a week, so it was an earlier version before today )
- Node: 12.20.1
- npm: 6.10.2

Using the commands that were laid out in the first post of this issue but with the patch version updated:
`npx @nrwl/tao@latest migrate 10.4.13`

After much troubleshooting I've got this error going from ng 9 to ng 10 coming from the update. Any help would be appreciated, thank you.
```
    Updating @angular/core to 10.0.0

>  NX   ERROR  "ng update" is deprecated in favor of "nx migrate". Read more: https://nx.dev/latest/angular/workspace/update


>  NX   ERROR  "ng update" is deprecated in favor of "nx migrate". Read more: https://nx.dev/latest/angular/workspace/update

Unknown error: Error
@angular/core migration failed, see above.
/Users/dmoore054/Documents/repos/webapp/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

Error: Command failed: /var/folders/9p/tmfpmvqd79q556mn4h_w0cvr0000gn/T/tmp-290i3hn5hofq255/node_modules/.bin/tao migrate --run-migrations
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at Object.handler (/Users/dmoore054/Documents/repos/webapp/node_modules/@nrwl/workspace/src/command-line/nx-commands.js:78:25)
    at Object.runCommand (/Users/dmoore054/Documents/repos/webapp/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/command.js:196:48)
    at Object.parseArgs [as _parseArgs] (/Users/dmoore054/Documents/repos/webapp/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:1043:55)
    at Object.get [as argv] (/Users/dmoore054/Documents/repos/webapp/node_modules/@nrwl/workspace/node_modules/yargs/build/lib/yargs.js:986:25)
    at Object.initLocal (/Users/dmoore054/Documents/repos/webapp/node_modules/@nrwl/cli/lib/init-local.js:24:13)
    at Object.<anonymous> (/Users/dmoore054/Documents/repos/webapp/node_modules/@nrwl/cli/bin/nx.js:40:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 398,
  stdout: null,
  stderr: null
}

```

**Comment by jimbarrett33** [comment]
@vandermore maybe this will help. I did a successful migration from 9 -> 10 -> 11 with these steps:

1) `npx @nrwl/tao@latest migrate 10.4.13`
2) `npm install --legacy-peer-deps`
3) `npx nx migrate latest`
4) `npm install --legacy-peer-deps`
5) `npx nx migrate --run-migrations`

The important step is 3) where you need to run the above instead of `npx nx migrate --run-migrations` because by the time you are step 3 you are at @nrwl/cli and workspace version 10.4.13 so you can/should now run `npx nx migrate latest` or you'll get the above "ng update" error.

(I have similar node and npm versions.)

Hope that helps.

**Comment by vandermore** [comment]
That did seem to work, thanks! I was hoping to go from 9 to 10 then test things, then to 11, but it seems I have little choice except to go straight through.

**Comment by markgoho** [comment]
Just successfully went from v9 to v12 by using `npx @nrwl/tao@latest migrate latest`, then installing packages, then running migrations. Thank you Nrwl team!
