### ISSUE TITLE
Storybook error when upgrading to 15.4.8

### ISSUE THREAD

**Issue by ureciocais** [nrwl/nx#17785]
### Current Behavior

Slowly trying to reach v16.
At the moment stuck at v15.4.8 (Storybook react is at v6.5.16)
Running Storybook I get this first: `Cannot find module '@babel/plugin-proposal-export-default-from'`
Once the module is installed I get: 
```
ModuleNotFoundError: Module not found: Error: Can't resolve 'SuisseIntl-Regular-WebS.woff2' in '/Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/src'
    at /Users/urecio/sources/cais/monorepo/node_modules/webpack/lib/Compilation.js:2016:28
    at /Users/urecio/sources/cais/monorepo/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Users/urecio/sources/cais/monorepo/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/urecio/sources/cais/monorepo/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Users/urecio/sources/cais/monorepo/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/urecio/sources/cais/monorepo/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Users/urecio/sources/cais/monorepo/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Users/urecio/sources/cais/monorepo/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Users/urecio/sources/cais/monorepo/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Users/urecio/sources/cais/monorepo/node_modules/webpack/lib/NormalModuleFactory.js:975:5
resolve 'SuisseIntl-Regular-WebS.woff2' in '/Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/src'
  Parsed request is a module
  using description file: /Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/package.json (relative path: ./src)
    using description file: /Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/package.json (relative path: ./src/SuisseIntl-Regular-WebS.woff2)
      no extension
        /Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/src/SuisseIntl-Regular-WebS.woff2 doesn't exist
      .mjs
        /Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/src/SuisseIntl-Regular-WebS.woff2.mjs doesn't exist
      .js
        /Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/src/SuisseIntl-Regular-WebS.woff2.js doesn't exist
      .jsx
        /Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/src/SuisseIntl-Regular-WebS.woff2.jsx doesn't exist
      .ts
        /Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/src/SuisseIntl-Regular-WebS.woff2.ts doesn't exist
      .tsx
        /Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/src/SuisseIntl-Regular-WebS.woff2.tsx doesn't exist
      .json
        /Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/src/SuisseIntl-Regular-WebS.woff2.json doesn't exist
      .cjs
        /Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/src/SuisseIntl-Regular-WebS.woff2.cjs doesn't exist
      as directory
        /Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/src/SuisseIntl-Regular-WebS.woff2 doesn't exist
    resolve as module
      /Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/src/node_modules doesn't exist or is not a directory
      /Users/urecio/sources/cais/monorepo/libs/shared/ui/fonts/node_modules doesn't exist or is not a directory
      /Users/urecio/sources/cais/monorepo/libs/shared/ui/node_modules doesn't exist or is not a directory
      /Users/urecio/sources/cais/monorepo/libs/shared/node_modules doesn't exist or is not a directory
      /Users/urecio/sources/cais/monorepo/libs/node_modules doesn't exist or is not a directory
```

### Expected Behavior

loads Storybook

### Steps to Reproduce

1. yarn nx migrate 15.4.8 (from version 15.4.0)

### Nx Report

```shell
Node : 16.15.0
   OS   : darwin arm64
   yarn : 1.22.19

   nx : 15.4.8
   @nrwl/angular : Not Found
   @nrwl/cypress : 15.4.8
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.8
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.8
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 15.4.8
   @nrwl/js : 15.4.8
   @nrwl/linter : 15.4.8
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.4.8
   @nrwl/nx-cloud : 16.0.5
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 15.4.8
   @nrwl/react-native : Not Found
   @nrwl/rollup : 15.4.8
   @nrwl/schematics : Not Found
   @nrwl/storybook : 15.4.8
   @nrwl/web : 15.4.8
   @nrwl/webpack : 15.4.8
   @nrwl/workspace : 15.4.8
   @nrwl/vite : 15.4.8
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   	 @cais-group/equity-generator
   ---------------------------------------
   Community plugins:
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by mandarini** [comment]
Hi there @ureciocais ! Thanks for filing an issue! It would be super helpful if you could provide me with a minimum reproduction repository. Like, for example, you can create a new Nx workspace with 15.4.8, add Storybook, add these fonts, and the error shows up. That way, I will be able to solve this issue for you! :D Thank you very much in advance!

**Comment by ureciocais** [comment]
Hi @mandarini, I got it working yesterday by changing the font imports from
```
@font-face {
  font-display: swap;
  font-family: 'Suisse Intl';
  font-weight: 400;
  src: url('./font/SuisseIntl-Regular-WebS.woff2') format('woff2'),
    url('./font/SuisseIntl-Regular-WebS.woff') format('woff');
}
```
to
```
@font-face {
  font-display: swap;
  font-family: 'Suisse Intl';
  font-weight: 400;
  src: url('./SuisseIntl-Regular-WebS.woff2') format('woff2'),
    url('./SuisseIntl-Regular-WebS.woff') format('woff');
}
```
And obviously moving the fonts to the root folder of the library

**Comment by mandarini** [comment]
That's wonderful news! Thanks for letting me know!
