### ISSUE TITLE
[Nx Vite TsPaths] Unable to resolve any file

### ISSUE THREAD

**Issue by cyberarc8** [nrwl/nx#29320]
### Current Behavior

When setting up a new React Monorepo with Vite `npx create-nx-workspace@latest react-monorepo --preset=react-monorepo` and then trying to build the App, the logs are cluttered with messages about Vite being unable to resolve paths. 

Example:

[Nx Vite TsPaths] Unable to resolve C:\Users\Me\Data\Code\react-monorepo\apps\my-react-app\index.html with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved C:\Users\Me\Data\Code\react-monorepo\apps\my-react-app\index.html to undefined

### Expected Behavior

All Paths should be resolved correctly.

### Steps to Reproduce

1. `npx create-nx-workspace@latest react-monorepo --preset=react-monorepo`
2. make selections: `√ Application name · my-react-app
√ Which bundler would you like to use? · vite
√ Test runner to use for end to end (E2E) tests · cypress
√ Default stylesheet format · tailwind
√ Which CI provider would you like to use? · azure`
4. `cd react-monorepo`
5. `npx nx build my-react-app --verbose`

### Nx Report

```shell
Node           : 22.9.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.8.3

nx                     : 20.2.2
@nx/js                 : 20.2.2
@nx/jest               : 20.2.2
@nx/eslint             : 20.2.2
@nx/workspace          : 20.2.2
@nx/cypress            : 20.2.2
@nx/devkit             : 20.2.2
@nx/eslint-plugin      : 20.2.2
@nx/module-federation  : 20.2.2
@nx/react              : 20.2.2
@nx/vite               : 20.2.2
@nx/web                : 20.2.2
typescript             : 5.6.3
---------------------------------------
Registered Plugins:
@nx/vite/plugin
@nx/eslint/plugin
@nx/cypress/plugin
@nx/jest/plugin
```

### Failure Logs

```shell
~/Data/Code
$ npx create-nx-workspace@latest react-monorepo --preset=react-monorepo
npm warn exec The following package was not found and will be installed: create-nx-workspace@20.2.2

 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

√ Application name · my-react-app
√ Which bundler would you like to use? · vite
√ Test runner to use for end to end (E2E) tests · cypress
√ Default stylesheet format · tailwind
√ Which CI provider would you like to use? · azure

 NX   Creating your v20.2.2 workspace.

- Installing dependencies with npm
√ Installing dependencies with npm
- Creating your workspace in react-monorepo
√ Successfully created the workspace: react-monorepo.
- Checking Nx Cloud setup
√ Nx Cloud has been set up successfully
- Generating CI workflow
√ CI workflow has been generated successfully

 NX   Your CI setup is almost complete.

Finish it by visiting: https://cloud.nx.app/connect/...

 NX   Welcome to the Nx community! 👋

🌟 Star Nx on GitHub: https://github.com/nrwl/nx
📢 Stay up to date on X: https://x.com/nxdevtools
💬 Discuss Nx on Discord: https://go.nx.dev/community

~/Data/Code
$ cd react-monorepo

~/Data/Code/react-monorepo (main)
$ npx nx build my-react-app --verbose

> nx run my-react-app:build

> vite build

The CJS build of Vite's Node API is deprecated. See https://vite.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

[Nx Vite TsPaths] Found tsconfig at C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] first parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: 'C:\\Users\\Me\\Data\\Code\\react-monorepo\\tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: 'C:\\Users\\Me\\Data\\Code\\react-monorepo',
  paths: {},
  addMatchAll: true
}

[Nx Vite TsPaths] Found tsconfig at C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] fallback parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: 'C:\\Users\\Me\\Data\\Code\\react-monorepo\\tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: 'C:\\Users\\Me\\Data\\Code\\react-monorepo',
  paths: {},
  addMatchAll: true
}
vite v5.4.11 building for production...

[Nx Vite TsPaths] Unable to resolve C:\Users\Me\Data\Code\react-monorepo\apps\my-react-app\index.html with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved C:\Users\Me\Data\Code\react-monorepo\apps\my-react-app\index.html to undefined

[Nx Vite TsPaths] Unable to resolve /src/styles.css with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved /src/styles.css to undefined
transforming...

[Nx Vite TsPaths] Unable to resolve vite/modulepreload-polyfill with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved vite/modulepreload-polyfill to undefined

[Nx Vite TsPaths] Unable to resolve /src/styles.css with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved /src/styles.css to undefined

[Nx Vite TsPaths] Unable to resolve /src/main.tsx with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved /src/main.tsx to undefined

[Nx Vite TsPaths] Unable to resolve react/jsx-runtime with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved react/jsx-runtime to undefined

[Nx Vite TsPaths] Unable to resolve react with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved react to undefined

[Nx Vite TsPaths] Unable to resolve react-dom/client with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved react-dom/client to undefined

[Nx Vite TsPaths] Unable to resolve ./app/app with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved ./app/app to undefined

[Nx Vite TsPaths] Unable to resolve ./cjs/react-jsx-runtime.production.min.js with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved ./cjs/react-jsx-runtime.production.min.js to undefined

[Nx Vite TsPaths] Unable to resolve react/jsx-runtime with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved react/jsx-runtime to undefined

[Nx Vite TsPaths] Unable to resolve ./nx-welcome with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved ./nx-welcome to undefined

[Nx Vite TsPaths] Unable to resolve ./cjs/react.production.min.js with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved ./cjs/react.production.min.js to undefined

[Nx Vite TsPaths] Unable to resolve react-dom with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved react-dom to undefined

[Nx Vite TsPaths] Unable to resolve react with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved react to undefined

[Nx Vite TsPaths] Unable to resolve react/jsx-runtime with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved react/jsx-runtime to undefined

[Nx Vite TsPaths] Unable to resolve ./cjs/react-dom.production.min.js with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved ./cjs/react-dom.production.min.js to undefined

[Nx Vite TsPaths] Unable to resolve react with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved react to undefined

[Nx Vite TsPaths] Unable to resolve scheduler with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved scheduler to undefined

[Nx Vite TsPaths] Unable to resolve ./cjs/scheduler.production.min.js with tsconfig paths. Using fallback file matching.

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Trying to resolve file from config in C:\Users\Me\Data\Code\react-monorepo\tsconfig.base.json

[Nx Vite TsPaths] Resolved ./cjs/scheduler.production.min.js to undefined
✓ 32 modules transformed.
rendering chunks...
computing gzip size...
../../dist/apps/my-react-app/index.html                   0.48 kB │ gzip:  0.31 kB
../../dist/apps/my-react-app/assets/index-Dob4_79B.css    5.94 kB │ gzip:  1.73 kB
../../dist/apps/my-react-app/assets/index-CwAXzi5-.js   166.81 kB │ gzip: 51.85 kB
✓ built in 4.81s



 NX   Successfully ran target build for project my-react-app


View logs and investigate cache misses at https://nx.app/runs/wtLwu3F3do
```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by trekinbami** [comment]
I have the same issue after migrating from 16.8 to 20.3.1. Is there a starting point for debugging this?

**Comment by everythinginjs** [comment]
same here on running Vitest

**Comment by yoshhiii** [comment]
Also experiencing this with `@nx/workspace": "20.0.6"`. TS paths aren't resolved for any project in the repo (react and storybook) when building.

**Comment by mikehuebner** [comment]
Is there a way to just mute these? 😅

**Comment by d-oliveros** [comment]
Same here, does anyone know a fix for this?

**Comment by rogerok** [comment]
Same here, version is  20.0.12

**Comment by siiron** [comment]
I've had this error since bunping to NX v20.x.x. But it has not bothered me since I silenced the waring by removing --verbose. But today, migrating to nx v20.3.1 the warning became an error and stopped my Storybook build saying error TS5083: Cannot read file './tsconfig.json'. I'm currently running Storybok v8.4.5 and vite v5.4.8.

```
> nx run design-system-storybook-react:build
 NX  Storybook builder starting ...
info => Cleaning outputDir: dist\apps\design-system-storybook-react
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
info => Loading presets
info => Building manager..
info
 => Manager built (235 ms)
info => Building preview..
info => Copying static files: apps\design-system-storybook-react\assets at dist\apps\design-system-storybook-react
[Nx Vite TsPaths] Found tsconfig at C:\Projects\Designsystem\DS-Mono-branches\tsconfig.base.json
[Nx Vite TsPaths] first parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: 'C:\\Projects\\Designsystem\\DS-Mono-branches\\tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: 'C:\\Projects\\Designsystem\\DS-Mono-branches',
  paths: {
    '@namespace/design-system-icons': [ 'libs/design-system-icons/index.ts' ],
    '@namespace/design-system-storybook-react': [ 'apps/design-system-storybook-react/src/index.ts' ],
    '@namespace/design-system-tokens': [ 'libs/design-system-tokens/dist/ts/tokens.ts' ],
    '@namespace/design-system-ui-react': [ 'libs/design-system-ui-react/src/index.ts' ],
    '@namespace/design-system-ui-web': [ 'libs/design-system-ui-web/src/index.ts' ],
    '@namespace/design-system-utils': [ 'libs/design-system-utils/src/index.ts' ]
  },
  addMatchAll: true
}
[Nx Vite TsPaths] Found tsconfig at C:\Projects\Designsystem\DS-Mono-branches\tsconfig.base.json
[Nx Vite TsPaths] fallback parsed tsconfig:  {
  resultType: 'success',
  configFileAbsolutePath: 'C:\\Projects\\Designsystem\\DS-Mono-branches\\tsconfig.base.json',
  baseUrl: '.',
  absoluteBaseUrl: 'C:\\Projects\\Designsystem\\DS-Mono-branches',
  paths: {
    '@namespace/design-system-icons': [ 'libs/design-system-icons/index.ts' ],
    '@namespace/design-system-storybook-react': [ 'apps/design-system-storybook-react/src/index.ts' ],
    '@namespace/design-system-tokens': [ 'libs/design-system-tokens/dist/ts/tokens.ts' ],
    '@namespace/design-system-ui-react': [ 'libs/design-system-ui-react/src/index.ts' ],
    '@namespace/design-system-ui-web': [ 'libs/design-system-ui-web/src/index.ts' ],
    '@namespace/design-system-utils': [ 'libs/design-system-utils/src/index.ts' ]
  },
  addMatchAll: true
}
error TS5083: Cannot read file './tsconfig.json'.
 NX   Running target build for project design-system-storybook-react and 6 tasks it depends on failed
Failed tasks:
- design-system-storybook-react:build
Hint: run the command with --verbose for more details.
```

**Comment by nemonemi** [comment]
I am experiencing this on 20.4.0.

**Comment by DOZBORNE** [comment]
I am on 20.4.0, with an Nx repo with numerous react libraries, as well as 4 Next JS pages router based apps. 

What I'm trying to do is utilize Vitest for testing, whilst using webpack (default) for bundling, building, and even HMR still for Next JS. However, this is seemingly impossible thus far. 

When using the `nxViteTsPaths` plugin, none of the paths can be resolved and Vitest always fails with `exit 1`. This is super tricky to debug since outside of using a debugger, I cannot get this functionality to work whatsoever. I can't even really get Vitest to tell me why. I've spent hours debugging this, and it seems like using the Nx Vite executor for Vitest is not able to resolve paths and is more or less broken. Though, I'm not sure here. 

If anyone has done/tried anything like this, would love to know. I cannot get success. 

I have also tried to replicate this in a simple new workspace with Next JS app. However, it also does not work. And I cannot seem to get a real error from Vitest.

**Comment by kwextpb** [comment]
A solution that works in my case is to use a `vite-tsconfig-paths` plugin directly. I have not noticed any differences,

I define it as such:

```
plugins: [tsconfigPaths({ root: workspaceRoot, ignoreConfigErrors: true })],
```

Where `workspaceRoot` is a root of the project.

**Comment by Stanzilla** [comment]
> I am on 20.4.0, with an Nx repo with numerous react libraries, as well as 4 Next JS pages router based apps.
> 
> What I'm trying to do is utilize Vitest for testing, whilst using webpack (default) for bundling, building, and even HMR still for Next JS. However, this is seemingly impossible thus far.
> 
> When using the `nxViteTsPaths` plugin, none of the paths can be resolved and Vitest always fails with `exit 1`. This is super tricky to debug since outside of using a debugger, I cannot get this functionality to work whatsoever. I can't even really get Vitest to tell me why. I've spent hours debugging this, and it seems like using the Nx Vite executor for Vitest is not able to resolve paths and is more or less broken. Though, I'm not sure here.
> 
> If anyone has done/tried anything like this, would love to know. I cannot get success.
> 
> I have also tried to replicate this in a simple new workspace with Next JS app. However, it also does not work. And I cannot seem to get a real error from Vitest.

Pretty much the same here. It seems impossible to get a Nextjs + Vitest + Storybook + Storybook Test (Vitest) setup working properly

**Comment by DOZBORNE** [comment]
> A solution that works in my case is to use a `vite-tsconfig-paths` plugin directly. I have not noticed any differences,
> 
> I define it as such:
> 
> ```
> plugins: [tsconfigPaths({ root: workspaceRoot, ignoreConfigErrors: true })],
> ```
> 
> Where `workspaceRoot` is a root of the project.

Hmm, do you use Next JS? I have tried using normal `vite-tsconfig-paths` but I cannot get it to work properly with the `@nx/vite:test` package. I can use it, but I have to manually run vite outside of Nx in order for it to at least resolve paths correctly. Though, this would kinda defeat the whole purpose of Nx in some ways ya know.

**Comment by DOZBORNE** [comment]
> It's actually working as expected, it is just noisy - added a PR to update the `debug` option to forcibly silence the logs: [#30200](https://github.com/nrwl/nx/pull/30200)

Not sure I understand exactly what you mean here. It's not working at all for the situation I described above.

**Comment by Coly010** [comment]
@DOZBORNE Can you open a new issue with a reproduction of your particular issue? It is not exactly the same as the one described here
