### ISSUE TITLE
migrate to 14.2.2, migrations can not be run "Cannot find module '@angular-devkit/core'"

### ISSUE THREAD

**Issue by MatznRisto** [nrwl/nx#10659]
Hey, thank you for updating to angular 14! We have problems to migrate to 14.2.2. We have the same issue we had some months ago. This time `NX_MIGRATE_USE_LOCAL=true` does not work
## Current Behavior

nx migrate --run-migrations are not running through. Stops at Running migration migration-entry-components with error
```Cannot find module '@angular-devkit/core'
Require stack:
- /Users/matthiasristo/.nvm/versions/node/v16.14.2/lib/node_modules/nx/src/commands/ngcli-adapter.js
- /Users/matthiasristo/.nvm/versions/node/v16.14.2/lib/node_modules/nx/src/commands/migrate.js
- /Users/matthiasristo/.nvm/versions/node/v16.14.2/lib/node_modules/nx/src/cli/index.js
- /Users/matthiasristo/.nvm/versions/node/v16.14.2/lib/node_modules/nx/bin/nx.js
```

## Expected Behavior

Migration should run through sucessfully

## Steps to Reproduce

1. Run nx migrate latest (currently 14.2.2)
2. Run npm i
3. Run nx migrate --run-migrations

This issue may not be prioritized if details are not provided to help us reproduce the issue.
Seems to be similar like [7731](https://github.com/nrwl/nx/issues/7731). Environment does not work in this case

### Environment

```  Node : 16.14.2
   OS   : darwin arm64
   npm  : 8.5.0
   
   nx : 14.2.2
   @nrwl/angular : 14.2.2
   @nrwl/cypress : 14.2.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.2.2
   @nrwl/eslint-plugin-nx : 14.2.2
   @nrwl/express : Not Found
   @nrwl/jest : 14.2.2
   @nrwl/js : 14.2.2
   @nrwl/linter : 14.2.2
   @nrwl/nest : 14.2.2
   @nrwl/next : Not Found
   @nrwl/node : 14.2.2
   @nrwl/nx-cloud : 14.0.8
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.2.2
   @nrwl/web : Not Found
   @nrwl/workspace : 14.2.2
   typescript : 4.7.3
   ---------------------------------------
   Community plugins:
   	 @ngneat/hot-toast: 4.1.0
   	 @ngneat/transloco: 4.0.0
   	 @ngneat/spectator: 10.0.0
   	 @storybook/angular: 6.5.8```

**Comment by wstidolph** [comment]
Same error on WLS2/Ubuntu 21.0.4 upgrading from NX 14.1.9 (Angular 13) to NX 14.2.4 (angular 14). Tried delete node_modules/ and package-lock.json before npm i, also tried `export NX_MIGRATE_USE_LOCAL=true; nx migrate --run-migrations `

Previous package.json had `  "@angular-devkit/core": "^13.0.0",` new package.json has `"@angular-devkit/core": "14.0.1",`
````
...
---------------------------------------------------------
Running migration update-router-initial-navigation
Successfully finished update-router-initial-navigation
---------------------------------------------------------
Running migration migration-entry-components
Cannot find module '@angular-devkit/core'
Require stack:
- /home/wstidolph/.nvm/versions/node/v16.13.0/lib/node_modules/nx/src/commands/ngcli-adapter.js
- /home/wstidolph/.nvm/versions/node/v16.13.0/lib/node_modules/nx/src/commands/migrate.js
- /home/wstidolph/.nvm/versions/node/v16.13.0/lib/node_modules/nx/src/cli/index.js
- /home/wstidolph/.nvm/versions/node/v16.13.0/lib/node_modules/nx/bin/nx.js
````

**Comment by juanchavezlive** [comment]
Same error here

**Comment by juanchavezlive** [comment]
As mentioned here:
https://github.com/nrwl/nx/issues/10628

Add the missing line "cli": "nx" to every migration that fails seems to solve the problem.

**Comment by JulienMichelFr** [comment]
Same error here when trying to update from nx 14.1.9.

I tried to use the trick above, but it fails on migrations from `@angular/material` and `@angular/cdk`.

Error when running `nx migrate --run-migrations`

```
Running migration migration-v14
Cannot find module '@angular-devkit/core'
Require stack:
- /home/database/.nvm/versions/node/v16.14.2/lib/node_modules/nx/src/commands/ngcli-adapter.js
- /home/database/.nvm/versions/node/v16.14.2/lib/node_modules/nx/src/commands/migrate.js
- /home/database/.nvm/versions/node/v16.14.2/lib/node_modules/nx/src/cli/index.js
- /home/database/.nvm/versions/node/v16.14.2/lib/node_modules/nx/bin/nx.js
```

I have the issue come from these migrations: 
```json
{
  "migrations": [
    // ...other migrations
    {
      "version": "14.0.0-0",
      "description": "Updates the Angular Material to v14",
      "factory": "./ng-update/index#updateToV14",
      "package": "@angular/material",
      "name": "migration-v14"
    },
    {
      "version": "14.0.0-0",
      "description": "Updates the Angular CDK to v14",
      "factory": "./ng-update/index#updateToV14",
      "package": "@angular/cdk",
      "name": "migration-v14"
    }
    // ...other migrations
  ]
}
```

When I add the `"cli": "nx"` on these two migrations, I get this error: 

```
Running migration migration-v14
Cannot find module '/home/database/web/techno-watcher/node_modules/@angular/material/schematics/./ng-update/index#updateToV14'
Require stack:
- /home/database/.nvm/versions/node/v16.14.2/lib/node_modules/nx/src/commands/migrate.js
- /home/database/.nvm/versions/node/v16.14.2/lib/node_modules/nx/src/cli/index.js
- /home/database/.nvm/versions/node/v16.14.2/lib/node_modules/nx/bin/nx.js
```

--- 

Nx report: 

```
Node : 16.14.2
OS: linux x64
npm  : 8.6.0

nx : 14.3.1
@nrwl/angular : 14.3.1
@nrwl/cypress : 14.3.1
@nrwl/detox : Not Found
@nrwl/devkit : 14.3.1
@nrwl/eslint-plugin-nx : 14.3.1
@nrwl/express : Not Found
@nrwl/jest : 14.3.1
@nrwl/js : 14.3.1
@nrwl/linter : 14.3.1
@nrwl/nest : 14.3.1
@nrwl/next : Not Found
@nrwl/node : 14.3.1
@nrwl/nx-cloud : 14.1.0
@nrwl/nx-plugin : Not Found
@nrwl/react : Not Found
@nrwl/react-native : Not Found
@nrwl/schematics : Not Found
@nrwl/storybook : 14.3.1
@nrwl/web : Not Found
@nrwl/workspace : 14.3.1
typescript : 4.7.3
---------------------------------------
Community plugins:
      @ngrx/component-store: 13.2.0
      @ngrx/effects: 13.2.0
      @ngrx/entity: 13.2.0
      @ngrx/router-store: 13.2.0
      @ngrx/store: 13.2.0
      @ngrx/schematics: 13.2.0
      @ngrx/store-devtools: 13.2.0
      @storybook/angular: 6.5.9
```

**Comment by MatznRisto** [comment]
I also tried ith with `"cli": "nx"` before. Tried also some other things. Did not find a solution. We can not upgrade at the moment. Has someone a solution?

**Comment by JulienMichelFr** [comment]
I've found a fix (and possibly the issue). 

When running the command `nx migrate --run-migrations`, it was the global `nx` command that was used instead of the local one. 

In order to fix it, you can either use
- `./node_modules/.bin/nx migrate --run-migrations`
- `npx nx@14.3.6 migrate --run-migrations`

**Comment by fikkatra** [comment]
> I've found a fix (and possibly the issue).
> 
> When running the command `nx migrate --run-migrations`, it was the global `nx` command that was used instead of the local one.
> 
> In order to fix it, you can either use
> 
> * `./node_modules/.bin/nx migrate --run-migrations`
> * `npx nx@14.3.6 migrate --run-migrations`

This works, thanks a lot!

**Comment by Vevl** [comment]
@leosvelperez do you have any idea?

I was following your advice but after all ended same as [Julien mentioned above](https://github.com/nrwl/nx/issues/10659#issuecomment-1154341148).

These migration was crashing but fixed by adding nx as cli:
- migration-entry-components
- migration-v14-typed-forms
- migration-v14-path-match-type

This produce another error:
- migration-v14 (Updates the Angular CDK to v14)

Error: 
Cannot find module 'C:\*****\node_modules\@angular\cdk\schematics/./ng-update/index#updateToV14'
Require stack:
- C:\*****\AppData\Roaming\npm\node_modules\nx\src\commands\migrate.js
- C:\*****\AppData\Roaming\npm\node_modules\nx\src\cli\index.js
- C:\*****\AppData\Roaming\npm\node_modules\nx\bin\nx.js

Its Windows 10 and as you can see there must be some problem with path **'\schematics/./ng-update'** especially this part.

I will try to create repro asap.

**Comment by Chronos2011** [comment]
I faced the same issue on Debian when updating my project from 13.9 to 14.4. It turned out that a globally installed nx caused the issue. I did:
`$ npm uninstall -g nx`
`$ npm install -g nx@14.4`
The issue was gone afterwards.

**Comment by FrozenPandaz** [comment]
I'm glad the issue was fixed by updating the global install of `nx`!

I just ran the `@angular/material` migrations above successfully as well.

If you continue to run into this issue, please create a new issue.

**Comment by maxime1992** [comment]
In my case running `nvm use` fixed it... I was on node 14 something and with node 16 something it worked...

Just lost over an hour on this
