### ISSUE TITLE
Many issues after upgrade to 15.7

### ISSUE THREAD

**Issue by TheStateOfComedy** [nrwl/nx#14999]
### Current Behavior

After upgrading to 15.7 many issues with generating and compiling. Reverting to 15.6.3 solves the issues

When trying to generate an app, with the cli. 

anthony@anthony-think-ubuntu:~/mt-brands$ nx g @nrwl/express:application image-server

>  NX  Generating @nrwl/express:application
>  NX   (0 , project_configuration_1.shouldDefaultToUsingStandaloneConfigs) is not a function
Pass --verbose to see the stacktrace.

When trying to compile, receive an issue that appears related to circular dependencies, despite project not containing any.

$ npx nx build mt-brands-api-server --verbose
npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.

 >  NX   Running target build for project mt-brands-api-server and 15 tasks it depends on:

 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

> nx run mt-brands-api-server:build
>  NX   Loop detected while pruning. Please report this issue.
HookWebpackError: Loop detected while pruning. Please report this issue.
    at makeWebpackError (/home/anthony/mt-brands/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /home/anthony/mt-brands/node_modules/webpack/lib/Compilation.js:3060:12
    at eval (eval at create (/home/anthony/mt-brands/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at fn (/home/anthony/mt-brands/node_modules/webpack/lib/Compilation.js:480:17)
    at _next0 (eval at create (/home/anthony/mt-brands/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/home/anthony/mt-brands/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (/home/anthony/mt-brands/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/anthony/mt-brands/node_modules/webpack/lib/Compilation.js:502:10
    at Hook.eval [as callAsync] (eval at create (/home/anthony/mt-brands/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/anthony/mt-brands/node_modules/tapable/lib/Hook.js:18:14)
-- inner error --
Error: Loop detected while pruning. Please report this issue.
    at nestMappedPackages (/home/anthony/mt-brands/node_modules/@nrwl/webpack/node_modules/nx/src/lock-file/npm-parser.js:307:15)
    at nestMappedPackages (/home/anthony/mt-brands/node_modules/@nrwl/webpack/node_modules/nx/src/lock-file/npm-parser.js:310:9)
    at nestMappedPackages (/home/anthony/mt-brands/node_modules/@nrwl/webpack/node_modules/nx/src/lock-file/npm-parser.js:310:9)
    at mapSnapshots (/home/anthony/mt-brands/node_modules/@nrwl/webpack/node_modules/nx/src/lock-file/npm-parser.js:256:9)
    at stringifyNpmLockfile (/home/anthony/mt-brands/node_modules/@nrwl/webpack/node_modules/nx/src/lock-file/npm-parser.js:187:28)
    at createLockFile (/home/anthony/mt-brands/node_modules/@nrwl/webpack/node_modules/nx/src/lock-file/lock-file.js:123:54)
    at /home/anthony/mt-brands/node_modules/@nrwl/webpack/src/utils/generate-package-json-webpack-plugin.js:42:135
    at fn (/home/anthony/mt-brands/node_modules/webpack/lib/Compilation.js:478:10)
    at _next0 (eval at create (/home/anthony/mt-brands/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/home/anthony/mt-brands/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
 ———————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
 >  NX   Running target build for project mt-brands-api-server and 15 tasks it depends on failed
   Failed tasks:
   - mt-brands-api-server:build
   

   
   

### Expected Behavior

Should be able to compile and generate apps/libs etc

### Steps to Reproduce

1.
Try to generate an app, or compile an existing one

### Nx Report

```shell
Already reverted sorry
```

**Comment by AgentEnder** [comment]
How did you update? You should use `nx migrate 15.7.0`. or `nx migrate latest`. The error sounds like you had some out of sync versions.

**Comment by TheStateOfComedy** [comment]
The install was originally done, when an npm install grabbed the latest version.  Will try nx migrate when I get a chance

**Comment by AgentEnder** [comment]
Yeah, you shouldn't use ~ or ^ with `nx`, since you need to use migrations.

**Comment by itspers** [comment]
Ive just updated with regular nx migrate latest and have this 

" NX   Loop detected while pruning. Please report this issue."

`HookWebpackError: Loop detected while pruning. Please report this issue.
    at makeWebpackError (C:\Users\omgit\sites\workc\node_modules\webpack\lib\HookWebpackError.js:48:9)
    at C:\Users\omgit\sites\workc\node_modules\webpack\lib\Compilation.js:3060:12
    at eval (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:23:1)
    at fn (C:\Users\omgit\sites\workc\node_modules\webpack\lib\Compilation.js:480:17)
    at _next0 (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1)
    at C:\Users\omgit\sites\workc\node_modules\webpack\lib\Compilation.js:502:10
    at Hook.eval [as callAsync] (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\omgit\sites\workc\node_modules\tapable\lib\Hook.js:18:14)
-- inner error --
Error: Loop detected while pruning. Please report this issue.
    at nestMappedPackages (C:\Users\omgit\sites\workc\node_modules\nx\src\lock-file\npm-parser.js:307:15)
    at nestMappedPackages (C:\Users\omgit\sites\workc\node_modules\nx\src\lock-file\npm-parser.js:310:9)
    at nestMappedPackages (C:\Users\omgit\sites\workc\node_modules\nx\src\lock-file\npm-parser.js:310:9)
    at mapSnapshots (C:\Users\omgit\sites\workc\node_modules\nx\src\lock-file\npm-parser.js:256:9)
    at stringifyNpmLockfile (C:\Users\omgit\sites\workc\node_modules\nx\src\lock-file\npm-parser.js:187:28)
    at createLockFile (C:\Users\omgit\sites\workc\node_modules\nx\src\lock-file\lock-file.js:123:54)
    at C:\Users\omgit\sites\workc\node_modules\@nrwl\webpack\src\plugins\generate-package-json-plugin.js:43:131
    at fn (C:\Users\omgit\sites\workc\node_modules\webpack\lib\Compilation.js:478:10)
    at _next0 (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:34:1)`

Also reverting back..

**Comment by stemcstudio** [comment]
Upgrading @nrwl/workspace from "15.6.3" to "15.7.0" is breaking my build. Interestingly it seems I can upgrade all the other @nrwl/(angular|cypress|jest|lnter|tao|web) packages.

I'm getting the stack trace...

nx run stemcmentor:build:production --aot

Unable to read angular.json
RangeError: Maximum call stack size exceeded
    at arrayBufferToString (/home/david/Development/stemcmono/node_modules/nx/src/adapter/ngcli-adapter.js:256:32)
    at /home/david/Development/stemcmono/node_modules/nx/src/adapter/ngcli-adapter.js:241:73
    at /home/david/Development/stemcmono/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:37
    at OperatorSubscriber._this._next (/home/david/Development/stemcmono/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
    at OperatorSubscriber.Subscriber.next (/home/david/Development/stemcmono/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
    at SafeSubscriber.__tryOrUnsub (/home/david/Development/stemcmono/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/home/david/Development/stemcmono/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/home/david/Development/stemcmono/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/home/david/Development/stemcmono/node_modules/@angular-devkit/core/node_modules/rxjs/internal/Subscriber.js:66:18)
    at Observable._subscribe (/home/david/Development/stemcmono/node_modules/@angular-devkit/core/node/host.js:130:17)

My usual method of upgrade is usually a clean npm install so I'll try following the "nx migrate" approach and see how that goes.

**Comment by AgentEnder** [comment]
Hey folks! I'm going to close this one out. Due to the ambiguous title, multiple issues are being reported between the original poster and other commenters piling on. To help us effectively maintain the repo and address issues that come in appropriately, please try to stick to one issue per github issue.

In these cases its easy to identify that they are a separate issue, since the stack traces are very different.

I'm sure that some issues here do need to be addressed. Please open an issue and include the information requested in the template so that we can more easily diagnose what went wrong.

Thanks.

**Comment by meeroslav** [comment]
> Ive just updated with regular nx migrate latest and have this
> 
> " NX Loop detected while pruning. Please report this issue."
> 
> `HookWebpackError: Loop detected while pruning. Please report this issue. at makeWebpackError (C:\Users\omgit\sites\workc\node_modules\webpack\lib\HookWebpackError.js:48:9) at C:\Users\omgit\sites\workc\node_modules\webpack\lib\Compilation.js:3060:12 at eval (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:23:1) at fn (C:\Users\omgit\sites\workc\node_modules\webpack\lib\Compilation.js:480:17) at _next0 (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:21:1) at eval (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:34:1) at eval (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:11:1) at C:\Users\omgit\sites\workc\node_modules\webpack\lib\Compilation.js:502:10 at Hook.eval [as callAsync] (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1) at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\omgit\sites\workc\node_modules\tapable\lib\Hook.js:18:14) -- inner error -- Error: Loop detected while pruning. Please report this issue. at nestMappedPackages (C:\Users\omgit\sites\workc\node_modules\nx\src\lock-file\npm-parser.js:307:15) at nestMappedPackages (C:\Users\omgit\sites\workc\node_modules\nx\src\lock-file\npm-parser.js:310:9) at nestMappedPackages (C:\Users\omgit\sites\workc\node_modules\nx\src\lock-file\npm-parser.js:310:9) at mapSnapshots (C:\Users\omgit\sites\workc\node_modules\nx\src\lock-file\npm-parser.js:256:9) at stringifyNpmLockfile (C:\Users\omgit\sites\workc\node_modules\nx\src\lock-file\npm-parser.js:187:28) at createLockFile (C:\Users\omgit\sites\workc\node_modules\nx\src\lock-file\lock-file.js:123:54) at C:\Users\omgit\sites\workc\node_modules\@nrwl\webpack\src\plugins\generate-package-json-plugin.js:43:131 at fn (C:\Users\omgit\sites\workc\node_modules\webpack\lib\Compilation.js:478:10) at _next0 (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:21:1) at eval (eval at create (C:\Users\omgit\sites\workc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:34:1)`
> 
> Also reverting back..

Can you create a separate issue and reproduction and tag me, please?

**Comment by meeroslav** [comment]
If providing repo is not possible, try to do following steps:

1. Provide the dependency section of your root `package.json` (all the `dependencies`, `devDependencies` etc.)
e.g.
```jsonc
{
  "dependencies": {
    // ...
  },
  "devDependencies": {
    // ...
  }
}
```

2. Go to `node_modules/nx/src/lock-file/lock-file.js` and comment existing code in the `yarn` if block in `createLockFile` and replace it with `return content`. This will return the existing root lock file and skip the broken part.
```js
if (packageManager === 'yarn') {
    // const graph = (0, yarn_parser_1.parseYarnLockfile)(content);
    // const prunedGraph = (0, project_graph_pruning_1.pruneProjectGraph)(graph, packageJson);
    // return (0, yarn_parser_1.stringifyYarnLockfile)(prunedGraph, content, normalizedPackageJson);
    return content;
}
```
3. Run the build again
4. Copy also the generated `package.json` from the dist folder. Again I'm only interested in the dependencies so you can omit the remaining stuff.

That should give me enough info to be able to reproduce your issue.
