### ISSUE TITLE
Lint breaks after updating from 19.0.5 to 19.0.6

### ISSUE THREAD

**Issue by TomTomB** [nrwl/nx#25319]
### Current Behavior

After updating to nx 19.0.6, linting will fail inside an angular monorepo. This only ocurres  if the user has updated the `@typescript-eslint/*` packages from 7.3.0 to e.g. latest (7.10.0). I guess this has to do with https://github.com/nrwl/nx/pull/24632.

### Expected Behavior

Linting should not break during patch releases.

### Steps to Reproduce

1. Create a default nx monorepo with the angular preset and choose integrated instead of standalone.
2. Update `@typescript-eslint/eslint-plugin` and `@typescript-eslint/parser` to 7.10.0
3. Lint. npx nx run-many -t lint --skip-nx-cache

### Nx Report

```shell
Node   : 20.11.1
OS     : linux-x64 (WSL)
yarn   : 1.22.21

nx                 : 19.0.6
@nx/js             : 19.0.6
@nx/jest           : 19.0.6
@nx/linter         : 19.0.6
@nx/eslint         : 19.0.6
@nx/workspace      : 19.0.6
@nx/angular        : 19.0.6
@nx/devkit         : 19.0.6
@nx/eslint-plugin  : 19.0.6
@nx/playwright     : 19.0.6
@nrwl/tao          : 19.0.6
@nx/web            : 19.0.6
@nx/webpack        : 19.0.6
typescript         : 5.4.5
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
```

### Failure Logs

```shell
✖  nx run eslint-issue:lint
      Linting "eslint-issue"...
      
       NX   Error while loading rule '@angular-eslint/template/banana-in-box': You have used a rule which requires '@angular-eslint/template-parser' to be used as the 'parser' in your ESLint config.
      
      Occurred while linting some/file/path....
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by mgansler** [comment]
I have noticed a very similar behaviour:

```
Linting "components"...
 NX   context.getScope is not a function
Occurred while linting /builds/mgansler/plusone/libs/components/cypress/support/commands.ts:14
Rule: "import/no-amd"
```

Worked fine with 19.0.5 but is broken with 19.0.6 and no other changes.

**Comment by SteveW94** [comment]
I experienced the same.

Due to this the Update PR is currently on hold

**Comment by Tijawk** [comment]
I have huge performance issue with `lerna` since I have updated `nx` from 19.0.5 to 19.0.6. I use `@typescript-eslint` too, 

I think it's the same probleme. I have rollback to 19.0.5.

**Comment by FrozenPandaz** [comment]
> I have huge performance issue with lerna since I have updated nx from 19.0.5 to 19.0.6. I use @typescript-eslint/*@7.10.0 too,
> 
> I think it's the same probleme. I have rollback to 19.0.5.

Mm.. this isn't much details but I think this might be a separate issue unrelated to this one.

>  NX   context.getScope is not a function

Thank you for reporting it. We'll look into it.

**Comment by JamesHenry** [comment]
@TomTomB @mgansler @SteveW94 Maybe you are now pulling in eslint v9?

Please try running this command or similar and see what version of eslint is getting pulled in:

```
npm ls eslint
```

**Comment by JamesHenry** [comment]
@Tijawk Please open a fresh issue for your case with maximum information/steps to reproduce

**Comment by TomTomB** [comment]
@JamesHenry Both eslint versions (8.57.x, and 9.x) result in the same error.

**Comment by SteveW94** [comment]
@JamesHenry 
This is before the installation of 19.0.6

![image](https://github.com/nrwl/nx/assets/36530889/43e84bfd-4726-4421-a172-495846855354)

As you can see no eslint 9
Just after installation of 19.0.6

![image](https://github.com/nrwl/nx/assets/36530889/d3ff3240-ec6d-412b-82e9-432f76b18862)

You can see,  @nx/eslint@19.0.6 is the culprit, as it references eslint 9!

In my package .json there is:
"eslint": "8.57.0" pinned. So no Semver Tag or anything.

So I would say, this way ESLint "sneaks" in there should not be intended!

**Comment by mgansler** [comment]
with 19.0.5:

```
yarn why v1.22.22
[1/4] 🤔  Why do we have the module "eslint"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "eslint@8.57.0"
info Has been hoisted to "eslint"
info Reasons this module exists
   - Specified in "devDependencies"
   - Hoisted from "@nx#eslint#eslint"
info Disk size without dependencies: "5.5MB"
info Disk size with unique dependencies: "15.11MB"
info Disk size with transitive dependencies: "18.44MB"
info Number of shared dependencies: 80
```

With 19.0.6:
```
yarn why v1.22.22
[1/4] 🤔  Why do we have the module "eslint"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "eslint@8.57.0"
info Has been hoisted to "eslint"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "5.38MB"
info Disk size with unique dependencies: "14.99MB"
info Disk size with transitive dependencies: "18.29MB"
info Number of shared dependencies: 82
=> Found "@nx/eslint#eslint@9.3.0"
info This module exists because "@nx#eslint" depends on it.
info Disk size without dependencies: "3.8MB"
info Disk size with unique dependencies: "11.71MB"
info Disk size with transitive dependencies: "15.73MB"
info Number of shared dependencies: 80
```

And with eslint removed from my package.json (and Nx 19.0.6):
```
y why eslint
yarn why v1.22.22
[1/4] 🤔  Why do we have the module "eslint"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "eslint@9.3.0"
info Reasons this module exists
   - "@nx#eslint" depends on it
   - Hoisted from "@nx#eslint#eslint"
info Disk size without dependencies: "5.34MB"
info Disk size with unique dependencies: "14.5MB"
info Disk size with transitive dependencies: "18.33MB"
info Number of shared dependencies: 71
```

Same error though, still `context.getScope is not a function`

**Comment by mgansler** [comment]
When I force eslint to 8.57.0, linting works:
```
 "resolutions": {
    "eslint": "8.57.0"
  }
  ```

**Comment by SteveW94** [comment]
👍🏼

**Comment by JamesHenry** [comment]
FYI we confirmed this is only an issue with yarn. The other package managers behave how we expected and to not force the eslint v9 dependency upon you. We are still discussing the ultimate resolution to this.

**Comment by terrymun** [comment]
Can confirm that this is also an issue with pnpm too. Currently on `nx@19.2.3` and upgrading eslint from 8.57.0 → 9.5.0 is causing issues.

**Comment by JamesHenry** [comment]
@terrymun It's better to open a fresh issue with full context about your specific circumstances, rather than commenting on closed issues. If you are choosing to upgrade from 8 to 9 as your comment suggests then it already confirms it is not directly related to this specific issue.

If you open a fresh issue the team will happily take a look
