### ISSUE TITLE
[Angular][Module Federation] Router issue after updating nx from 14.5.8 to 14.8.2

### ISSUE THREAD

**Issue by DamianTt** [nrwl/nx#12369]
## Current Behavior
I have simple POC (master branch): https://github.com/DamianTt/NxAngularModuleFederationDocker
 that works with nx 14.5.8. It has Module Federation architecture - host and remotes. Remotes have defined routing as RouterModule.forChild([...]). Unfortunately it doesn't work after update nx version to 14.8.2 (see failure log below). There is no error if I remove routing from remote app - that's why I think the problem is connected with Angular Router 

## Expected Behavior
Routing in remote app works after updating nx version to 14.8.2

## Steps to Reproduce
https://github.com/DamianTt/NxAngularModuleFederationDocker/tree/routerIssue - branch routerIssue. Run `npm run dev`, navigate to http://localhost:4200/, then click 'App1' and you will see an error in console.

1. Create Nx workspace
2. Create Host application
3. Create Remote application
4. Add routing to remote application as RouterModule.forChild([...])

### Failure Logs
```default-node_modules_angular_core_fesm2020_core_mjs.js:1 ERROR Error: Uncaught (in promise): Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with EnvironmentInjector#runInContext. Find more at https://angular.io/errors/NG0203
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `EnvironmentInjector#runInContext`. Find more at https://angular.io/errors/NG0203
    at injectInjectorOnly (core.mjs:4775:15)
    at Module.ɵɵinject (core.mjs:4786:12)
    at Object.RouterModule_Factory [as useFactory] (router.mjs:7026:1)
    at Object.factory (core.mjs:6974:38)
    at R3Injector.hydrate (core.mjs:6887:35)
    at R3Injector.get (core.mjs:6775:33)
    at injectInjectorOnly (core.mjs:4782:33)
    at ɵɵinject (core.mjs:4786:12)
    at useValue (core.mjs:6567:65)
    at R3Injector.resolveInjectorInitializers (core.mjs:6824:17)
    at resolvePromise (zone.js:1211:31)
    at resolvePromise (zone.js:1165:17)
    at zone.js:1278:17
    at _ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:26218:33)
    at _ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:585:35)
```

### Environment
```Node : 16.13.2
   OS   : win32 x64
   npm  : 8.1.2

   nx : 14.8.2
   @nrwl/angular : 14.8.2
   @nrwl/cypress : 14.8.2
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.8.2
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.2
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.8.2
   @nrwl/js : 14.8.2
   @nrwl/linter : 14.8.2
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.2
   @nrwl/web : Not Found
   @nrwl/webpack : 14.8.2
   @nrwl/workspace : 14.8.2
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
```

**Comment by galenwilk** [comment]
I'm seeing the same error on a recently generated MFE Angular application running on nx 14.8.2.

**Comment by Coly010** [comment]
Hey :) This issue has been resolved in a recent fix and it'll be released on a stable release with Nx 15.

For now, if you'd like to avail of the fix you can run `nx migrate next` and `nx migrate --run-migrations`.

I hope this helps!

**Comment by cougdoble** [comment]
@Coly010 apologies if I'm missing this in an obvious place, but did this fix get released in a patch for v14 as well? I didn't see it in any change logs, and upgrading to 15 is not an option for my organization at the moment. Currently experiencing this issue in 14.8.4

**Comment by Coly010** [comment]
@cougdoble No, the fix will not have been backported unfortunately

**Comment by Coly010** [comment]
We will be working to make `@nrwl/angular` compatible with more versions of Anguar in the near future. At that stage you should be able to migrate the tooling independently to your angular version

**Comment by PascalHB** [comment]
Hi @Coly010,

I just updated to nrwl/workspace 15.7.2 by using nx migrate latest and running the migrations. It still shows the same error - wasn't it fixed yet? Or do I need to do anything specific to fix it?

Thank you
Pascal

**Comment by DamianTt** [comment]
Hi @PascalHB 
I just updated nx version to 15.7.2 in the repository I wrote about in the main post and it works for me. You can take a look here, there is a branch named 'nx-update-15-7-2': https://github.com/DamianTt/NxAngularModuleFederationDocker/tree/nx-update-15-7-2

**Comment by ryanjpburgos** [comment]
Hi @Coly010,

I'm facing the same issue with the version 15.8.5 of NX and the version 15.2.0 of Angular
![image](https://user-images.githubusercontent.com/49457859/224107616-d9a6e3a4-11aa-46b8-89ca-39197c7a67ea.png)

**Comment by vigie** [comment]
Yes the issue seems to be back as of latest (15.8.6) @Coly010 . Just going through the [default example](https://nx.dev/recipes/module-federation/faster-builds) with nothing extra and I get the above error.

I can see that two copies of angular core are generated and one is requested by the host and the other by the remote

![Screenshot 2023-03-16 at 11 01 34 AM](https://user-images.githubusercontent.com/5872403/225711406-afb0192b-bb42-4566-8eb8-1bcf338cfd6d.png)
![Screenshot 2023-03-16 at 11 01 27 AM](https://user-images.githubusercontent.com/5872403/225711423-ce20b622-7ea2-409c-8ee6-f80aea9423cf.png)

**Comment by vigie** [comment]
FYI, I just confirmed that downgrading back to 15.7.2 fixes the issue.
