### ISSUE TITLE
Cannot find module 'lazy' when running Express/Node application with esbuild in v15 and v16.0.0

### ISSUE THREAD

**Issue by wizardnet972** [nrwl/nx#16530]
### Current Behavior

The issue occurs in version 15 and 16.0.0. I developed an application using Express and Node.js, using the `apps` preset (bundler `esbuild`) When I run the provided code snippet:
```
import express from 'express';

const host = process.env.HOST ?? 'localhost';
const port = process.env.PORT ? Number(process.env.PORT) : 3000;

const app = express();

app.get('/', (req, res) => {
  res.send({ message: 'Hello API' });
});

app.listen(port, host, () => {
  console.log(`[ ready ] http://${host}:${port}`);
});

import('./lazy').then((x) => {
  console.log({ x });
});
```
Unfortunately, when I ran this code, I encountered an error message that stated that the module at the following path could not be found:

> Error: Cannot find module '/Users/wizardnet972/sandbox/nx-import-node/dist/apps/nx-api/apps/nx-api/src/lazy' imported from /Users/wizardnet972/sandbox/nx-import-node/dist/apps/nx-api/apps/nx-api/src/main.js

The error occurred because the compiler esbuild was unable to locate the lazy file.

### Expected Behavior

Be able to find the lazy file and complete the promise

### GitHub Repo

https://github.com/wizardnet972/nx-import-node.git

### Steps to Reproduce

Clone the repo.
Run serve nx-api

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node : 18.13.0
   OS   : darwin arm64
   npm  : 9.3.0

   nx                      : 15.9.2
   @nrwl/js                : 15.9.2
   @nrwl/jest              : 15.9.2
   @nrwl/linter            : 15.9.2
   @nrwl/workspace         : 15.9.2
   @nrwl/cli               : 15.9.2
   @nrwl/devkit            : 15.9.2
   @nrwl/esbuild           : 15.9.2
   @nrwl/eslint-plugin-nx  : 15.9.2
   @nrwl/node              : 15.9.2
   @nrwl/tao               : 15.9.2
   @nrwl/webpack           : 15.9.2
   typescript              : 4.9.5
```
```


### Failure Logs

```shell
➜  nx-import-node git:(main) ✗ npx nx serve nx-api

> nx run nx-api:serve:development

[ watch ] build succeeded, watching for changes...
Debugger listening on ws://localhost:9229/d6ebb9f0-7af3-4f8c-bcf8-6482ed62f8bc
Debugger listening on ws://localhost:9229/d6ebb9f0-7af3-4f8c-bcf8-6482ed62f8bc
For help, see: https://nodejs.org/en/docs/inspector
Error: Cannot find module '/Users/wizardnet972/sandbox/nx-import-node/dist/apps/nx-api/apps/nx-api/src/lazy' imported from /Users/wizardnet972/sandbox/nx-import-node/dist/apps/nx-api/apps/nx-api/src/main.js
    at new NodeError (node:internal/errors:400:5)
    at finalizeResolution (node:internal/modules/esm/resolve:326:11)
    at moduleResolve (node:internal/modules/esm/resolve:945:10)
    at defaultResolve (node:internal/modules/esm/resolve:1153:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:842:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1151:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:438:21)
```
```


### Additional Information

_No response_

**Comment by jaysoo** [comment]
@wizardnet972 This is a tricky one. The error is because Node does not support dynamic `import(...)` without an extension. Normally there is some Node resolution that happens for a static `require` that is skipped here.

The fix is to write `import('./lazy.js')` with the file extension of the output file. Don't worry, TypeScript understand this just fine. Once you make that change you can compile and run the app just fine.

**Comment by wizardnet972** [comment]
@jaysoo Thank you!
