### ISSUE TITLE
Cant run apps after migrating from nx 13 to 14

### ISSUE THREAD

**Issue by JWood48** [nrwl/nx#10233]
## Current Behavior

running my-app:server:development --open fails with `Cannot find module './ArraySerializer'`

## Expected Behavior
Should start app

## Steps to Reproduce
N/A

### Failure Logs
```
Cannot find module './ArraySerializer'
Require stack:
- C:\app\node_modules\webpack\lib\serialization\ObjectMiddleware.js
- C:\app\node_modules\webpack\lib\util\serialization.js
- C:\app\node_modules\webpack\lib\util\makeSerializable.js
- C:\app\node_modules\webpack\lib\DependenciesBlock.js
- C:\app\node_modules\webpack\lib\Module.js
- C:\app\node_modules\webpack\lib\RuntimeModule.js
- C:\app\node_modules\webpack\lib\index.js
- C:\app\node_modules\@nrwl\web\src\executors\dev-server\dev-server.impl.js
- C:\app\node_modules\nx\src\config\workspaces.js
- C:\app\node_modules\nx\src\command-line\run.js
- C:\app\node_modules\nx\bin\run-executor.js
```
tried removed node_modules and yarn.lock - same error

NOTE: many  nx commands opens a console window with the following error:

```
[process exited with code 1 (0x00000001)]
```

### Environment
```
>  NX   Report complete - copy this into the issue template

   Node : 16.13.0
   OS   : win32 x64
   yarn : 1.22.17
   
   nx : 14.1.4
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.1.4
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.4
   @nrwl/eslint-plugin-nx : 14.1.4
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.4
   @nrwl/js : 14.1.4
   @nrwl/linter : 14.1.4
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.1.4
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.4
   @nrwl/web : 14.1.4
   @nrwl/workspace : 14.1.4
   typescript : 4.3.5
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
         @nx-tools/nx-docker: 1.0.5

Done in 0.71s.
```

**Comment by AgentEnder** [comment]
Hey @JWood48, can you run `npm ls webpack` and throw those results here? Thanks.

**Comment by JWood48** [comment]
Sure:
```
$ yarn why webpack
yarn why v1.22.17
[1/4] Why do we have the module "webpack"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "webpack@4.46.0"
info Has been hoisted to "webpack"
info Reasons this module exists
   - Hoisted from "@storybook#core-server#webpack"
   - Hoisted from "@storybook#react#webpack"
   - Hoisted from "@storybook#core-server#@storybook#builder-webpack4#webpack"
   - Hoisted from "@storybook#core-server#@storybook#core-common#webpack"
   - Hoisted from "@storybook#core-server#@storybook#manager-webpack4#webpack"
info Disk size without dependencies: "5.72MB"
info Disk size with unique dependencies: "10.92MB"
info Disk size with transitive dependencies: "28.36MB"
info Number of shared dependencies: 112
=> Found "@nrwl/react#webpack@5.72.0"
info This module exists because "@nrwl#react" depends on it.
=> Found "@nrwl/web#webpack@5.72.0"
info This module exists because "@nrwl#web" depends on it.
=> Found "@storybook/builder-webpack5#webpack@5.72.0"
info This module exists because "@storybook#builder-webpack5" depends on it.
=> Found "@storybook/manager-webpack5#webpack@5.72.0"
info This module exists because "@storybook#manager-webpack5" depends on it.
=> Found "eslint-config-kentcdodds#webpack@5.72.0"
info This module exists because "kcd-scripts#eslint-config-kentcdodds" depends on it.
Done in 2.55s.
```

**Comment by JWood48** [comment]
I dont know how to read this, but it seems that storybook uses webpack 4 but nx uses webpack 5??
