### ISSUE TITLE
 npx nx generate <some commands> fail with:   NX   Cannot find module '../adapter/compat' in angular app

### ISSUE THREAD

**Issue by newaeonweb** [nrwl/nx#17142]
### Current Behavior

After update v15(Nx and Angular) to v16 some commands fail to execute with  `NX   Cannot find module '../adapter/compat'`. Using the **vscode extension** or by running the command directly in the terminal.

### Expected Behavior

Able to generate Angular components/services/guards/etc... using the vscode extension or via the terminal

### Steps to Reproduce

1. Migrate some Nx/Angular from v15 to v16
2. Try to generate some components, services, etc...

### Nx Report

```shell
Node   : 16.18.0
   OS     : darwin arm64
   npm    : 8.19.2
   Hasher : Native
   
   nx (global)        : 16.1.0
   nx                 : 16.2.1
   @nx/js             : 16.2.1
   @nx/jest           : 16.2.1
   @nx/linter         : 16.2.1
   @nx/workspace      : 16.2.1
   @nx/angular        : 16.2.1
   @nx/cypress        : 16.2.1
   @nx/devkit         : 16.2.1
   @nx/eslint-plugin  : 16.2.1
   @nx/storybook      : 16.2.1
   @nrwl/tao          : 16.2.1
   @nx/webpack        : 16.2.1
   typescript         : 5.0.4
   ---------------------------------------
   Community plugins:
   @nguniversal/builders       : 16.0.2
   @nguniversal/express-engine : 16.0.2
   @storybook/angular          : 7.0.12
   nx-stylelint                : 14.0.2

```
```


### Failure Logs

```shell
>  NX  Generating @schematics/angular:resolver


 >  NX   Cannot find module '../adapter/compat'

   Require stack:
   - /Users/.../node_modules/nx/src/command-line/generate/generate.js
   - /Users/.../node_modules/nx/src/command-line/generate/command-object.js
   - /Users/.../node_modules/nx/src/command-line/nx-commands.js
   - /Users/.../node_modules/nx/bin/init-local.js
   - /Users/.../node_modules/nx/bin/nx.js
   Pass --verbose to see the stacktrace.
```
```


### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

_No response_

**Comment by leosvelperez** [comment]
This has been fixed in https://github.com/nrwl/nx/pull/17090 and will be released in Nx 16.3.0. Please keep an eye on the releases to get the fix.
