### ISSUE TITLE
Invalid types when adding Cypress support

### ISSUE THREAD

**Issue by comatory** [nrwl/nx#32930]
### Current Behavior

After adding a Cypress configuration to a library, using [documentation instructions](https://nx.dev/docs/technologies/test-tools/cypress/introduction#configure-cypress-for-an-existing-project), Typescript errors are raised when running `typecheck` target.

### Expected Behavior

Running `typecheck` target should pass.

### GitHub Repo

https://github.com/productboardlabs/nx-cypress-typecheck-bug

### Steps to Reproduce

1. `pnpm dlx create-nx-workspace@latest`
2. Select React stack.
3. Framework None
4. No React Router
5. Vite for bundler
6. Vitest for tests
7. Test runner: Cypress
8. CSS for default styles
9. Eslint: yes
10. Prettier: yes
11. No coding agent
12. No CI provider
13. No remote cache
14. `pnpm add @nx/cypress`
15. `pnpm nx g @nx/js:library libs/feature`
16. Select `vite` bundler, `eslint` and `vitest`
17. `pnpm nx g @nx/cypress:configuration`, select `@nx-cypress-typecheck-bug/feature`, use `vite` as bundler, `eslint`, `@nx-cypress-typecheck-bug/feature:serve` target, port `3000`
18. `pnpm nx sync`
19. Run `pnpm nx typecheck feature`

You will see errors

### Nx Report

```shell
Node           : 22.15.0
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 10.17.1

nx                     : 21.6.2
@nx/js                 : 21.6.2
@nx/eslint             : 21.6.2
@nx/workspace          : 21.6.2
@nx/cypress            : 21.6.2
@nx/devkit             : 21.6.2
@nx/eslint-plugin      : 21.6.2
@nx/module-federation  : 21.6.2
@nx/react              : 21.6.2
@nx/rollup             : 21.6.2
@nx/vite               : 21.6.2
@nx/web                : 21.6.2
typescript             : 5.9.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/eslint/plugin
@nx/vite/plugin
@nx/cypress/plugin
---------------------------------------
Cache Usage: 0.00 B / 46.04 GB
```

### Failure Logs

```shell
cypress/e2e/app.cy.ts:8:8 - error TS2551: Property 'login' does not exist on type 'cy & CyEventEmitter'. Did you mean 'log'?

8     cy.login('my-email@something.com', 'myPassword');
         ~~~~~

  ../node_modules/.pnpm/cypress@14.5.4/node_modules/cypress/types/cypress.d.ts:1567:5
    1567     log(message: string, ...args: any[]): Chainable<null>
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    'log' is declared here.

cypress/support/commands.ts:13:9 - error TS2669: Augmentations for the global scope can only be directly nested in external modules or ambient module declarations.

13 declare global {
           ~~~~~~

cypress/support/commands.ts:24:22 - error TS2345: Argument of type '"login"' is not assignable to parameter of type 'keyof Chainable<any>'.

24 Cypress.Commands.add('login', (email, password) => {
```

### Package Manager Version

pnpm@10.17.1

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by tomalaforge** [comment]
it happened to us when we updated TS from 5.5 to 5.9.

**Comment by tomalaforge** [comment]
@jaysoo this does work for cypress e2e tests but we still have the issue for CCT.

**Comment by jaysoo** [comment]
@tomalaforge This should fix it https://github.com/nrwl/nx/pull/33906

**Comment by tomalaforge** [comment]
Ok Thanks but it doesn't work for me, I have this error

````
TS2345: Argument of type 'mount' is not assignable to parameter of type keyof Chainable<any>
```
