### PR TITLE
fix(nextjs): produce correct next.config.js file for production server

### LINKED ISSUE #15796: next.js build is broken since 15.8.7
### Current Behavior

`dist/packages/next-app/with-nx.js`

contains imports from `@nrwl/devkit, @nrwl/workspace/src/utilities/buildable-libs-utils and ../src/utils/config`
which are not resolvable when trying to run app in production. Even if `@nrwl` deps are installed, there is no way to resolve relative import because it's relative to nx sources. 

### Expected Behavior

STR results in app running

### GitHub Repo

https://github.com/glibvoronin/nx-next-build-issue

### Steps to Reproduce

1. `nx build next-app`
2. `cd dist/packages/next-app && npm i`
3. `npm start`

### Nx Report

```shell
Node : 16.17.0
   OS   : darwin arm64
   npm  : 8.15.0
   
   nx                      : 15.8.7
   @nrwl/js                : 15.8.7
   @nrwl/jest              : 15.8.7
   @nrwl/linter            : 15.8.7
   @nrwl/workspace         : 15.8.7
   @nrwl/cli               : 15.8.7
   @nrwl/cypress           : 15.8.7
   @nrwl/devkit            : 15.8.7
   @nrwl/eslint-plugin-nx  : 15.8.7
   @nrwl/next              : 15.8.7
   @nrwl/react             : 15.8.7
   @nrwl/tao               : 15.8.7
   @nrwl/webpack           : 15.8.7
   typescript              : 4.9.5
```

### Failure Logs

```shell
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Cannot find module '../src/utils/config'
Require stack:
- /Users/glibvoronin/projects/nx-next-build-issue/dist/packages/next-app/with-nx.js
- /Users/glibvoronin/projects/nx-next-build-issue/dist/packages/next-app/next.config.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:956:15)
    at Function.mod._resolveFilename (/Users/glibvoronin/projects/nx-next-build-issue/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Function.Module._load (node:internal/modules/cjs/loader:804:27)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/glibvoronin/projects/nx-next-build-issue/dist/packages/next-app/with-nx.js:8:18)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/glibvoronin/projects/nx-next-build-issue/dist/packages/next-app/with-nx.js',
    '/Users/glibvoronin/projects/nx-next-build-issue/dist/packages/next-app/next.config.js'
  ]
}
```

### Additional Information

Most probably caused by https://github.com/nrwl/nx/pull/15650

`@nrwl/next@15.8.6` works perfectly fine

### PR DESCRIPTION
**Pull request by jaysoo**
This PR fixes an issue where the generated `next.config.js` file errors out due to `with-nx.js` referencing relative paths that do no exist.

For reference, the reason we previously used a compiled version of `with-nx.js` rather than `@nrwl/next/plugins/with-nx` is because `@nrwl/next` installs development packages (e.g. Cypress, Webpack, etc.) that bloated the built artifact. See: https://github.com/nrwl/nx/issues/12150

This fix has two components:
1. Move dependencies on `@nrwl/cypress`, `@nrwl/jest`, and `@nrwl/webpack`. from `packages/next/package.json` into `ensurePackage` whenever they are used by generators. This change addresses the package size issue.
2. Remove the compiled version of `with-nx.js` and use the normal plugin again. This requires a check on the "phase" so that webpack and eslint configurations are only added when doing builds. By checking the phase, we no longer need access to Nx graph since everything has already been compiled into `.next.`.

## Current Behavior
Production build cannot run

## Expected Behavior
Production build can run

## Related Issue(s)

Fixes #15796

### CODE REVIEW

File: packages/next/src/executors/build/lib/create-next-config-file.ts [hunk 1]
```diff
@@ -1,17 +1,9 @@
...
-import * as ts from 'typescript';
-import { existsSync, readFileSync, writeFileSync } from 'fs';
+import { ExecutorContext } from '@nrwl/devkit';
+
+import { copyFileSync, existsSync } from 'fs';
 import { join } from 'path';
 
-import type { NextBuildBuilderOptions } from '../../../utils/types';
-import { findNodes } from 'nx/src/utils/typescript';
+import { NextBuildBuilderOptions } from '../../../utils/types';
```
Comment (ndcunningham) [inline packages/next/src/executors/build/lib/create-next-config-file.ts:6]: Should this still be imported as a type?

**Review by ndcunningham — APPROVED** [review]
